### ISSUE TITLE
FreeOTP 2FA Code "Invalid" in Web and Mobile

### ISSUE THREAD

**Issue by robDAO** [tutao/tutanota#1380] opened 2019-07-25 10:53 UTC
**Bug in mobile app**
2FA Code from the FreeOTP Auth App is not working.

**Describe the bug**
Copy the code and paste it in the 2FA prompt box of Tutanota during login and get error message "Invalid Credentials"

**Smartphone (please complete the following information):**
 - Device: [XIaomi Redmi4]
 - OS: [Android Latest Release]
 - Version [Latest Release]

**Comment by armhub** [comment] 2019-07-26 15:07
This is a duplicate of #284.

**Closed by armhub** 2019-07-26 15:07 UTC
Labels: bug
