### ISSUE TITLE
After failing TOTP/OTP I get only "temporary server error" 

### ISSUE THREAD

**Issue by EinfachNurBaum** [tutao/tutanota#5879] opened 2023-09-13 18:06 UTC
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Describe the bug**
After the TOTP's input popup has expired you only get "Server error" when you try again. Even restarting the Deskstop app does not help. 
I use andOPT (android third party app - not playstore app- for TOTP)
Dekstop App for Windows 10
German UI

**To Reproduce**
1. Enter Email and password
2. Click on log in (I use the german UI so Idk if it is Sign in, Sign Up or Log in)
3. Get the error pop up "temporary server error/problem"

**Expected behavior**
Show the "Enter your OTP"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Desktop Environment, if applicable (on Linux)
 - Version: I got this error already in earlier Windows versions

**Comment by charlag** [comment] 2023-09-14 07:16
Duplicate of #5868

**Closed by charlag** 2023-09-14 07:16 UTC
Labels: bug, desktop

**Comment by ganthern** [comment] 2023-09-14 07:21
Thank you for the report anyway @EinfachNurBaum, It's not obvious that this was a duplicate.
