### ISSUE TITLE
I cannot access my account in Linux client anymore

### ISSUE THREAD

**Issue by Ludwigklages** [tutao/tutanota#7267] opened 2024-07-24 14:03 UTC
I was always able to use Linux client trough Appimage till recent problem. Since last update (currently I'm using v.235.240718.0) I cannot sign in my account. In my Android client I'm still get access to my account without problem. The Appimage works normal, I see the sign-in secreen. I enter my username and pasword (still no problem). When I write my authetication code I recieve an error.

My Distro: Linux Mint 20.3

**This is the error mesage from client:**

Feedback v235.240718.0 - Error - UNKNOWN - linux

 Client: linux
 Type: UNKNOWN
 Tutanota version: 235.240718.0
 Timestamp (UTC): Wed, 24 Jul 2024 13:37:37 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/235.240718.0 Chrome/126.0.6478.61 Electron/31.0.2 Safari/537.36
Error
 Error message: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoAt5Y5c/resources/app.asar.unpacked/desktop/better-sqlite3.node)
Stacktrace: 
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoAt5Y5c/resources/app.asar.unpacked/desktop/better-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at new Fe (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/better-sqlite3-Bu0ZH0B8.js:1:18578)
    at l.openDb (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/sqlworker.js:1:5985)

**A also copied the logs. These are the logs when I tried to get access:**

v235.240718.0 - linux

 Client: linux
 Type: UNKNOWN
 Tutanota version: 235.240718.0
 Timestamp (UTC): Wed, 24 Jul 2024 13:56:41 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/235.240718.0 Chrome/126.0.6478.61 Electron/31.0.2 Safari/537.36

== MAIN LOG ==
2024-07-24T13:53:33.012Z I 
2024-07-24T13:53:33.080Z I "error",OfflineDbClosedError
 Error message: Offline db is closed,"OfflineDbClosedError: Offline db is closed\n    at get db (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:23:123900)\n    at _P.all (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:25:1034)\n    at _P.getAllCredentials (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:25:113)\n    at sD.loadAll (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:274447)\n    at _D.dispatch (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:289733)\n    at FD.dispatch (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:295777)\n    at ipc (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:285352)\n    at exports.MessageDispatcher.handleMessage (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/better-sqlite3-Bu0ZH0B8.js:1:32100)\n    at /tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/better-sqlite3-Bu0ZH0B8.js:1:31208\n    at /tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:277015"
2024-07-24T13:53:33.082Z E "Encountered error when trying to handle errors with ErrorHandlerImpl",OfflineDbClosedError
 Error message: Offline db is closed
2024-07-24T13:53:33.108Z I "worker init time (ms):",145
2024-07-24T13:53:38.192Z I "removed topmost modal component"
2024-07-24T13:55:05.934Z I "removed topmost modal component"
2024-07-24T13:55:07.058Z I "removed topmost modal component"
2024-07-24T13:55:08.787Z I "removed topmost modal component"
2024-07-24T13:55:30.331Z I "removed topmost modal component"
2024-07-24T13:55:32.758Z I "removed topmost modal component"
2024-07-24T13:55:33.970Z I "removed topmost modal component"
2024-07-24T13:55:52.968Z I "webauthn supported: ",true
2024-07-24T13:56:35.527Z I "removed topmost modal component"
2024-07-24T13:56:35.530Z I "error",Error,"Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutanoAt5Y5c/resources/app.asar.unpacked/desktop/better-sqlite3.node)\n    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)\n    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)\n    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)\n    at Module.load (node:internal/modules/cjs/loader:1215:32)\n    at Module._load (node:internal/modules/cjs/loader:1031:12)\n    at c._load (node:electron/js2c/node_init:2:17025)\n    at Module.require (node:internal/modules/cjs/loader:1240:19)\n    at require (node:internal/modules/helpers:179:18)\n    at new Fe (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/better-sqlite3-Bu0ZH0B8.js:1:18578)\n    at l.openDb (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/sqlworker.js:1:5985)"
2024-07-24T13:56:35.530Z I "Unknown error",Error
2024-07-24T13:56:35.757Z I "error",OfflineDbClosedError
 Error message: Offline db is closed,"OfflineDbClosedError: Offline db is closed\n    at get db (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:23:123900)\n    at _P.get (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:25:971)\n    at _P.getCredentialEncryptionMode (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:25:1098)\n    at sD.getCredentialEncryptionMode (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:274263)\n    at _D.dispatch (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:290062)\n    at FD.dispatch (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:295777)\n    at ipc (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:285352)\n    at exports.MessageDispatcher.handleMessage (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/better-sqlite3-Bu0ZH0B8.js:1:32100)\n    at /tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/better-sqlite3-Bu0ZH0B8.js:1:31208\n    at /tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:277015"
2024-07-24T13:56:35.758Z E "Encountered error when trying to handle errors with ErrorHandlerImpl",OfflineDbClosedError
 Error message: Offline db is closed
2024-07-24T13:56:35.957Z I "error",OfflineDbClosedError
 Error message: Offline db is closed,"OfflineDbClosedError: Offline db is closed\n    at get db (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:23:123900)\n    at _P.get (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:25:971)\n    at _P.getCredentialEncryptionMode (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:25:1098)\n    at sD.getCredentialEncryptionMode (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:274263)\n    at _D.dispatch (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:290062)\n    at FD.dispatch (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:295777)\n    at ipc (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:285352)\n    at exports.MessageDispatcher.handleMessage (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/better-sqlite3-Bu0ZH0B8.js:1:32100)\n    at /tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/better-sqlite3-Bu0ZH0B8.js:1:31208\n    at /tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:11:277015"
2024-07-24T13:56:35.958Z E "Encountered error when trying to handle errors with ErrorHandlerImpl",OfflineDbClosedError
 Error message: Offline db is closed
2024-07-24T13:56:38.527Z I "removed topmost modal component"
2024-07-24T13:56:39.899Z I "removed topmost modal component"

== WORKER LOG ==
2024-07-24T13:56:13.313Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/secondfactorauthservice?_body=%7B%22_format%22%3A%220%22%2C%22accessToken%22%3A%22W3pY6SEAAUAC5oW-M3ERrCMdqlZ1wYul2w%22%7D",0,"",["v","cv","Content-Type","Accept"],"[66 characters]"
2024-07-24T13:56:13.314Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/secondfactorauthservice?_body=%7B%22_format%22%3A%220%22%2C%22accessToken%22%3A%22W3pY6SEAAUAC5oW-M3ERrCMdqlZ1wYul2w%22%7D",0,"",["v","cv","Content-Type","Accept"],"[66 characters]"
2024-07-24T13:56:33.895Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/secondfactorauthservice?_body=%7B%22_format%22%3A%220%22%2C%22accessToken%22%3A%22W3pY6SEAAUAC5oW-M3ERrCMdqlZ1wYul2w%22%7D",0,"",["v","cv","Content-Type","Accept"],"[66 characters]"
2024-07-24T13:56:33.895Z I "[RestClient]","failed request","GET","https://app.tuta.com/rest/sys/secondfactorauthservice?_body=%7B%22_format%22%3A%220%22%2C%22accessToken%22%3A%22W3pY6SEAAUAC5oW-M3ERrCMdqlZ1wYul2w%22%7D",0,"",["v","cv","Content-Type","Accept"],"[66 characters]"
2024-07-24T13:56:35.525Z I "generating new database key for persistent session"
2024-07-24T13:56:35.530Z E "Error while initializing offline cache storage",Error
2024-07-24T13:56:35.626Z I "ws connect reconnect:",false,"state:","terminated"
2024-07-24T13:56:35.633Z I "initIndexer after log in"
2024-07-24T13:56:35.734Z I "ws open state:","automatic"
2024-07-24T13:56:35.736Z I "New leader status set:",true
2024-07-24T13:56:36.240Z I "{\"indexingTime\":0,\"storageTime\":0,\"preparingTime\":0,\"mailcount\":0,\"storedBytes\":0,\"encryptionTime\":0,\"writeRequests\":0,\"largestColumn\":0,\"words\":0,\"indexedBytes\":0,\"downloadingTime\":0}","total time: ",0

== NATIVE LOG ==
2024-07-24T13:36:41.620Z I "the monkey has been patched pid:",68452
2024-07-24T13:36:42.056Z I "retrying to create credentials db"
2024-07-24T13:36:42.056Z I "deleting credentials db"
2024-07-24T13:36:42.086Z I "version:  ","235.240718.0"
2024-07-24T13:36:42.221Z I "resolving key...","tutanota-vault"
2024-07-24T13:36:42.222Z I "config up to date"
2024-07-24T13:36:42.371Z I "[2024-07-24T13:36:42.358Z]","using safeStorage with backend","gnome_libsecret"
2024-07-24T13:36:42.510Z I "[DesktopMain]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2024-07-24T13:36:42.511Z I "[2024-07-24T13:36:42.511Z]","Create tray:true"
2024-07-24T13:36:42.515Z I "[SSEFacade]","last missed notification check:",{"lastMissedNotificationCheckTime":1721828196086}
2024-07-24T13:36:42.517Z I "[ApplicationWindow]","webAssetsPath: ","/tmp/.mount_tutanoAt5Y5c/resources/app.asar"
2024-07-24T13:36:42.657Z I "default mailto handler:",false
2024-07-24T13:36:42.658Z I "Webapp ready"
2024-07-24T13:36:42.666Z I "[2024-07-24T13:36:42.666Z]","[ElectronUpdater]","INFO:","Checking for update"
2024-07-24T13:36:42.666Z I "[2024-07-24T13:36:42.666Z]","[ElectronUpdater]","INFO:","checking-for-update"
2024-07-24T13:36:42.667Z I "[SSE]","connect"
2024-07-24T13:36:42.694Z I "[SSE]","state:","connecting"
2024-07-24T13:36:42.735Z I "[DesktopMain]","spellcheck-dictionary-initialized","de"
2024-07-24T13:36:42.775Z I "desktop file exists, checking version..."
2024-07-24T13:36:42.775Z I "version mismatch, reintegrating..."
2024-07-24T13:36:42.776Z I "[SSE]","lookup"
2024-07-24T13:36:42.776Z I "[SSE]","lookup"
2024-07-24T13:36:42.888Z I "[DesktopMain]","getting dictionaries from:","https://app.tuta.com/desktop/dictionaries/"
2024-07-24T13:36:42.917Z I "[DesktopMain]","spellcheck-dictionary-initialized","de"
2024-07-24T13:36:42.937Z I "[SSE]","established SSE connection with code",200
2024-07-24T13:36:42.937Z I "[SSE]","state:","connected"
2024-07-24T13:36:42.938Z I "[SSE]","heartbeat"
2024-07-24T13:36:42.938Z I "[SSE]","state:","connected"
2024-07-24T13:36:42.938Z I "[SSEFacade]","heartbeatTimeout","240"
2024-07-24T13:36:42.939Z I "[SSE]","heartbeat"
2024-07-24T13:36:42.939Z I "[SSE]","state:","connected"
2024-07-24T13:36:42.939Z I "[SSEFacade]","notification"
2024-07-24T13:36:42.939Z I "[SSE]","heartbeat"
2024-07-24T13:36:42.939Z I "[SSE]","state:","connected"
2024-07-24T13:36:42.940Z I "[SSEFacade]","last missed notification check:",{"lastMissedNotificationCheckTime":1721828196086}
2024-07-24T13:36:42.940Z I "[SSEFacade]","downloading missed notification"
2024-07-24T13:36:42.953Z I "[SSE]","state:","connected"
2024-07-24T13:36:43.040Z I "[2024-07-24T13:36:43.040Z]","[ElectronUpdater]","INFO:","Update for version 235.240718.0 is not available (latest version: 235.240718.0, downgrade is disallowed)."
2024-07-24T13:36:43.041Z I "[2024-07-24T13:36:43.040Z]","[ElectronUpdater]","INFO:","update not available:",{"version":"235.240718.0","files":[{"url":"tutanota-desktop-linux.AppImage","sha512":"qrP0BCDJJMr9NJSCC9zdmAEomW4TXLooftxJOpPCbmnI/N6pehsFYbaqh7OQOGq4d9/U5fj5pyO4MZS7rOsUwg==","size":127302353,"blockMapSize":133861}],"path":"tutanota-desktop-linux.AppImage","sha512":"qrP0BCDJJMr9NJSCC9zdmAEomW4TXLooftxJOpPCbmnI/N6pehsFYbaqh7OQOGq4d9/U5fj5pyO4MZS7rOsUwg==","releaseDate":"2024-07-19T11:46:10.394Z","signature":"McW8KnxVUVuua2UMt4ZPYyLw0l0c7tmBZknHBIyqbs/EmBeQE8H0mY1+DKfdiKiolUYQL6M+w6TzNkawmiuIxRJ/gvJWLj52R2RmhRUrxzqkqBQL1VK1DJV6RfrbvD/1SKcaUih6cnKuDligPLgtUmj79XbP1uX25B4DpfnHl2hwBdN7uD8wbpv7Mwys+GlmOhJ10hUgurHjw6a5Ci9j0Mg1ejO9XvwCPQ2EcKMIoQ2q4JmzMqBfUjKb4LDBpKy2MxWS6s1qgKVG+jNh5gug5UDLBYljS0iX9PmgJYOJgu4vcqnfiF0uPoSm0qQKbo0cnBhm2gnuVIfrEgaFbUiOMQ=="}
2024-07-24T13:36:43.070Z I "[SSEFacade]","downloaded missed notification"
2024-07-24T13:37:17.550Z I "[ProtocolProxy]","error for GET https://app.tuta.com/rest/sys/secondfactorauthservice:"
2024-07-24T13:37:17.551Z I "[ProtocolProxy]",?
2024-07-24T13:37:17.551Z I "[ProtocolProxy]","{\"name\":\"TypeError\",\"message\":\"fetch failed\",\"stack\":\"TypeError: fetch failed\\n    at Kp (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:10:1472)\\n    at async /tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:10:30651\\n    at async AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:51554)\"}"
2024-07-24T13:37:17.551Z I "[ProtocolProxy]","failed after 20294ms"
2024-07-24T13:37:37.562Z I "[OfflineDbRefCounter]","Deleting db for user LrdNuGR----1"
2024-07-24T13:37:37.562Z I "deleting db for","LrdNuGR----1"
2024-07-24T13:37:37.562Z I "[OfflineDbRefCounter]","Deleted db for user LrdNuGR----1"
2024-07-24T13:37:37.563Z I "[PerWindowSqlCipherFacade]","open db for","LrdNuGR----1"
2024-07-24T13:37:37.567Z I "[2024-07-24T13:37:37.567Z]","[WorkerSqlCipher]","started sqlcipher-worker-1"
2024-07-24T13:37:37.681Z I "[2024-07-24T13:37:37.681Z]","[sqlcipher-worker-1]","set up sql cipher done"
2024-07-24T13:37:37.686Z I "retrying to create db","LrdNuGR----1"
2024-07-24T13:37:37.686Z I "deleting db for","LrdNuGR----1"
2024-07-24T13:37:37.687Z I "[2024-07-24T13:37:37.687Z]","[WorkerSqlCipher]","started sqlcipher-worker-2"
2024-07-24T13:37:37.798Z I "[2024-07-24T13:37:37.797Z]","[sqlcipher-worker-2]","set up sql cipher done"
2024-07-24T13:40:42.936Z I "[SSE]","heartbeat"
2024-07-24T13:40:42.936Z I "[SSE]","state:","connected"
2024-07-24T13:41:30.955Z I "[SSE]","state:","connected"
2024-07-24T13:44:43.492Z I "[SSE]","heartbeat"
2024-07-24T13:44:43.492Z I "[SSE]","state:","connected"
2024-07-24T13:46:19.517Z I "[SSE]","state:","connected"
2024-07-24T13:48:43.489Z I "[SSE]","heartbeat"
2024-07-24T13:48:43.490Z I "[SSE]","state:","connected"
2024-07-24T13:51:07.616Z I "[SSE]","state:","connected"
2024-07-24T13:52:43.489Z I "[SSE]","heartbeat"
2024-07-24T13:52:43.489Z I "[SSE]","state:","connected"
2024-07-24T13:53:32.077Z I "[ApplicationWindow]","webAssetsPath: ","/tmp/.mount_tutanoAt5Y5c/resources/app.asar"
2024-07-24T13:55:55.617Z I "[SSE]","state:","connected"
2024-07-24T13:56:13.312Z I "[ProtocolProxy]","error for GET https://app.tuta.com/rest/sys/secondfactorauthservice:"
2024-07-24T13:56:13.312Z I "[ProtocolProxy]",?
2024-07-24T13:56:13.312Z I "[ProtocolProxy]","{\"name\":\"TypeError\",\"message\":\"fetch failed\",\"stack\":\"TypeError: fetch failed\\n    at Kp (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:10:1472)\\n    at async /tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:10:30651\\n    at async AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:51554)\"}"
2024-07-24T13:56:13.312Z I "[ProtocolProxy]","failed after 20346ms"
2024-07-24T13:56:33.894Z I "[ProtocolProxy]","error for GET https://app.tuta.com/rest/sys/secondfactorauthservice:"
2024-07-24T13:56:33.894Z I "[ProtocolProxy]",?
2024-07-24T13:56:33.894Z I "[ProtocolProxy]","{\"name\":\"TypeError\",\"message\":\"fetch failed\",\"stack\":\"TypeError: fetch failed\\n    at Kp (/tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:10:1472)\\n    at async /tmp/.mount_tutanoAt5Y5c/resources/app.asar/desktop/DesktopMain.js:10:30651\\n    at async AsyncFunction.<anonymous> (node:electron/js2c/browser_init:2:51554)\"}"
2024-07-24T13:56:33.894Z I "[ProtocolProxy]","failed after 20579ms"
2024-07-24T13:56:35.529Z I "[OfflineDbRefCounter]","Deleting db for user LrdNuGR----1"

As I said, so far I had absolutely no problem in my linux client. Only with last update something went broken.

**Comment by rezbyte** [comment] 2024-07-25 07:55
Hi @Ludwigklages,
Thank you for your report. We are already aware of this issue and a fix is planned. Stay tuned for the coming updates!

Duplicate of #7133.

**Closed by rezbyte** 2024-07-25 07:55 UTC
Labels: bug, desktop
