### ISSUE TITLE
Tutanota Desktop keeps logging me out 

### ISSUE THREAD

**Issue by ThracianKnight1907** [tutao/tutanota#3258] opened 2021-07-07 09:09 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**

Tutanota seems to log me out, for no reason. I can log in, but it seems to log me out again after a reboot.

**To Reproduce**

1. Log in
2. Reboot

**Expected behavior**

Tutanota keeps me logged in

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Desktop Environment, if applicable (on Linux): Gnome 40

I am using the Tutanota flatpak, v 3.84.10

**Comment by ThracianKnight1907** [comment] 2021-07-07 09:16
Now it kept me logged in, but this happened twice in the last few days. It could also be caused by updates, so I'll have to see

**Comment by charlag** [comment] 2021-09-02 14:02
Flatpak is still not completely functional although I use it on Fedora without issues.

**Comment by charlag** [comment] 2022-03-04 13:06
Closing this as we cannot reproduce it and it is also Flatpak specific so should be reported under Flathub repo if still relevant

**Closed by charlag** 2022-03-04 13:06 UTC
Labels: bug, desktop
