### ISSUE TITLE
Desktop/web/mobile: feature request to add support for changing language in settings

### ISSUE THREAD

**Issue by matsest** [tutao/tutanota#1072] opened 2019-01-31 11:42 UTC
As suggested to Tutanota on [Twitter](https://twitter.com/TutanotaTeam/status/1090931261965852673), I would like to suggest that you add an option for changing app language in the settings.

As many users use English as a system language, either by habit or e.g. company policy, it is useful to be able to change to their native language for some apps and not for others (e.g. MS Office changes shortcuts when changing system/app language).

I also believe that this could improve translation quality over time as more users would see the setting and actually test out their native language translation. It is also useful for actually translating as it's faster to see the translation in the app itself instead of being forced to change system language.

Thanks!

**Comment by Mxchaeltrxn** [comment] 2019-09-16 06:58
Can I still work on this feature?

**Comment by charlag** [comment] 2019-09-16 07:31
It is actually implemented as part of #1357 

Duplicate of #1357

**Closed by charlag** 2019-09-16 07:31 UTC
Labels: improvement

**Comment by Mxchaeltrxn** [comment] 2019-09-16 07:35
I see. This is a feature I'd like to use but I don't see where it is on my desktop app. I'm not sure if this is the right place to ask but could you tell me where this feature is?

**Comment by charlag** [comment] 2019-09-16 07:36
It's in the settings/appearance/language
