### ISSUE TITLE
Unread mail icon stuck permanently on trash folder despite there being no unread mail

### ISSUE THREAD

**Issue by rdragonrydr** [tutao/tutanota#4376] opened 2022-07-16 23:12 UTC
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
I permanently have a "1 unread" icon in my trash folder even though the unread message has been there more than 30 days and is now gone.

**To Reproduce**
I deleted an unread email (for whatever reason, my computer was lagging or something, so when I hit the trash button in my inbox, it moved it to garbage before opening it and marking it read) and left it to auto-expire the 30 day trash timer.

Now the email is indeed gone from my trash, but the "1 unread" icon is still present on the trash folder.

I am not sure if this would also happen with a "normal" marked-unread message or if that race condition I mentioned earlier could have been involved.

**Expected behavior**
Unread emails in trash being deleted after 30 days should also decrement the unread-emails badge on the folder.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 102.0
 - Version: Tutanota 3.98.12

**Comment by charlag** [comment] 2022-07-18 07:24
Hi
Auto-deleted emails also should change the counter but it could be that one update got lost.
If you scroll to the end of the list the counter should fix itself.

**Comment by charlag** [comment] 2022-07-18 07:45
It seems like there's a new issue

**Comment by rdragonrydr** [comment] 2022-07-19 11:49
> Hi Auto-deleted emails also should change the counter but it could be that one update got lost. If you scroll to the end of the list the counter should fix itself.

I had tried that and it didn't work. I was scrolling all the way back to see if the unread message was still there and reached the end of the list without finding it, but the number didn't get reset.

**Comment by alstr** [comment] 2022-07-23 06:54
This has been a bug for as long as I can remember. Hoping for a fix soon as it’s pretty annoying!

**Comment by andreldm** [comment] 2022-08-13 20:29
Besides my +1, I suggest removing that counter from trash folder all together, gmail behaves like this which I think it's a sane decision, oftentimes I delete emails without opening them and have to open them in trash just to get rid of this annoying counter. By the way, I see the stuck counter both in Firefox and the Android app.

**Comment by KaoriRinaFujimoto** [comment] 2022-09-21 04:46
+1 from me as well.  
Even though I've been a Tutanota subscriber for a long time, I just started to run into this issue...
A fix would be highly appreciated - even if it's just by removing the counter as previous posters have suggested.

**Comment by charlag** [comment] 2022-09-21 07:06
It is fixed now and about to be released
duplicate of #4417

**Closed by charlag** 2022-09-21 07:06 UTC
Labels: bug

**Comment by alstr** [comment] 2022-09-26 07:52
Not sure if this is related, but now although the trash unread icon is potentially fixed, I'm seeing ghost emails in my inbox that I've already deleted. I can't delete them - the buttons don't work and the message body just says "This element cannot be displayed correctly. If possible, please ask the sender to re-send this message". Every time I log in they appear as unread again. Only getting this on macOS. I'll open a new issue if it persists but just thought I'd mention.

**Comment by andreldm** [comment] 2022-09-28 18:14
Is this bug really fixed? I'm using v3.101.1 in desktop/firefox and v3.100.2 in android, in both cases the counter is still stuck.

**Comment by charlag** [comment] 2022-09-29 07:24
@andreldm  You need to scroll to the bottom of the list and wait for a few seconds

**Comment by andreldm** [comment] 2022-09-30 11:45
> @andreldm You need to scroll to the bottom of the list and wait for a few seconds

That solved the issue, thanks!
