### ISSUE TITLE
Stopped working in PaleMoon last week or so

### ISSUE THREAD

**Issue by hiiamboris** [tutao/tutanota#3828] opened 2022-01-21 14:30 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**

Nothing is being loaded at all, just an empty page (a week ago worked fine):
<img src=https://i.gyazo.com/fdcacaec8f933742cf7c9039625e5e05.png width=300></img> <img src=https://i.gyazo.com/b0807e268e25514e015fd97f25971df8.png width=300></img>

User agent spoofing doesn't seem to help either.

**To Reproduce**

1. [Download PaleMoon](https://www.palemoon.org/download.php?mirror=eu&bits=32&type=7z) and start
2. Open https://mail.tutanota.com/mail

**Expected behavior**

Working web interface

**Desktop (please complete the following information):**
 - OS: W10 10.0.19043.1415
 - Browser: Pale Moon 29.4.4

**Comment by charlag** [comment] 2022-01-21 16:32
Duplicate of #3830

**Closed by charlag** 2022-01-21 16:32 UTC
Labels: bug
