### ISSUE TITLE
Refresh issue with deleted and new emails

### ISSUE THREAD

**Issue by arentsen** [tutao/tutanota#3671] opened 2021-11-11 15:13 UTC
I have to refresh (in the browser) often to be able to see my deleted emails vanish from the inbox or to see the latest emails that already came in. In the desktop version I often have to logout and login again before I see my new mail or before delete works.

It would be great if switching accounts could be done in one click, with a dropdown button for instance. Right now you have to do two clicks which can be a lot if you have to do it often.

I am on macOS Big Sur.

**Comment by ganthern** [comment] 2021-12-07 10:31
Regarding the account switch dropdown, the mac client should show a list of all currently opened windows in the dock symbol's context menu. It's possible to have multiple windows logged into different accounts.

**Comment by ganthern** [comment] 2021-12-07 10:37
@arentsen could this be related to your refresh issue? https://github.com/tutao/tutanota/issues/3449

**Comment by charlag** [comment] 2022-03-04 12:45
I believe that this is indeed a duplicate of #3449

**Closed by charlag** 2022-03-04 12:45 UTC
Labels: bug, desktop
