### ISSUE TITLE
pinch-to-zoom

### ISSUE THREAD

**Issue by nokhub** [tutao/tutanota#4962] opened 2023-01-10 16:45 UTC
Replace double tapping with pinch-to-zoom. Also support pinch-to-zoom in non-HTML emails unlike the double tap.

spike: #1997

**Comment by blankscreengithub** [comment] 2023-09-30 13:52
This still has not been implemented yet, although an email from said they did.

**Comment by charlag** [comment] 2023-10-02 07:27
duplicate of  #1997

**Closed by charlag** 2023-10-02 07:27 UTC
Labels: improvement, android, ios
