### ISSUE TITLE
CryptoError: invalid mac

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#3003] opened 2021-04-30 13:11 UTC
Reported by several users via feedback email.

**Comment by jowlo** [comment] 2021-04-30 13:23
In 2915169bf4fe2e58846973444c7e21257b247f8f we changed it so we prepend a `0x1` to the data if using a MAC.

Two questions:
 * what happens if the first IV byte is also `0x1`?
 * what do we do with data that was saved with the previous version (with MAC but without the prepended flag)

**Comment by Open-wan** [comment] 2021-04-30 13:28
Similar issue, since 2-3 releases - W10 LTSC

at DesktopMain.js:1:415399
at Object.aes256Decrypt
at DesktopMain.js:1:415739)
at Object.aesDecryptObject
at DesktopMain.js:13:205269)
at Object._getEncryptedVar
at DesktopMain.js:13:208726)
at async
at DesktopMain.js:13:246033

**Comment by jowlo** [comment] 2021-04-30 13:43
@Open-wan that would fit with 2915169 which was introduced with the release `v3.82.13`

**Comment by bingoxo** [comment] 2021-05-01 12:15
i have same bug and i can't get notifications on windows desktop app , are they related ?

**Comment by charlag** [comment] 2021-05-03 11:29
@jowlo if there's no mac then the data is shorter (even length instead of odd)
We didn't use this function before.

**Comment by 0xktz** [comment] 2021-05-06 16:26
I'm having this issue as well, the app is constantly dead in the background. fixing it would be really appreciated

**Comment by Open-wan** [comment] 2021-05-25 11:58
Still have this issue at each opening of Tutanota Desktop W10 LTSC
Popup "An error occured"

Feedback v3.83.7 - CryptoError - PREMIUM - win32
Client: win32
Type: PREMIUM
Tutanota version: 3.83.7
Timestamp (UTC): Tue, 25 May 2021 11:56:01 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.83.7 Chrome/87.0.4280.141 Electron/11.4.6 Safari/537.36
CryptoError
Error message: invalid mac


"Ignore the error for this session" didn't work.

**Comment by Open-wan** [comment] 2021-05-27 06:46
Ok: 
- deleting tutanota desktop App
- manually deleting C:\Users\xxxxxxxxxx\AppData\Roaming\tutanota-desktop

Problem solved

**Comment by bedhub** [comment] 2021-06-03 06:16
duplicate of #3111. Is fixed in version 3.84.4

**Closed by bedhub** 2021-06-03 06:16 UTC
Labels: bug, duplicate
