### ISSUE TITLE
android app battery hungry

### ISSUE THREAD

**Issue by letkan** [tutao/tutanota#476] opened 2018-07-19 15:42 UTC
Version 3.35.7 on CrDroid Nougat/Mi 4c.
Tutanota:
keep awake 21m 28s
battery 10%

K-9 Mail:
keep awake 3m 55s
battery 1%

Same period of time (since last charge), about 18 hours. Kind of unacceptable if you ask me. Basically the app just checks with the server very often, no mail sent or received.

**Comment by jg0ra** [comment] 2018-07-19 17:18
I think the same thing. See https://github.com/tutao/tutanota/pull/459
Also, SSE events occurs every 30 seconds and it doesn't help for going into deep sleep.

**Comment by letkan** [comment] 2018-07-19 17:48
Well, I read the thread but having very limited programming knowledge I can't participate or take sides, my observation is empirical. All I can suggest is for you to fork, implement your logic and let's compare.

**Comment by jg0ra** [comment] 2018-07-19 19:13
Since tutanota server side send an event every 30 seconds , it can't be battery friendly only releasing JobService's wakelock or using a Service instead. So, I decide to leave it because awake time was reduced but not enough as K9 mail

**Comment by letkan** [comment] 2018-07-19 19:55
Ok, now I get it. That's a problem, practically the client hardly sleeps. Can't those 30 seconds be adjustable?

**Comment by charlag** [comment] 2018-07-20 05:57
Hi @letkan. Sorry to give you troubles. We are still tweaking things and will be in the next months.
First of all, which Android version do you use? Did you exclude Tutanota from the battery optimizations? (we ask you about this on the first launch).
I have excluded Tutanota from battery optimizations and on Oreo I barely notice battery impact - it barely crosses 2-3%. We may still give an option in the future where we don't keep the connection open.

30 seconds was chosen for the firewalls. Most of them will block connections from the outside after some time (original connection implementation which we use has 10 seconds default interval!)

**Comment by charlag** [comment] 2018-07-20 05:58
@jg0ra our initial implementation used service. Not only cannot we run on Oreo without notification, but also battery consumption wasn't better.
Do you know how k9 handles this? They don't do push notifications I assume.

**Comment by letkan** [comment] 2018-07-20 07:02
Good morning @charlag, I'm on Nougat right now (see first post) and I did exclude Tutanota from optimization. I can't use Oreo just yet because there is no reliable rom for my device ATM.

**Comment by jg0ra** [comment] 2018-07-20 07:30
@charlag K9 mail uses imap, not applicable to tutanota.
I fighted a lot with incorrect GCM heartbeat intervals. Reducing it to 300 seconds, connections are keep alive without being shut down by firewalls. See https://play.google.com/store/apps/details?id=com.andqlimax.pushfixer
Only using a Service or releasing JobService's wakelock, will not help on battery consumption if event interval is not reduced. For starting a service in Oreo, may be mandatory use startForegroundService

**Comment by charlag** [comment] 2018-07-20 12:02
@letkan I don't propose you using Oreo, just collecting more info

@jg0ra thanks for the lead, we can adjust interval from the server side so maybe it is a good idea to increase it more.
With Oreo launching foreground service is very tricky, because you cannot use PRIORITY_MIN for notifications. So we gave it up and it is better. We will look into increasing interval in the next two weeks, team is quite busy atm and I cannot change it alone. Thanks for understanding.

**Comment by prog-amateur** [comment] 2018-07-20 22:51
Hello. Would be better (easier) if we could use Tutanota on K9 mail (at least unencrypted emails), but it is my opinion.

**Comment by charlag** [comment] 2018-07-28 17:04
Letting you know that we've increased the heartbeat interval to 4 mins on the server side so it should help

**Comment by letkan** [comment] 2018-07-29 12:08
Great, let's see how it goes

**Comment by jgora** [comment] 2018-07-30 11:30
I'm testing on Nougat with my fork.
At the moment, battery consumption is not more than 1% per hour and awake time at 8%.
So, looks good.

**Comment by charlag** [comment] 2018-07-30 11:59
It's 1% for me too on Oreo with upstream, I think increasing interval really helps. If we find nothing funny in a few days, we may close it

**Comment by letkan** [comment] 2018-07-31 12:51
This is working very well now, thanks.

**Comment by prog-amateur** [comment] 2018-08-12 10:34
On my side, it is still consuming a LOT of battery. Around 10%, just behind the display. 
I am on version 3.35.4, with battery saver off for this app.

**Comment by charlag** [comment] 2018-08-13 06:01
@prog-amateur hi! Glad to hear it's better but it still sounds like a lot of battery.
We have no plans on integrating with K-9. We use e2e encryption and we don't have an SMTP/IMAP bridge yet. You would lose all the benefits of the encryption.

**Comment by prog-amateur** [comment] 2018-08-13 11:56
@charlag too bad, but I can understand the encryption point of view. 

Just for information, since I have reboot my phone, I confirm that it is consuming 17% of battery. 507 mAh, the app is awoken since 3h37mn. That's huge, I can't explain the cause of this issue. 
My version and setup are the same as yesterday, when Tutanota was around 4% of battery consumption (so still version 3.35.13 from F-Droid, with battery optimization disabled). 

I think you have a big challenge to solve ^^

**Comment by jgora** [comment] 2018-08-13 16:44
I think it could be due to JobService wakelock. See https://github.com/tutao/tutanota/pull/459
You could confirm it with Wakelock Detector

In my fork, without JobService and 4 min SSE events interval, battery  consumtion is very fine

**Comment by prog-amateur** [comment] 2018-08-13 23:00
It is possible that JobService wakelock is the issue, but I can't confirm as I am not expert. 
However, I insist and come back to say that the app is now 30% of battery consumption, with 877mAh (!!!). 

This is abnormal, am I the only one with this huge battery consumption ? 
I would be forced to uninstall it because I would have to always reload my smartphone.

**Comment by charlag** [comment] 2018-08-14 05:38
@prog-amateur that sounds weird, we couldn't send so much just for notifications, did you index mailbox in that time?

**Comment by prog-amateur** [comment] 2018-08-14 17:59
Hello, what do you mean by index mailbox ? (sorry I am far to be an expert). 
I just have installed tutanota from F-Droid, and I didn't change anything from the settings in my mailbox.

**Comment by charlag** [comment] 2018-08-15 05:44
@prog-amateur when you enable the search it needs to download and decrypt a lot of stuff and create indexes so that you can search your inbox (in can only be done locally (remember, it's e2e encrypted, server cannot do that). This process takes a lot of energy of course.

**Comment by prog-amateur** [comment] 2018-08-20 11:32
@charlag just to be sure I understood your feedback : do you mean that if I want to keep a good battery life, I should disable the search option ? 
Or does it do it only once, then it can have a good battery life because index will be done by increment ? 
Thank you

**Comment by charlag** [comment] 2018-08-21 05:57
It affects it especially after turning on but shouldn't matter much otherwise

**Comment by prog-amateur** [comment] 2018-08-27 14:36
![img_eggsif_9028188172349438084](https://user-images.githubusercontent.com/33793118/44665794-522ce600-aa06-11e8-9da1-29f9b6a4f8ea.png)



This is what I have everyday. I want to be clear : 
- I didn't modify anything in Tutanota app setup (just install)
- I have no specific battery software installed, just Android
- Tutanota is not optimized by the battery management in Android (no app sleep)

What can I do ?

**Comment by charlag** [comment] 2018-08-27 15:00
Try to enable battery optimizations? This is super weird, we don't see it on our devices

**Comment by prog-amateur** [comment] 2018-08-27 23:02
I agree, it is really weird as I didn't changed anything to Tutanota setup, just install and that's it. 
I have just started to use battery optimizations. I will try to feedback soon.

**Comment by prog-amateur** [comment] 2018-08-28 22:44
Today since the latest full load, I have 16% with 450mAh battery consumption, which is still high. 
What I still don't understand is the ~ 17000 packages sent/received. I still suspect this as a strange behavior for only one email account, moreover I didn't received any email today. 
Too bad that @letkan letkan didn't come back to compare. Definitively, there is something wrong with this app, this is not related to the user side.

**Comment by jgora** [comment] 2018-08-31 08:35
@prog-amateur install https://play.google.com/store/apps/details?id=com.uzumapps.wakelockdetector.noroot for gaining more information.
You will need a rooted device or connecting the device to a computer for grant the required permission to the app via adb command line.
Without more information, will stay at a dead end

**Comment by budbay** [comment] 2018-09-03 02:42
i am also having an issue with the app keeping my device awake and draining battery.  i am on android 8.1 oreo and have battery optimization off as requested.  the last version that worked well was 3.35.4, i have tried every version since from fdroid and playstore but keep experiencing high drain and go back to 3.35.4, i have tried updating and clean installs with same affect.  the wakelock is "*job*/de.tutao.tutanota/.push.PushNotificationService" i have attached 4 screen shots the first two are the stats from first part of day with 3.35.4 installed, the last two are after uninstalling 3.35.4 and installing 3.36.4 from fdroid. as you can see my device goes from 3% awake (which is my usual average) to 10% awake.  i have tried running the newer versions for a few days to see if the would "settle in" and would see awake time as high as 25%.  any help here is appreciated.
![screenshot_20180902-150859](https://user-images.githubusercontent.com/25737221/44964933-abaa7e80-aef8-11e8-8ec8-74f08b665598.png)
![screenshot_20180902-150908](https://user-images.githubusercontent.com/25737221/44964934-abaa7e80-aef8-11e8-9b6f-b7f12fe73564.png)
![screenshot_20180902-200459](https://user-images.githubusercontent.com/25737221/44964935-abaa7e80-aef8-11e8-9ca7-09f3174452ce.png)
![screenshot_20180902-200506](https://user-images.githubusercontent.com/25737221/44964936-abaa7e80-aef8-11e8-8268-35faec731cb6.png)

**Comment by charlag** [comment] 2018-09-03 08:10
Hi, thanks for the screenshots. As far as I can see, doze interactive time is the same as screen time.
Would be nice if you could try with optimizations on and post it here.
I am considering giving users two options: power saving or timely notifications (it is already implicitly works like that with Android battery optimizations toggle but we can adapt better if we know user preferences perhaps).
We are open to other suggestions except ditching job for foreground service, we tried it for a long time and it was far worse

**Comment by jgora** [comment] 2018-09-03 08:40
@charlag  Release jobservice's wakelock returning false https://github.com/tutao/tutanota/pull/459
I see that PushNotificationService::connect method will work without any kind of wakelock if battery optimizations are turned off, as my fork is able to work in this way (with a service instead of a jobservice, but without acquiring any kind of wakelock)

**Comment by charlag** [comment] 2018-09-03 08:43
I can try making a test build and posting it here so everyone affected could try it out

**Comment by jgora** [comment] 2018-09-03 08:53
@charlag I think it's a goot idea.
If @prog-amateur and @budbay can't try it, I will

**Comment by budbay** [comment] 2018-09-03 15:16
I can try out a test build when your ready, thanks for the quick responses.

**Comment by budbay** [comment] 2018-09-03 19:14
Could I ask what the difference is between the two versions? As I stated 3.35.4 works well for me battery wise and seems to use "*job*/de.tutao.tutanota/.push.PeriodicJobRestartService"  and the  newer versions using " job /de.tutao.tutanota/.push.PushNotificationService" causes me the issues.  If possible I was just hoping to understand the difference.

**Comment by charlag** [comment] 2018-09-04 05:08
We tried the approach where Job is only used to restart the service, but the problem is that you cannot start a service from a job so push notifications did not work properly when the app is not in foreground.

**Comment by charlag** [comment] 2018-09-11 06:44
Hi everyone!
Sorry for the delay on this, we've been preoccupied with other problems.
With commits 9212cd2e61b7fd31c823bd5e6b7830544b044153 & 10b2b1832d43a7922a4ff6eefa5f3702f0504a18
This is a version which tries to release wakelock after reading notifications object or after 15 second after establishing a connection.
This is a rather conservative approach but I think we should start with that.
Please test with & without battery optimizations.
Forcing phone into Doze using ADB would be nice too.
Please report your Android version and phone model. Would be nice if you mentioned how big delays were.
[tutanota-3.36.7-jo.zip](https://github.com/tutao/tutanota/files/2369617/tutanota-3.36.7-jo.zip)

**Comment by budbay** [comment] 2018-09-11 20:33
I'm at work currently but gave a shot at installing this.  I kept getting an error logging in, can't connect to network.  So I went back to older version.  If I have time after work I will give another go and see if I can collect more info.

**Comment by letkan** [comment] 2018-09-12 08:10
The error is: Couldn't reach server, looks like you are offline. Please try again later
I believe these are the relevant lines from logcat:

`09-12 10:45:53.184 24976 24976 I chromium: [INFO:CONSOLE(1)] "createSession worker", source: file:///android_asset/tutanota/dist/worker.js (1)
09-12 10:45:53.275 24976 24976 I chromium: [INFO:CONSOLE(1)] "failed to request", source: file:///android_asset/tutanota/dist/worker.js (1)
09-12 10:45:54.382 24976 24976 I chromium: [INFO:CONSOLE(1)] "error", source: file:///android_asset/tutanota/dist/main-boot.js (1)`

**Comment by charlag** [comment] 2018-09-12 11:04
Than it's my fault, will post another one later

**Comment by charlag** [comment] 2018-09-13 06:26
Another newer version
[tutanota-3.36.9-jo.zip](https://github.com/tutao/tutanota/files/2377939/tutanota-3.36.9-jo.zip)

**Comment by budbay** [comment] 2018-09-14 02:18
so i tried the new test with and without battery optimizations with similar results, i actually think this test version kept the device awake more than before. i appreciate the attention to this issues. heres a couple screens
![_20180913_071438](https://user-images.githubusercontent.com/25737221/45525860-5bee7180-b79a-11e8-8dd6-19be9b6782cf.JPG)
![screenshot_20180913-072336](https://user-images.githubusercontent.com/25737221/45525865-5ee96200-b79a-11e8-90d7-d79baeb6f4d8.png)

**Comment by charlag** [comment] 2018-09-14 05:51
What is `PeriodicJobRestartService`? We don't have it for many versions already. My guess is that you never completely uninstalled the app and it is still there from the early versions.

I don't understand why device is more awake than before because in the test version we explicitly end job after some time

**Comment by letkan** [comment] 2018-09-14 07:38
Here are my stats with the test app, I sent/received  3 emails with minimal content just for testing. To me it seems this version behaves better then the release though I find no justification for the 7MB data transfer. I wish this test app had a debug log so that one can see what exactly is going on..

![screenshot_20180914-101621](https://user-images.githubusercontent.com/9017461/45536131-32b8fa00-b809-11e8-87ef-85c300b9947d.png)

![screenshot_20180914-101641](https://user-images.githubusercontent.com/9017461/45536137-3a789e80-b809-11e8-87d3-1a222b544dee.png)

**Comment by charlag** [comment] 2018-09-14 08:04
@letkan I'm not sure that the data counter is correct tbh.
There are debug logs but you may need permission to see them.
Look for :pushprocess process

**Comment by letkan** [comment] 2018-09-14 08:27
On Fri, Sep 14, 2018 at 11:04 AM, Ivan Kupalov <notifications@github.com>
wrote:

> @letkan <https://github.com/letkan> I'm not sure that the data counter is
> correct tbh.
>
Yeah,  I also thought that was absurd. After posting the comment I checked
the phone's own battery stats on the app and it showed 2MB over the last
month so I knew something was fishy which is why I thought of logs.

> There are debug logs but you may need permission to see them.
> Look for :pushprocess process
>
Where do I find them?

**Comment by charlag** [comment] 2018-09-14 14:59
There was an error on our server side because of which we were sending more data than usual (and battery could be affected as well). I will notify you when it's fixed. Sorry for the inconvenience.

**Comment by budbay** [comment] 2018-09-15 03:54
@charlag , yeah that was my bad, I installed over old version.  That's what I get for testing on break at work.  I am off the next few days so I'll do a clean install and test further.

**Comment by budbay** [comment] 2018-09-16 03:06
So I gave a proper test today. last night I did a clean install of the test.apk, removed all data from other version.  first few hours this morning phone was sleeping like a baby, so i sent myself an email from desktop.  I got the notification fairly quick, after that the wakelock and awake time were pretty similar as before.  tried with and without battery optimizations.  the battery impact did seem slightly better.  just a thought, but would it be possible maybe to have a setting where user could specify a polling interval? anyhow here are a few screens from the day, first two are from before the email notification, last two were at end of the day.
![screenshot_20180915-115717](https://user-images.githubusercontent.com/25737221/45592457-89baee00-b933-11e8-97ef-16ad4866cdd4.png)
![screenshot_20180915-115730](https://user-images.githubusercontent.com/25737221/45592458-89baee00-b933-11e8-9c09-3ff707b91000.png)
![screenshot_20180915-180222](https://user-images.githubusercontent.com/25737221/45592459-8a538480-b933-11e8-8adb-8dadb5a11521.png)
![screenshot_20180915-180228](https://user-images.githubusercontent.com/25737221/45592460-8a538480-b933-11e8-9576-0152df0b0b2a.png)

**Comment by charlag** [comment] 2018-09-17 05:14
@budbay thanks for testing! It seems like my mechanism "disconnect after 15 sec" doesn't work properly but I'm glad notifications still do work and battery usage is better. I'll try making some more changes and post another version later. There's no polling interval, there's a heartbeat/timeout interval around 4 minutes.

@letkan you can find logs using ADB or something like MatLog

**Comment by jgora** [comment] 2018-09-17 07:09
@charlag I have bad experiences with Thread.sleep() in android. Sometimes it stops the whole app.
Since onStartJob only starts the connect task in looperThread as a background thread (if not already connected), Why not releasing wakelock for letting device going into deep sleep mode?
IMHO Tcp works during deep sleep.

**Comment by letkan** [comment] 2018-09-17 15:45
@charlag I was referring to a log file written by the app somewhere (enable/disable logging in preferences?).

**Comment by charlag** [comment] 2018-09-18 05:17
@letkan the app always writes to Android log. It is unusual for Android apps to write to their own log

@jgora the contract clearly says "return true if job is done" but it is clearly not right after startup. I don't want to risk not receiving notifications in hope that Android doesn't kill us afterwards, we need to receive at least something. I've never heard any concerns about `Thread.sleep()` except that, for sure, you will stop the whole app if you run it on UI thread

**Comment by charlag** [comment] 2018-09-18 12:50
@jgora doesn't releasing wakelock mean that we won't receive notifications? Did you try it out?

**Comment by jgora** [comment] 2018-09-18 17:08
Although the jobservice's wakelock would be released, the threadLoop will continue running if battery optimization is off. This thread will receive SSE events and post notifications.
If thread stops due to IOException, for example, next scheduled job execution will restart it.
My fork is working without any kind of wakelock. Certainly with a service that starts the threadLoop as main diference.

**Comment by charlag** [comment] 2018-09-19 06:10
If battery optimizations are on, job would not have a chance to fetch notifications, right?
I did not understand what you meant by the last sentence.

**Comment by jgora** [comment] 2018-09-19 06:27
If battery optimizations are on, the https connection for SSE will be shutdowned by Doze.
The threadloop may be stopped (I suppose).
The jobservice will be able to start periodically.
User experience will not be like push notifications.
You can explore the effects installing without granting android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS to, for example, https://f-droid.org/es/packages/eu.siacs.conversations/

**Comment by letkan** [comment] 2018-09-19 06:54
For what it's worth, last night i built @jgora 's fork with his changes and battery discharge overnight (7h) was 3% (total) including 4MB of data transferred by the app due to server thing. Battery optimization was off and notifications work. The only issue I have is that now I constantly have a "Tutanota notification service" notification on lockscreen and Tutanota icon in statusbar and can't get rid of them.

**Comment by jgora** [comment] 2018-09-19 07:04
@letkan This morning I have change service notification priority to min in my fork.
If you build app again, the icon is only visible if you expand the notification area.
Now, I'm testing the behaivor of activity on back pressed. Replacing moveTaskToBack() with finish() seems to help on battery consuption.

**Comment by charlag** [comment] 2018-09-20 06:27
@jgora and, btw, `moveTaskToBack()` is a good idea for exploring why we consume so much in background (WS should be stopped after some time). It may be that we hurt battery more by foreground than by notifications.

**Comment by jgora** [comment] 2018-09-20 06:48
Acording to my tests, replacing moveTaskToBack () with finish () improves Tutanota battery consuption.

@charlag Oreo makes mandatory the service's notification icon. If you don't like it, use a JobService but release its wakelock or never will be battery friendly.
I doubt if without a Service and dispite having battery optimization off, android could kill Tutonate on low memory conditions or when activity is removed from recent task.

**Comment by charlag** [comment] 2018-09-26 12:29
Hi everyone!
Server issue with many WebSocket messages should be fixed now so if you could re-measure again, we would be very glad.
Thanks again!

**Comment by letkan** [comment] 2018-09-26 13:13
I will, thanks.

**Comment by letkan** [comment] 2018-10-08 15:01
@charlag, sorry I forgot to get back to you on this, all is good now.

**Comment by charlag** [comment] 2018-10-09 06:09
@letkan thanks a lot!

**Comment by charlag** [comment] 2018-11-15 15:16
In 3.40.3 proposed fixes were merged and we shouldn't use so much battery. Please report any anomalies.

**Closed by charlag** 2018-11-15 15:16 UTC
Labels: improvement

**Comment by acarv** [comment] 2020-01-25 18:49
It's just odd that nowadays every application designer assumes that his users want to be slaves of their telephones or mail...
What I would expect for an application, from such a good service as Tutanota is, is that it, at least, have an operation mode where the user can open the application (when he wants or is ready to be disturbed by e-mails), request his mail update and then close the application (without anything left lurking in the shadows) until he wants to check mail again.
I really do not find at all amusing that my phone interrupts me every time someone sends me an e-mail.
I have uninstalled the Tutanota app from my Android 5.1.1 Galaxy Note 4. And yes it drained my battery more than anything else I have in it.
Best Regards
André de Carvalho

**Comment by letkan** [comment] 2020-01-25 19:10
> It's just odd that nowadays every application designer assumes that his users want to be slaves of their telephones or mail...
> What I would expect for an application, from such a good service as Tutanota is, is that it, at least, have an operation mode where the user can open the application (when he wants or is ready to be disturbed by e-mails), request his mail update and then close the application (without anything left lurking in the shadows) until he wants to check mail again.

Post that as a feature request. Alternatively you can disable notifications for the app.

> I really do not find at all amusing that my phone interrupts me every time someone sends me an e-mail.
> I have uninstalled the Tutanota app from my Android 5.1.1 Galaxy Note 4. And yes it drained my battery more than anything else I have in it.

Haven't had battery issues with Tutanota in a long time, Android 9. Maybe it is something specific to your device/OS.

> Best Regards
> André de Carvalho
