### ISSUE TITLE
Auto login after cancelling signup

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2630] opened 2021-01-18 14:16 UTC
How to reproduce:
1. Store credentials for a login.
2. Select to signup for a new account.
3. Cancel the dialog
-> The view switches to the stored credentials and you are automatically logged in.
Expected: You are not logged in but stay in the credentials input view.

**Comment by johnbotris** [comment] 2021-01-18 16:57
this is a duplicate of #2549

**Closed by johnbotris** 2021-01-18 16:57 UTC
Labels: bug, good first issue
