### ISSUE TITLE
Uncaught BadRequestError: final aggregateName _ownerEncSessionKey is tried to be modified

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4951] opened 2023-01-09 10:08 UTC
**Bug in web app**

Some users (all clients) are getting 400 Bad Request when interacting with their mail. We're not quite sure when that happens exactly, but it looks like we're trying to set `_ownerEncSessionKey` twice.

This seems to happen when the read status is changed or when the replied status is changed.

```
Client: win32
Type: PREMIUM
Tutanota version: 3.106.5
Timestamp (UTC): Sun, 08 Jan 2023 22:23:17 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.106.5 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36
BadRequestError
Error message: 400: NLITkMX--F-9 | PUT /rest/tutanota/mail/M9yDoWj--7-2/NLHBoH2----9
Stacktrace:
BadRequestError: 400: NLITkMX--F-9 | PUT /rest/tutanota/mail/M9yDoWj--7-2/NLHBoH2----9
at cP (asset://app/common-min-ad5cd377.js:1:7485)
at l.onload (asset://app/worker.js:12:100956)
```

`final aggregateName _ownerEncSessionKey is tried to be modified - PUT /rest/tutanota/mail/M9yDoWj--7-2/NLHBoH2----9/`

> Viewing an unread message in a folder. The message displays correctly, though I am notified of this error. The message is not marking itself as read after viewing.

**Notes:**

* This happens with mail that's not in the inbox and with mail that's in the inbox.
* Sometimes happens right after opening a folder:
  > Ordner geöffnet
* several reports: 
  > An error occurred when sending

  these seem to be triggered in the Inbox. No Idea if it was an internal or external mail that was sent.
* something interesting:
  > Hi, there is a problem with the day and date of emails sitting in the box. It’s dated 1970. 
  
  > wrong date

  > Wrong date year 1970

  these seem to happen exclusively on ios. The mail that is referenced in the error report has a normal sent/received/moved date.

**Further Info:**
One user got back to us:

> Hi,
> 
> 
> these type of errors occur for me from time to time. The scenario is always the same:
> 
> 
> * I recieve new message.
> * The rule is applied and message is moved to designated folder in unread state.
> * I go to a folder and choose that unread message.
> * Error occurs.
> * I choose other message in folder (or in any other folder, doesn't matter).
> * The error-causing message becomes unread again.
> * Back to point three, and this scenario from that point repeats itself indefinitely.
> * I can't move, delete, mark as read that message.
> * The problem exist after application restart.
> * The problem is valid on desktop app (windows) and android app (f-droid build). I rarely use browser version and do not remember that it is also affected.
> 
> 
> Sometimes the solution is to go to another device, then read or delete that message.
> Sometimes that message exist in a "ghost" state in one of my devices (it was deleted , but it is still visible, i cannot delete it againt because it does not exist in fact).
> Most of the times the problem is resolved after app update (maybe cache is then wiped out?).

same user after querying the offline time range:
> I have set it to big random number when the feature was released, because i want to have all my e-mails cached locally. It is now at 1902 days.

Does this happen after we changed the cache cleanup around christmas?

**Comment by bedhub** [comment] 2023-01-16 10:23
Check if we still receive these errors after  3.108.xx has been released

**Comment by ganthern** [comment] 2023-01-19 12:08
we have a repro in the reports mailbox (the offending mail is in the BadRequestError folder):  

```
Client: linux
Type: PREMIUM
Tutanota version: 3.106.5
Timestamp (UTC): Thu, 19 Jan 2023 12:06:52 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.106.5 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36
BadRequestError
Error message: 400: NM8vAaS----9 | PUT /rest/tutanota/mail/NKxWKxk--7-9/NM8n0fs----9
Stacktrace:
BadRequestError: 400: NM8vAaS----9 | PUT /rest/tutanota/mail/NKxWKxk--7-9/NM8n0fs----9
at cP (asset://app/common-min-ad5cd377.js:1:7485)
at l.onload (asset://app/worker.js:12:100956)
```

**Comment by ganthern** [comment] 2023-02-07 12:18
This seems to have cleared up completely with 3.108.x and the mail that did this in the reports mailbox is also fine now, can be set read/unread and everything.

**Comment by charlag** [comment] 2023-02-09 10:38
It still comes up with 3.108.12

**Comment by charlag** [comment] 2023-02-10 09:23
Might be related to #4664

**Comment by charlag** [comment] 2023-02-20 13:09
Investigating one case of the ghost email it seems like the same email is in two folders, there were few update and move events but the latest move (to trash) was not (fully) processed. We don't see how it could happen so far.

**Comment by ganthern** [comment] 2023-03-08 08:48
A case in the browser:

> Not sure what happened. I was just clicking through and deleting emails.

Client: Browser
Type: PREMIUM
Tutanota version: 3.110.0
Timestamp (UTC): Mon, 06 Mar 2023 18:43:26 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
BadRequestError
Error message: 400: NPsE4Ex----9 | PUT /rest/tutanota/mail/NBERYmx--k-2/NPqbVGM----9
Stacktrace:
BadRequestError: 400: NPsE4Ex----9 | PUT /rest/tutanota/mail/NBERYmx--k-2/NPqbVGM----9
at cW (https://mail.tutanota.com/common-min-3277242d.js:1:7560)
at l.onload (https://mail.tutanota.com/worker.js:12:23203)

User Responded:
> I do typically have 2 tabs with Tutanota, one for emails, the other for the calendar.  This is the first time I've gotten this error.

Worker Log:
```
2023-03-06T16:17:43.685Z I "ws connect reconnect:",false,"state:","terminated"
2023-03-06T16:17:43.686Z I "initIndexer after log in"
2023-03-06T16:17:43.857Z I "ws open state:","automatic"
2023-03-06T16:17:43.858Z I "New leader status set:",false
2023-03-06T16:17:44.404Z I "{\"indexingTime\":0,\"storageTime\":0,\"preparingTime\":0,\"mailcount\":0,\"storedBytes\":0,\"encryptionTime\":0,\"writeRequests\":0,\"largestColumn\":0,\"words\":0,\"indexedBytes\":0,\"downloadingTime\":0}","total time: ",0
2023-03-06T16:17:45.598Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPp1nop----9"
2023-03-06T16:17:46.971Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPqbVPm----9"
2023-03-06T17:51:34.354Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPs2Bzv----9"
2023-03-06T17:51:34.367Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPs2CBV----9"
2023-03-06T17:58:55.375Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPs3sxM----9"
2023-03-06T18:08:56.451Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPs6AhH----9"
2023-03-06T18:09:00.676Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPs6BjJ----9"
2023-03-06T18:09:10.450Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPs6E70----9"
2023-03-06T18:09:12.393Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPs6EaL----9"
2023-03-06T18:10:27.885Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPs6Wzk----9"
2023-03-06T18:16:56.843Z I "ws close event:",{"isTrusted":true},"state:","automatic"
2023-03-06T18:16:56.844Z I "New leader status set:",false
2023-03-06T18:16:56.844Z I "ws tryReconnect closeIfOpen:",false,"enableAutomaticState:",false,"delay:",6000
2023-03-06T18:17:02.852Z I "ws reconnect socket.readyState: (CONNECTING=0, OPEN=1, CLOSING=2, CLOSED=3): 3","state:","automatic","closeIfOpen:",false,"enableAutomaticState:",false
2023-03-06T18:17:02.956Z I "ws connect reconnect:",true,"state:","automatic"
2023-03-06T18:17:03.498Z I "ws open state:","automatic"
2023-03-06T18:17:03.500Z I "New leader status set:",true
2023-03-06T18:20:55.310Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPs8uvP----9"
2023-03-06T18:20:55.337Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPs8v7S----9"
2023-03-06T18:35:43.887Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsCJ8y--7-9"
2023-03-06T18:35:46.425Z I "[RestClient]","failed request","GET","https://mail.tutanota.com/rest/sys/publickeyservice?_body=<redacted>",404,"",["accessToken","v","cv","Content-Type","Accept"],"[63 characters]"
2023-03-06T18:37:23.430Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsCg3H----9"
2023-03-06T18:37:26.142Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsCh46----9"
2023-03-06T18:37:42.849Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsClBQ----9"
2023-03-06T18:37:45.593Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsClrN----9"
2023-03-06T18:37:47.499Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsCmK4----9"
2023-03-06T18:37:48.060Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsCmQQ----9"
2023-03-06T18:38:53.415Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsD1Pf----9"
2023-03-06T18:43:04.698Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsDzKi----9"
2023-03-06T18:43:04.722Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsDzbj----9"
2023-03-06T18:43:08.513Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsE-gj----9"
2023-03-06T18:43:14.473Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsE18t----9"
2023-03-06T18:43:21.355Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsE2pg----9"
2023-03-06T18:43:26.220Z W "Abort transaction on updating group data: concurrent access","NBERYmv--N-2","NPsE40f----9"
2023-03-06T18:43:26.916Z I "[RestClient]","failed request","PUT","https://mail.tutanota.com/rest/tutanota/mail/NBERYmx--k-2/NPqbVGM----9",400,"",["accessToken","v","cv","Content-Type","Accept"],"[2111 characters]"
```

**Comment by charlag** [comment] 2023-03-14 13:27
It might be related to `SessionKeyNotFoundError` for Mail that is happening since the offline release.

After checking with @armhub we've discovered that the mail has the `_finalEncrypted` fields which means it was already successfully decrypted **but** it has no `_ownerEncSessionKey` set. It is unclear yet how it happens but it seems like we are saving an entity to the cache which doesn't have `_ownerEncSessionKey`. This should not happen.

**Comment by charlag** [comment] 2023-03-14 16:47
After looking closely and for a long time at `CryptoFacade` I think these are the cases and how we handle them:

1. If the key is in the cache we **don't** write it to the instance
2. If it is resolved via `.bucketKey` aggregate it will *invoke server update* with a **delay**
3. If it's there, it's there
4. It is' Symmetric permission, we **don't** write it to the instance
5. If it's External bucket, we **don't** write it **nor** update it on the instance
6. If it's Public bucket, we **only** write and update it if we are the **leader** client

In most of these cases (except for 3.) we might end with a *decrypted* instance *without* `_ownerEncSessionKey`, even if temporarily (until the update with the session key comes in). As the key should be the same for all clients I don't see a problem with always setting it on the instance.

**Comment by bedhub** [comment] 2023-03-15 08:24
It could work with the old permission system, we tried this approach first while implementing the new permission system (BucketKey), but this was problematic at the end. 
With the new permission system we must resolve the session key always with the bucket key as long as all the ownerEncSession keys (including attachments) have been updated on the server
and made their roundtrip to the client. Writing these temporary ownerEncSession keys on the instance (Mail) might lead to a situation that we cannot resolve the session key for an attachment in the
new permission system.

So i think we should find another solution.

I assume that we receive this error now because the client is doing a put request with ownerEncSessionKey=null while the state  on the server is already not null.

To solve this we could either 

a) Implement partial update (so put request do not always include the full instance) or
b) Ignore updates of the ownerEncSessionKey from the client in a regular put request. 

I am in favor of option b for now. As for both permission systems (old and new) We have special requests to update the ownerEncSession key. We should just rely on them and ingore setting
this field for regular put requests.

**Comment by charlag** [comment] 2023-03-15 09:21
> Writing these temporary ownerEncSession keys on the instance (Mail) might lead to a situation that we cannot resolve the session key for an attachment in the
new permission system.

I am not sure why this is is the case yet. I would be in favor of keeping the key on the instance once we resolve it because there still might be a situation where we will try to resolve the key again and if we can avoid it, we should.

**Comment by vaf-hub** [comment] 2023-03-17 11:32
> > Writing these temporary ownerEncSession keys on the instance (Mail) might lead to a situation that we cannot resolve the session key for an attachment in the
> > new permission system.
> 
> I am not sure why this is is the case yet. I would be in favor of keeping the key on the instance once we resolve it because there still might be a situation where we will try to resolve the key again and if we can avoid it, we should.

It is the case because the `bucketKey` on the mail is used to get the session keys for attached files and the `MailDetailsBlob` instances. When decrypting the "leading" mail instance using the `bucketKey`, we store the session keys in the session key cache and then use it later when we need to decrypt on the associated instances.

I am in favor of option B. Just not making requests fail, based on whether they have an `ownerEncSessionKey" set, seems to be a rather simple yet reasonable fix. We could even write it to the mail if it is in request. We would just need to make sure, that we resolve the session key of mail instances using the `bucketKey` even if there is an `ownerEncSessionKey`. This should already be the case. The `bucketKey` will be remove from the mail once all session keys it can resolve were written to the associated instances.

**Comment by charlag** [comment] 2023-03-17 13:24
> When decrypting the "leading" mail instance using the `bucketKey`, we store the session keys in the session key cache and then use it later when we need to decrypt on the associated instances.

So the problematic situation is where we download the email only, write it to offline with `ownerEncSessionKey` but not download e.g. attachments and then when we later (e.g. after restart) want to download attachments we wouldn't have it in the cache, do I understand correctly?

**Comment by vaf-hub** [comment] 2023-03-20 08:48
> 

I think the problem will only occur if we do not call `resolveSessionKey` in the case that the mail is stored in the offline cache with an `ownerEncSessionKey`. I am not sure if we do that. If we always call `resolveSessionKey` even for such cases we should not have a problem. Right now it is anyway only possible to get a reference to an associated instance (`MailDetailsBlob` or `File`) if we have the mail. This is the main reason why we thought it is fine to make decryption of those instances dependent on the mail. Also, in the leader client we try to write all `ownerEncSessionKey`s when we decrypt a mail using the `bucketKey`, i.e. even for attached files that are not downloaded yet. We do that without downloading the `File` instances:

https://github.com/tutao/tutanota/blob/f6b0edc4c4cad4fb111067f56ac5343579ec6310/src/api/worker/crypto/CryptoFacade.ts#L321-L322

I guess the fact that the PUT request fails for these mails because of a missing `ownerEncSessionKey` already tells us that the request to update the `ownerEncSessionKey`s failed or was never sent because we are not the leader client.

**Comment by charlag** [comment] 2023-03-20 09:19
I think this is how it happens:
 - we resolve session key but not write it to the object (maybe we are not the leader)
 - we return from `resolveSessionKey()`
 - we put the instance into the cache
 - we try to update the instance before getting an entity update with `ownerEncSessionKey` written to the instance

https://github.com/tutao/tutanota/blob/f6b0edc4c4cad4fb111067f56ac5343579ec6310/src/api/worker/crypto/CryptoFacade.ts#L562-L579

**Comment by charlag** [comment] 2023-03-20 09:57
Just saw multiple messages in the logs where leader client is explicitly `false` right before the failing update

**Comment by charlag** [comment] 2023-03-21 10:21
I just had this case in support and I know how this error happens and possible other inconsistencies.

There were multiple entity updates for a mail, `CREATE, `UPDATE` and then move.

We've tried to process `UPDATE` and tried to download the updated mail, got 404 and skipped the update. Then we reached move operation and we just moved mail from one list to another, without re-downloading. From now on we will have outdated mail instance until another client updates it.

We probably should at least expel the instance from the cache when we get 404 for it and should generally consider what happens with these timing issues.

**Comment by vaf-hub** [comment] 2023-03-22 08:03
> I just had this case in support and I know how this error happens and possible other inconsistencies.
> 
> There were multiple entity updates for a mail, `CREATE, `UPDATE` and then move.
> 
> We've tried to process `UPDATE` and tried to download the updated mail, got 404 and skipped the update. Then we reached move operation and we just moved mail from one list to another, without re-downloading. From now on we will have outdated mail instance until another client updates it.
> 
> We probably should at least expel the instance from the cache when we get 404 for it and should generally consider what happens with these timing issues.

Just to be clear, this cannot be related to the new session key resolution with `bucketKeys`, as we did not enable it yet, but when we do it might well be the case that the number of these errors increases as we would then automatically have updates for the ownerEncSessionKey and move operations if there are inbox rules.

I think we should do both:

1. On the server-side handle PUT requests even if the ownerEncSessionKey is not set (just keep the one that is set in the database). This should decrease number of errors. I am not sure if we need to make more exceptions (read, phishing flags...)
2. Delete the instance from the cache if an entity event update leads to a failed request. This makes it at least possible to recover from the broken state.

**Comment by charlag** [comment] 2023-03-22 15:14
Related: Why do we even need entity updates for the updated session key?

Either we already downloaded the instance without the key and then we are in the process of resolving it or we already downloaded it with a key. All clients should independently arrive on the same `ownerEncSessionKey` or am I wrong?

**Comment by ganthern** [comment] 2023-04-12 14:53
I'm still getting some reports about this

**Comment by charlag** [comment] 2023-05-15 08:22
Two things I've noticed in reports:
 - `Abort transaction on updating group data: concurrent access` is quite often printed before this error happens, even in android app (!)
 - quite often WS connection is unstable before this happens

**Comment by bedhub** [comment] 2023-06-21 07:59
I think this error occurs because we allow updating the ownerEncSessionKey with a regular PUT request and we don't have the most recent version of the entity on the client. I assume that we are sending an entity with ownerEncSessionKey set to null together with the PUT request although the ownerEncSessionKey has already been set on the entity.

I am thinking of an UPDATE operation on a newly received mail which is done before we processed the UPDATE event of setting the ownerEncSessionKey . Such fast UPDATE might be triggered by inbox rule processing although i was not able to reproduce this case.

I was able to reproduce the error by setting ownerEncSessionKey to null for an update request using browser dev tools. 

I made a fix on the server to ignore changes of the ownerEncSessionKey with regular PUT request, so let's observe if this error still occurs.

see tutadb repo merge_requests/408

**Closed by bedhub** 2023-06-21 07:59 UTC
Labels: bug, no-repro
