### ISSUE TITLE
All calendar inputs are moved one week earlier

### ISSUE THREAD

**Issue by Kaptajnhado** [tutao/tutanota#6822] opened 2024-04-04 06:25 UTC
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Yesterday all my calendar inputs got one week off original input. E.g. an event created April the 10th at 3pm is now shown at April the 3th at 3pm.

It seems systematically for all events.

**To Reproduce**
I can just open the app. 
Have tried to look for Tuta updates to fix the error. 
And no bugs either..

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Fairphone
 - OS: Latest Android

**Additional context**

**Comment by rezbyte** [comment] 2024-04-04 06:44
Hi @Kaptajnhado,
I am sorry to hear you are having issues with the calendar.

Thank you for reporting this problem. We are already aware of this issue and a fix is planned. Stay tuned for the coming update!

Duplicate of https://github.com/tutao/tutanota/issues/6734.

**Closed by rezbyte** 2024-04-04 06:44 UTC
Labels: bug
