### ISSUE TITLE
Going back from the first selected mail in search results moves you outside the search

### ISSUE THREAD

**Issue by europound** [tutao/tutanota#2879] opened 2021-03-27 11:44 UTC
Search string 
List of found string
Click on email
Press back
Search list lost
Have to Search for a string again

**Comment by charlag** [comment] 2021-03-29 07:50
Actually can't reproduce it anymore, I search, click on email, then it opens previous email

**Comment by vaf-hub** [comment] 2021-03-30 13:27
I cannot reproduce this either. @europound can you provide more details?

**Comment by jowlo** [comment] 2021-04-15 15:34
Also can't reproduce, after clicking into the search bar the text and list of results is still there.

Closing. Please reopen and provide more details if it is still an issue.

**Closed by jowlo** 2021-04-15 15:34 UTC
Labels: bug
