### ISSUE TITLE
Some links from calendar invite disappears

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2741] opened 2021-02-22 10:41 UTC
>When receiving calendar invites with Zoom links for instance, the link disappears on the accepted and saved invite.

Also update of event is not automatically applied, we should try that out.

**Comment by charlag** [comment] 2021-02-22 10:52
Another report:
> Like Ms Teams, Skype for Business or Zoom meeting links. It is removed.

**Comment by johnbotris** [comment] 2021-02-23 09:52
This needs more context and explanation. 

I've sent and also updated invitations from both Tutanota and Gmail with links in  the description, and the links aren't removed. However, in the invite from Gmail, it is rendered as normal text (not an <a>) so it's unclickable, is this  what the customer is referring to? It also seems like we aren't parsing description text with escaped commas properly
![Screenshot from 2021-02-23 10-46-08](https://user-images.githubusercontent.com/22109738/108826669-7d372700-75bc-11eb-9468-9b9d482785f5.png)

**Comment by charlag** [comment] 2021-02-24 08:35
>Mostly Outlook 

maybe broken links are indeed the issue

**Comment by meewgumi** [comment] 2021-03-09 04:06
@charlag @johnbotris Regarding the links "rendered as normal text" and "unclickable", I have found this to be bothersome when meeting URLs are in the "Location" field. Do you think this could be the original customer's complaint? The only way to open a URL is to Edit Event and copy text manually, which is not intuitive. Perhaps most people wouldn't think of clicking "Edit" as part of their normal workflow.

The way I see it there are two places a meeting URL could live:

1. Location field
2. Description field

Both of these appear in the Event modal in plain text. However, clicking within the modal closes it, which is not expected behavior. Expected behavior: clicking "x" or outside the modal closes it, and clicking within it allows the user to select text. Simply allowing the modal text to be selected might be a good enough fix for now.

Ideally, clicking a URL in the location field should open the URL as a hyperlink on all platforms. If you want to go with this, I suggest only allowing links to be clicked within the event modal (not in Day or Agenda View, as the entire rectangle should function to open the modal). But short of that, manually selecting text as proposed above could at least get the job done by making the funky "Edit" workflow obsolete, thereby removing a hurdle in the user's task flow.

As an aside: I have been using Tutanota calendar for several months, and although it is rough around the edges, I find that it functions well, and that's all I ask for. The Location field and URLs are the only things I see worthy of improving in the short term. The reason being that this particular issue could be seen as "more stressful" than any other in the customer's eyes, usually because it occurs when trying to join a meeting, which is a time sensitive workflow with high stakes if it's too hard to figure out.

**Comment by charlag** [comment] 2021-03-09 08:54
@meewgumi thatnks for the detailed description of the issue!
It might as well be that the link is "broken" like you mention. I also didn't expect the link to be in the Location field, perhaps we should try to make it a link if possible, at least with some regex.

It's also not intended that the popup closes if you click on it, I guess no one noticed yet. Description of the event should be rendered as HTML so I think there might be some problem with unescaping there rather than with presentation.

We will try to address these issues but of course contributions/test cases/examples are very welcome.

**Comment by meewgumi** [comment] 2021-03-10 01:32
@charlag I'm happy to help with test cases, examples, and research on this issue. Is Reddit still the best place to look? I also saw Uservoices but that link wasn't working when I checked.

I'm personally invested in this because it's the biggest feature I see missing from the current Calendar product, not just for auto-generated invites, but for setting up my own meetings with URLs.  If we agree on this, I'll start documenting all the places links can show up on different platforms and examples of calendar invites from other providers for your reference around this user goal: **As a Calendar user, I want to easily open links within events.**

Potential solutions:

1. Plain text URLs should be clickable (new feature to meet core expectations)
3. Event popup should stay open when clicking/tapping (bug)
4. Description HTML should capture links (bug, but I'd argue this is not critical)

For "Description HTML" above, I don't think this is worth spending time on fixing because I never knew until you mentioned it that the events could contain HTML. The interface looks like a rich text editor to me, and seems almost entirely unnecessary. For a customer likely accustomed to Google Calendar and teammates sending out invites from MS Teams, Zoom, etc.; rich text editing is not a must-have feature. The single most important feature is that the meeting link works. This is why I labeled it as a core expectation above. If this bug could be limited only to fixing `<a href` parsing to the event description, I'd say that would be enough to meet core expectations. But without combining it with 1 and 2, it's an incomplete fix.

Unfortunately, I'm unable to contribute any actual code—I looked at the source code and it all went over my head. But I'm very good at product & ux design, organizing issues, finding insights from customer feedback, simplifying complex features to the bare minimum, and QA testing. I'd be happy to contribute this skillset to the community, and I hope it will be helpful.

Thanks!

**Comment by charlag** [comment] 2021-03-10 09:53
Thanks a lot for your offer. We don't really need coding help here as much as we need examples of ics files which have broken description/location fields.

**Comment by meewgumi** [comment] 2021-03-11 05:28
@charlag Ok I can collect .ics files from all the major services! Is the email body important too? I thought .ics files weren't being imported to the calendar?

**Comment by meewgumi** [comment] 2021-03-19 01:32
Hi, I researched the "disappearing link" problem with Zoom, MS Teams, and Webex [[source 1](https://www.reddit.com/r/tutanota/comments/jx0m7o/link_to_original_email_in_calendar_entries/)] [[source 2](https://www.reddit.com/r/tutanota/comments/k592i5/microsoft_teams_meeting_link_broken_in_a_calendar/)], along with Skype as referenced earlier in this thread.

It looks like most issues would be fixed by https://github.com/tutao/tutanota/pull/2826, so long as URLs in the description field and location field are clickable.

| Meeting Platform  | Host's Calendar | Location Field | Description Field
| ------------- | ------------- | ------------- | ------------- |
| Zoom  | Google Calendar  | https:// | https://
| Zoom  | [Zoom for Gsuite](https://gsuite.google.com/marketplace/app/zoom_for_gsuite/364750910244)<sup>1</sup>  | - | https://
| Zoom  | Yahoo Calendar  | https:// | https://
| Zoom  | Outlook | https:// | https://
| MS Teams  | Google Calendar  | https:// | Hyperlink - URL OK
| MS Teams  | Outlook | - | Hyperlink - URL missing<sup>2</sup>
| Skype  | Outlook | - | Hyperlink - URL missing<sup>2</sup>
| Google Meet  |  Google Calendar | https:// | https://
| Webex | Webex<sup>3</sup> | https:// | https://

<sup>1</sup> Zoom for Gsuite uses a field called "Joining Info" instead of "Location". It contains server.zoom.url, Meeting ID, and passcode in plain text. Note that https:// is missing from the link.
<sup>2</sup> Hyperlink is working in Tutanota email, but accepting calendar invite strips the URL from the event.
<sup>3</sup> Webex has a [known issue](https://help.webex.com/en-us/WBX9000023477/Join-Meeting-Link-is-Missing-from-Email-Invitation-for-Webex-Meetings) with disappearing links from the Outlook integration.

The biggest problem is Outlook Calendar and disappearing hyperlinks from MS Teams/Skype. Tutanota recognizes these links in emails, but not in the Calendar. It appears Google Calendar has solved for this problem, since MS Teams links are recognized when I send an invite to Tutanota from Google.

Hope this helps!

**Comment by meewgumi** [comment] 2021-03-19 01:38
Oh yeah, here is the DESCRIPTION field from the Skype to Outlook ics:

`DESCRIPTION;LANGUAGE=en-US:skype<http://skype.com>\n\nhttp://skype.com\n\n.
 ..........................................................................
 ..............................................................\nJoin onlin
 e meeting<https://join.skype.com/meeting>\n..........................
 ..........................................................................
 .....................................\n`

There is also an extra Microsoft-specific field:
`X-MICROSOFT-ONLINEMEETINGEXTERNALLINK:https://join.skype.com/meeting`

**Comment by bedhub** [comment] 2021-03-19 07:03
Thanks for testing these cases. Do you still have the original ics files for these cases and may i ask you to upload them here so we can use them as a reference?

**Comment by meewgumi** [comment] 2021-03-20 06:46
@bedhub I can upload anonymized ics files where I replace all personal links, does that work?

**Comment by bedhub** [comment] 2021-03-22 07:27
Yes, that would be enough.

**Comment by meewgumi** [comment] 2021-03-23 00:00
@bedhub Here are the two ics files in a [Gist](https://gist.github.com/meewgumi/c87ef5ca23ab376e211f63b0caeb881e)

**Comment by charlag** [comment] 2021-03-23 08:18
@meewgumi thanks a lot, it will help us a great deal!

**Comment by mandm-pt** [comment] 2021-03-30 08:11
I just encounter this issue as well. I think there's already enough details, but nonetheless will leave the ICS I received with some fields changed to not reveal sensitive information:

```
BEGIN:VCALENDAR
PRODID:-//Tutao GmbH//Tutanota 3.82.12//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REPLY
BEGIN:VEVENT
DTSTART:20210330T110000Z
DTEND:20210330T120000Z
DTSTAMP:20210325T163746Z
UID:id
SEQUENCE:0
SUMMARY:something
DESCRIPTION:\n________________________________________________________________________________\nMicrosoft Teams meeting\nJoin on your computer or mobile app\nClick here to join the meeting<https://teams.microsoft.com/l/meetup-join/19%3ameeting_something%40thread.v2/0?context=something>\nLearn More<https://aka.ms/JoinTeamsMeeting> | Meeting options<https://teams.microsoft.com/meetingOptions/?organizerId=id&tenantId=id&threadId=id&messageId=0&language=en-US>\n________________________________________________________________________________\n
ORGANIZER;EMAIL=mail:mailto:mail
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE;CN=name;EMAIL=mail:mailto:mail
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=name;EMAIL=mail:mailto:mail
END:VEVENT
END:VCALENDAR
```

The way I worked around this was going to **Sent** box, **find the reply** message and then click on the ***.ics attachment**

**Comment by charlag** [comment] 2021-03-30 08:13
@mandm-pt does it look like a broken link or how does description look like?
Thanks a lot for more info, hope we can find time soon to fix it

**Comment by mandm-pt** [comment] 2021-03-30 08:15
@charlag The link is fine, I copied and pasted on browser and it asks me to open the teams app. Might look like a broken link because I replaced the ids just to post the message here on git

**Comment by jowlo** [comment] 2021-04-01 09:41
* After importing the `teams-outlook.ics` provided by @meewgumi the link in the description is completely removed completely. Is that intended?
![Screenshot from 2021-04-01 11-29-20](https://user-images.githubusercontent.com/6842104/113274363-e86fc980-92dd-11eb-95f1-351c0b558cf2.png)

 * Also links in location are clickable but overflow the modal.
 ![Screenshot from 2021-04-01 11-33-23](https://user-images.githubusercontent.com/6842104/113274603-2bca3800-92de-11eb-8414-99f594bb7e78.png)

 * For some reason the protocol is stripped from the links parsing in the description. Clicking the link still works.
![Screenshot from 2021-04-01 11-34-51](https://user-images.githubusercontent.com/6842104/113274780-5caa6d00-92de-11eb-8976-c25df2531280.png)
![Screenshot from 2021-04-01 11-35-53](https://user-images.githubusercontent.com/6842104/113274866-70ee6a00-92de-11eb-8066-5091ddb1c875.png)

 * Event bubble is closed if click release is outside of the bubble. Quite inconvenient if you need to go outside to scroll the description field
 https://user-images.githubusercontent.com/6842104/113275397-0be74400-92df-11eb-8780-e7c16117fb0f.mp4

**Comment by johnbotris** [comment] 2021-04-01 10:26
ok so truth be told I hadn't seen these test samples since the changes I initially made. after looking at it again, the links are being sanitized out by the html sanitizer, presumably because they're all wrapped in angle braces. Is the solution to just render all descriptions as plaintext, or maybe just for calendar events that were imported from .ics?

**Comment by charlag** [comment] 2021-04-01 11:29
@johnbotris I'm not sure what to do there tbh. We can try to scan for some HTML tags to determine whether it's HTML because there's no indication otherwise I think.

**Comment by charlag** [comment] 2021-04-01 14:57
We talked with @johnbotris about it and we should discuss how to proceed. The right thing to do would be to also only do plaintext but we need some server to migrate gracefully.

**Comment by charlag** [comment] 2021-04-06 07:04
I did some more experiments and I think I wouldn't change it to plaintext now:
- Google edits HTML and sends HTML (except for the meeting link which is not marked)
- Outlok edits HTML **but** sends plaintext (including their special link formatting with triangle brackets)

I think we should check whether the only thing inside angled brackets is a URL and then removed brackets and replace it with a proper link.

**Closed** 2021-04-06 08:59 UTC
Labels: bug
