### ISSUE TITLE
Duplicate attachments when draft is saved

### ISSUE THREAD

**Issue by obryan5598** [tutao/tutanota#3365] opened 2021-08-10 08:36 UTC
Hi all, here follows the issue report I have experienced yesterday.

**What:**
Anytime an email containing an attachment is saved as a draft, when reopening it the number of attachments duplicates.

**Where:**
Tutanota Desktop for Mac OS Version 3.85.6 (3.85.6.1623)

**Steps to reproduce:**
1. Open Tutanota Desktop for Mac OS
2. Write a new email and attach one file
3. Click on top-left corner button "Close" (Draft is then automatically saved)
4. Re-open the drafted email to edit it (may click on the "pencil" icon)
5. Check attachments that are now two: the original only-one file is thus duplicated
6. Repeat steps 3-5, which show [attachments = attachments*2] for each iteration

Feel free to reach out for any question or concern.
Thank you very much guys: you are doing an awesome job!

**Comment by johnbotris** [comment] 2021-08-10 08:44
thanks for the report, this is a duplicate of #3310, this has been fixed with version [3.85.10](https://github.com/tutao/tutanota/releases/tag/tutanota-release-3.85.10)

**Closed** 2021-08-10 08:44 UTC

**Comment by obryan5598** [comment] 2021-08-10 09:15
Hi @johnbotris sorry for duplicating this issue: I have been looking in the open issues but not in the closed ones.
Thank you very much!
