### ISSUE TITLE
Incorrect date display

### ISSUE THREAD

**Issue by EmirLogas** [tutao/tutanota#4088] opened 2022-04-28 21:15 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in Calendar**

**Describe the bug**
Real date is 29.04.2022 but in my calendar saying today is 28.04.2022. Is this problem caused by the time zone? how can I solve it?

**Screenshots**
![Screenshot 2022-04-29 000632](https://user-images.githubusercontent.com/76751818/165846902-bc46830d-3408-4531-a61c-48b87d6068e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 99.0.1

**Comment by johnbotris** [comment] 2022-04-29 06:54
sounds like a duplicate of https://github.com/tutao/tutanota/issues/3338

**Closed by johnbotris** 2022-04-29 06:54 UTC
Labels: bug

**Comment by EmirLogas** [comment] 2022-04-29 08:22
That's exactly what the problem was caused by. Sorry for the repetition. Thanks for the reply. Tutanota <3
