### ISSUE TITLE
Problems with Gnome Web

### ISSUE THREAD

**Issue by musicsd** [tutao/tutanota#2090] opened 2020-06-03 09:42 UTC
When I enter information, it says: You are not connected to the Internet.

Browser: Gnome Web
Version: 3.32.1.2
Operating system: Debian Buster

![عکس‌صفحه از 2020-06-03 14-12-25](https://user-images.githubusercontent.com/66354118/83621707-450e3500-a5a4-11ea-8d94-b9acf20965e0.png)

**Comment by charlag** [comment] 2020-06-03 10:39
I couldn't connect, it says certificate is expired but it expires in 2021?

![Screenshot from 2020-06-03 12-39-03](https://user-images.githubusercontent.com/3099142/83627455-3ec58c00-a597-11ea-8d51-1278320d8fb8.png)

**Comment by charlag** [comment] 2020-06-03 11:54
It's something with wildcard certificate it seems, duplicate of #2089

**Closed by charlag** 2020-06-03 11:54 UTC
Labels: bug
