### ISSUE TITLE
The x button to delete the search menu does not work

### ISSUE THREAD

**Issue by Mijenko** [tutao/tutanota#6685] opened 2024-03-11 05:16 UTC
**Describe the bug**
The x button to delete the search menu does not clear the text when clicked

**To Reproduce**
1. Type a search into the bar, either in Contacts or Emails 
2. Attempt to click the X button to erase the recent search 
3. It does not delete the search 

**Expected behavior**
The X button should clear the search bar and return to the main page of Emails or Contacts without the search results filtered 

**Screenshots**
![Tutanota email issue](https://github.com/tutao/tutanota/assets/162950756/d0155c55-5407-4450-ad09-b5ec5c063bfd)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Version	10.0.19045 Build 19045

**Comment by rezbyte** [comment] 2024-03-11 06:51
Hi @Mijenko,
I am sorry to hear you are having issues with the search bar.

Thank you for reporting this problem. We are already aware of this issue and a fix is planned. Stay tuned for the coming updates!

Duplicate of #6604.

**Closed by rezbyte** 2024-03-11 06:51 UTC
Labels: bug, desktop
