### ISSUE TITLE
MailBody is flashing when mail is updated

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4309] opened 2022-06-27 08:47 UTC
First Case:
1. Have unread email in mailbox
2. Open it with 2 or 3 column layout
3. See that email is marked as read
4. See that mail body flashes when update arrives

Second Case (arguably the worse one):
1. open a mail in the two- or three-column layout
2. click on another one
3. see that the old mailbody overstays its welcome and gets removed too late

**Comment by paw-hub** [comment] 2022-08-04 08:58
So from our investigation, we found a number of issues that cause this.

For a start, marking an email as read/unread also causes the contrast fix to change state to false temporarily. On a dark theme, this causes the entire email body to flash from white to black and then back to white.

Then there is content in the body moving to the horizontal center. This appears to be due to the progress icon styling being used for a couple frames.

We found that if you prevent the MailViewerViewModel from being recreated on update, this prevents the above two issues, but then updating drafts on a separate instance of the client no longer updates the contents of the selected mail. However it does not prevent the old mail body from being replaced late, and these issues still occur with switching emails.

For the contrast fix, we should probably not switch from using a white background to the theme's background when changing emails until we have determined that the email we changed to/updated to requires different styling.

**Comment by johnbotris** [comment] 2022-08-15 09:00
# Testing notes

Open a mail, mark at as unread from the action bar:
- [ ] The mail body does not flicker

Open a mail, and then open another that hasn't been loaded yet (you can thottle the network connection to make it more obvious)
- [ ] The loading icon shows (rather than the previous mailbody bouncing around in the mailviewer)

Set dark mode, open a mail that triggers the contrast fix (renders in light mode), then open another mail that also triggers the fix
- [ ] The body background color doesn't switch back to black before switching to white again

## Regression tests
- [ ] the switching between mails always correctly updates the state of the viewer (mail body, subject, recipients, sender, headers)
- [ ] external image loading  preferences are correctly checked when switching between mails (always show, never show, ask)
- [ ] drafts are updated in the viewer when changes are made
- [ ] replying/forwarding references the corret mail after switching in the mail viewer

**Closed** 2022-08-19 08:22 UTC
Labels: bug, done
