### ISSUE TITLE
Not showing all attachments

### ISSUE THREAD

**Issue by nk3d** [tutao/tutanota#2670] opened 2021-02-02 11:22 UTC
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in web app**
Also on mobile and desktop app
**Describe the bug**
Not Showing all attachments on version 3.80.5 

**To Reproduce**
Just sent an email with more than 2-3 attachment files. on mobile you only see 2 no more. on web and desktop you see only one row with 4 files the others are not visible as icons.

**Expected behavior**

**Screenshots**

<a href="https://ibb.co/cxv9qjZ"><img src="https://i.ibb.co/cxv9qjZ/2021-01-27-14-24-05-Window.png" alt="2021-01-27-14-24-05-Window" border="0"></a>

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by charlag** [comment] 2021-02-02 11:54
Duplicate of #2651

**Closed by charlag** 2021-02-02 11:54 UTC
Labels: bug
