### ISSUE TITLE
Responsive ui

### ISSUE THREAD

**Issue by unknowtech** [tutao/tutanota#1129] opened 2019-02-18 17:29 UTC
![img_20190218_184257_956_1](https://user-images.githubusercontent.com/41585567/52968433-76fa8880-33ad-11e9-97a1-3840e52042d7.jpg)
![img_20190218_184301_416_1](https://user-images.githubusercontent.com/41585567/52968441-7d890000-33ad-11e9-98f4-32f3f3e8adf9.jpg)

Hi guys, I hope you're well

I've a suggestion for the app

An interesting and useful feature would be to make the emails (images and other content) adapted to the mobile make them boostrap / responsive as does gmail, or others (aquamail bluemail) 
 
having to scroll from left to right is annoying. 
 
Thank you

**Comment by charlag** [comment] 2019-02-19 07:17
Hey
we don't accept feature requests here and it's tracked as #370 anyway.
Most of the time *that's how email is formatted*. It's possible to make them responsive. Maybe we need to check if we strip some useful styling during sanitizing.
I've made some prototypes with zooming in the past but they worked horribly. It's not reluctance why we didn't implement this yet, it's just hard to get right. I'll try to revisit it soon.

duplicate of #370

**Closed by charlag** 2019-02-19 07:17 UTC
