### ISSUE TITLE
Calendar editor time picker keeps reopening itself on Web App and Desktop

### ISSUE THREAD

**Issue by andrehgdias** [tutao/tutanota#8185] opened 2024-12-23 10:36 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app and Desktop client**

**Describe the bug**
When creating or editing an event, the drop-down from the time section traps the focus and keeps reopening itself even after selecting a value with the mouse or keyboard.

**To Reproduce**
1. Open event editor
2. Try to change the event start time choosing an option form the drop-drown 
3. See the value updating and the drop-down reopening trapping you on this interaction

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3 Cinnamon
 - Browser Librewolf
 - Version v259.241220.0

**Comment by tsaoi** [comment] 2024-12-23 11:51
Exactly the same issue on MacOS Big Sur
v259.241220.0 - darwin

Client: darwin
Tutanota version: 259.241220.0
Macintosh; Intel Mac OS X 10_15_7) tutanota-desktop/259.241220.0

**Comment by charlag** [comment] 2024-12-23 13:15
Hi, thank you for the report, we can reproduce it and will try to fix it soon

**Comment by charlag** [comment] 2024-12-23 13:36
This is happening because of #8164

We will have to roll it back and reimplement time picker without using modal

**Comment by charlag** [comment] 2024-12-23 13:58
Fixed by d94873bc12a4d75ab64d6129e04d8c2f8ac18986

**Closed by charlag** 2024-12-23 13:58 UTC
Labels: bug, topic: calendar
