### ISSUE TITLE
Unpacked Linux build

### ISSUE THREAD

**Issue by yochananmarqos** [tutao/tutanota#1857] opened 2020-02-28 23:03 UTC
The build instructions are only for the web and Android app. I poked around and came up with the following which launched the client, but it didn't create a `/dist/linux-unpacked` folder at all.

```
npm install
node dist release
node make -d
```

Manjaro Linux
GNOME 3.34.4

**Comment by ganthern** [comment] 2020-03-03 10:03
That command builds the web app and the desktop source files into a folder that then can get executed directly by an installed version of electron, it is meant to be used for fast iteration when developing. 
The script that actually builds the app is `dist.js`, but it currently has no option to get the unpacked app, which may be a sensible addition.

If you want a `linux-unpacked` directory right now, you'll have to replace the line
```
"target": "AppImage",
```
with
```
"target": "dir",
```
in the linux target array in `buildSrc/electron-package-json-template.js`, 
comment out
```
fs.removeAsync(path.join(distDir, '/installers/')),
```
in `buildSrc/DesktopBuilder.js` and run `node dist -l prod`.
The files you seek will be in `build/dist/installers/linux-unpacked`.

**Comment by yochananmarqos** [comment] 2020-03-03 19:23
Got it working, thanks!

**Comment by yochananmarqos** [comment] 2020-03-04 15:45
With my built package, I receive a desktop notification: _Failed to handle push message_. This does not happen with the `tutanota-desktop-bin` AUR package or the AppImage.

```
[2020-03-04T15:42:00.075Z] the monkey has been patched
[2020-03-04T15:42:00.116Z] _connectedSseInfo {
  identifier: '4Mvzb3TRgspNM80xBbfowdhwKJii1VZQuVAi97PFSRQ=',
  sseOrigin: 'https://mail.tutanota.com',
  userIds: [ 'LwemdXD----2' ]
}
[2020-03-04T15:42:00.118Z] scheduling to reconnect sse in 1 seconds
[2020-03-04T15:42:00.119Z] argv:  [ '/opt/tutanota-desktop/tutanota-desktop' ]
[2020-03-04T15:42:00.119Z] version:   1583252801766.0.0
[2020-03-04T15:42:00.149Z] startFile:  file:///opt/tutanota-desktop/resources/app.asar/desktop.html
[2020-03-04T15:42:00.289Z] default mailto handler: false
[2020-03-04T15:42:00.290Z] alarm storage initialized
[2020-03-04T15:42:01.119Z] { lastMissedNotificationCheckTime: 1583247104479 }
[2020-03-04T15:42:01.120Z] scheduling to reconnect sse in 79 seconds
[2020-03-04T15:42:01.122Z] starting sse connection, identifier 4Mv userIds [ 'LwemdXD----2' ]
[2020-03-04T15:42:01.347Z] Webapp ready
[2020-03-04T15:42:01.347Z] checking for /home/yochanan/.local/share/applications/tutanota-desktop.desktop ...
[2020-03-04T15:42:01.348Z] /home/yochanan/.local/share/applications/tutanota-desktop.desktop does not exist, checking for permission to ask for permission...
[2020-03-04T15:42:02.004Z] established SSE connection
[2020-03-04T15:42:02.006Z] received new timeout: heartbeatTimeout:240
[2020-03-04T15:42:02.006Z] scheduling to reconnect sse in 288 seconds
[2020-03-04T15:42:02.006Z] sse heartbeat
[2020-03-04T15:42:02.006Z] scheduling to reconnect sse in 288 seconds
[2020-03-04T15:42:02.031Z] sse heartbeat
[2020-03-04T15:42:02.031Z] scheduling to reconnect sse in 288 seconds
[2020-03-04T15:42:02.031Z] downloading missed notification
[2020-03-04T15:42:02.703Z] failed to handle push message: error during missedNotification retrieval, got 400
[2020-03-04T15:42:04.379Z] storing push identifier 4Mv
[2020-03-04T15:42:04.382Z] initPushNotifications
[2020-03-04T15:42:04.382Z] { lastMissedNotificationCheckTime: 1583247104479 }
[2020-03-04T15:42:04.382Z] scheduling to reconnect sse in 121 seconds
[2020-03-04T15:42:04.383Z] starting sse connection, identifier 4Mv userIds [ 'LwemdXD----2' ]
[2020-03-04T15:42:04.387Z] sse response closed
[2020-03-04T15:42:04.387Z] scheduling to reconnect sse in 60 seconds
[2020-03-04T15:42:04.388Z] sse error: socket hang up
[2020-03-04T15:43:04.391Z] { lastMissedNotificationCheckTime: 1583247104479 }
[2020-03-04T15:43:04.392Z] scheduling to reconnect sse in 44 seconds
[2020-03-04T15:43:04.392Z] starting sse connection, identifier 4Mv userIds [ 'LwemdXD----2' ]
[2020-03-04T15:43:05.072Z] established SSE connection
[2020-03-04T15:43:05.073Z] received new timeout: heartbeatTimeout:240
[2020-03-04T15:43:05.073Z] scheduling to reconnect sse in 288 seconds
[2020-03-04T15:43:05.073Z] sse heartbeat
[2020-03-04T15:43:05.073Z] scheduling to reconnect sse in 288 seconds
[2020-03-04T15:43:05.075Z] sse heartbeat
[2020-03-04T15:43:05.075Z] scheduling to reconnect sse in 288 seconds
[2020-03-04T15:43:05.075Z] downloading missed notification
[2020-03-04T15:43:05.721Z] failed to handle push message: error during missedNotification retrieval, got 400
```

**Comment by ganthern** [comment] 2020-03-05 12:29
That actually looks like a bug that's unrelated to this issue, so if you'd like to open a new report, go ahead.

**Comment by yochananmarqos** [comment] 2020-04-15 14:53
I applied #1928 as a patch in my [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/commit/?h=tutanota-desktop&id=95771c0d0a62154a4ad26a59b0b882d0acbc05c7), it's working nicely.

**Comment by mpfau** [comment] 2020-05-07 09:03
Update works fine but an updated failed error is shown on each start of an up-to-date client. The following is printed on the terminal:
```
[2020-05-07T08:46:03.163Z] autoUpdater info:
 checking-for-update
[2020-05-07T08:46:03.164Z] checking for /home/map/.local/share/applications/tutanota-desktop-test.desktop ...
[2020-05-07T08:46:03.246Z] desktop file exists, checking version...
[2020-05-07T08:46:03.382Z] autoUpdater error:
 Auto Update Error 1, continuing polling:
This file could not be downloaded, or the latest version (from update server) does not have a valid semver version: "null"
[2020-05-07T08:46:03.386Z] autoUpdater error:
 Update check failed, This file could not be downloaded, or the latest version (from update server) does not have a valid semver version: "null"
```
This seems to be a problem with the electron autoUpdater (manifest for Linux: https://test.tutanota.com/desktop/latest-linux.yml)

**Closed** 2020-05-07 13:11 UTC
Labels: desktop, improvement, not-testable

**Comment by yochananmarqos** [comment] 2020-05-11 18:14
@ganthern 

Version 3.73.1 fails to build using:

```
	npm install --cache "$srcdir/npm-cache"
	node dist -l --custom-desktop-release --unpacked
```

[Build log](https://pastebin.com/nirGtQY3)

**Comment by ganthern** [comment] 2020-05-12 07:49
Hey @ajgraves @yochananmarqos ,

the problem is that our system.js is incompatible with the current node version. node LTS dubnium works (availale as nodejs-lts-dubnium in the arch community repo).

Upgrading node and the build system is in the pipeline, in the meantime I have updated BUILDING.md to reflect this requirement. Thank you for reporting this!

**Comment by yochananmarqos** [comment] 2020-05-12 15:38
@ganthern: I ended up [using `nvm`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tutanota-desktop#n22) so folks don't have to replace their existing `nodejs` install with `nodejs-lts-dubnium` just for one AUR package.

**Comment by ajgraves** [comment] 2020-05-12 17:25
> @ganthern: I ended up [using `nvm`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tutanota-desktop#n22) so folks don't have to replace their existing `nodejs` install with `nodejs-lts-dubnium` just for one AUR package.

This is a much better solution @yochananmarqos, I was preparing to push an update that forced `nodejs-lts-dubnium` but was thinking if there might be a better way. COMPLETELY forgot about nvm. Then noticed you pushed the update to the AUR and I wiped out what I came up with. Thanks!
