### ISSUE TITLE
Read Emails on other clients shows as unread on Android

### ISSUE THREAD

**Issue by eagerto-learn** [tutao/tutanota#7811] opened 2024-10-24 12:08 UTC
If I read an Email on Linux Desktop client, that Email still shows as unread on Android.

**Expected behavior**
Emails that have been read on a client should be recognized across all clients as read.

 - Device: Oneplus 9 Pro
 - OS: Lineage OS 21
 - Version 246.241002

**Comment by SkypLabs** [comment] 2024-11-26 16:59
It is possible that your problem is not a specific issue between Linux Desktop and Android, but something more generic. Since quite recently, when I read an email on Android (version 251.241112.0), there is a high chance it remains marked as unread. If I remember correctly, it also happened on the web client.

I will investigate more and try to be more specific about the behaviour I encountered.

**Comment by charlag** [comment] 2024-12-05 08:51
Hi, this indeed should have nothing to do with a specific client. May I ask if other changes apply properly between the clients?

**Comment by raffitz** [comment] 2024-12-29 17:48
Is this not a duplicate of #8041 ?

**Comment by hrb-hub** [comment] 2024-12-30 10:43
duplicate of #8041

**Closed by hrb-hub** 2024-12-30 10:43 UTC
Labels: bug
