### ISSUE TITLE
The keyboard shortcut list is repeated multiple times

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [tutao/tutanota#1762] opened 2020-01-20 21:40 UTC
**Describe the bug**
The keyboard shortcut list is repeated multiple times as you can see in the picture below

**Screenshots**
![Selection_004](https://user-images.githubusercontent.com/29783425/72759172-8ac1f680-3bdd-11ea-9aa3-94cca22bf1cf.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Desktop Environment: Cinnamon.
 - Version 3.66.7

**Comment by charlag** [comment] 2020-01-20 21:46
Duplicate of #1700

**Closed by charlag** 2020-01-20 21:46 UTC
Labels: bug, desktop
