### ISSUE TITLE
pricing.monthly_label and pricing.yearly_label are not changed to the newly chosen language, although have been translated

### ISSUE THREAD

**Issue by PhuNH** [tutao/tutanota#2029] opened 2020-05-03 14:49 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
The labels pricing.monthly_label and pricing.yearly_label stay in the language the app starts up with, although the app's language has been changed.

**To Reproduce**
1. Start the app in language A, for example, English. In the Subscription popup, the two labels are in language A, i.e. "Yearly" and "Monthly";
2. Change the app's language to another one, call it B. All parts of the app that have been translated to B are now shown in B;
3. Open Subscription popup;
4. Although the two labels are already translated to B, they are still shown in A, i.e. "Yearly" and "Monthly".

**Expected behavior**
The two labels if have been translated should be shown in the language the app is currently using.

**Screenshots**
https://imgur.com/RmHc0IJ

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Desktop Environment: KDE Plasma 5.17.5
 - Version: 3.72.0

**Additional context**
This occurs on both the desktop app and web app, but not on the mobile app.

**Comment by nokhub** [comment] 2022-11-18 09:03
seems to be fixed

**Comment by PhuNH** [comment] 2022-11-18 12:53
@nokhub I'm afraid it's not fixed, I can still reproduce by starting the desktop app in Vietnamese then changing the language to English, the two labels stay in Vietnamese
![Screenshot_20221118_135039](https://user-images.githubusercontent.com/1079742/202709666-6bc904fc-927a-4fdf-8549-5cae9ecaf9c5.jpg)

**Comment by nokhub** [comment] 2022-11-18 16:09
Thanks for your comment!
Yes you are right, I was able to reproduce it after all. But I'm glad to tell you that this is already fixed in another branch and therefore won't be a problem after one of the next releases :)

**Comment by nokhub** [comment] 2022-11-24 11:28
## Test notes
* [ ] login to some free account
* [ ] go to settings
* [ ] go to "Subscription"
* [ ] click on edit the current subscription
* [ ] check that "Yearly" and "Monthly" in the buy option box are displayed in the same language like the rest of the client is
* [ ] close the dialog
* [ ] go to "Appearance"
* [ ] change the language
* [ ] go to "Subscription" again
* [ ] click on edit the current subscription
* [ ] check that "Yearly" and "Monthly" in the buy option box are again displayed in the same language like the rest of the client is

![image](https://user-images.githubusercontent.com/115003415/203773370-974772c1-9ba3-41cb-9ec4-d823c48fbb8a.png)

**Closed** 2022-11-25 09:31 UTC
Labels: bug, desktop, done, ui
