### ISSUE TITLE
cypher error

### ISSUE THREAD

**Issue by europound** [tutao/tutanota#4569] opened 2022-09-10 21:26 UTC
![Screenshot_2022-09-11-00-24-38-36_b00ecfeaa23c51d9a5681227a7fea7bd](https://user-images.githubusercontent.com/47265511/189502300-4993e3dc-1e12-4ace-b77f-8edd9942dfc3.jpg)
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by charlag** [comment] 2022-09-12 07:02
Duplicate of #4560

**Closed by charlag** 2022-09-12 07:02 UTC
Labels: bug
