### ISSUE TITLE
Schedule messages to send after/at

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#593] opened 2018-09-08 16:48 UTC
Not sure if this is possible (read: super-easy) to do, but it would be great to have the ability to schedule a message in order to be sent in the future.

I think the tough part here is that you would need some "state" on the server (or the encrypted message itself) because clients can be offline by the scheduled time.

**Comment by charlag** [comment] 2019-10-04 14:58
duplicate of #448
@x80486 you opened both of them btw :sweat_smile:

**Closed by charlag** 2019-10-04 14:58 UTC
Labels: new feature
