### ISSUE TITLE
Send plain text email as is

### ISSUE THREAD

**Issue by chandradeepdey** [tutao/tutanota#6135] opened 2023-11-11 18:56 UTC
- [✅] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [✅] I've searched and did not find a similar issue.

**Describe the bug**
I sent a [mail](https://lore.kernel.org/all/NizcVHQ--3-9@chandradeepdey.com/) to the kernel mailing list, which expects a specific format. At first, the Tutanota client didn't even let me copy in tab characters. I worked around that by typing the Unicode code manually. It also stripped the starting spaces from the diff lines (I noticed this and added them back manually, but that didn't work) and added a bunch of blank lines at the end, turning the [patch](https://lkml.org/lkml/diff/2023/11/11/163/1) unparsable.

![image](https://github.com/tutao/tutanota/assets/21266577/86b7af41-32fa-43d7-b50d-299eea62041e)

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Desktop Environment, if applicable (on Linux): KDE Plasma
 - Version: 3.118.27

**Comment by charlag** [comment] 2023-11-13 10:31
duplicate of #1588

**Closed by charlag** 2023-11-13 10:31 UTC
Labels: bug, desktop
