### ISSUE TITLE
iOS app only shows 1 new email in the badge count even though there are more than 1 new emails.

### ISSUE THREAD

**Issue by killerb77** [tutao/tutanota#5806] opened 2023-08-27 21:12 UTC
- [ X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
After more than one email is receive the notification badge only shows 1 new email regardless how many more than 1 there are.

**To Reproduce**
1. Receive more than 1 new email.
2. Look at the badge count and it will still just show 1.

**Expected behavior**
It should show the actual number of new emails.

**Smartphone (please complete the following information):**
 - Device: [iphone 14 pro max]
 - OS: [e.g. iOS17 public beta 5]
 - Version [v3.117.0]

**Comment by vitoreiji** [comment] 2023-08-29 06:43
Duplicate of #1757

**Closed by vitoreiji** 2023-08-29 06:43 UTC
Labels: bug
