### ISSUE TITLE
File could not be attached with umlaut and crash

### ISSUE THREAD

**Issue by akaessens** [tutao/tutanota#2880] opened 2021-03-27 14:54 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
The Desktop application (v3.82.12) cannot attach files with umlauts (in this case german ü). The same file renamed is working.

**To Reproduce**
1. Go to 'new email'
2. click on the attachment button
3. open file with umlaut in filename
3. See error "file cannot be loaded"
4. click OK
5. Blank white screen

**Expected behavior**
Umlauts should work...

**Screenshots**
![image](https://user-images.githubusercontent.com/24660231/112724655-b1cc3480-8f14-11eb-9df6-d7d69ac6b0d6.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Desktop Environment: KDE Plasma
 - v3.82.12

**Additional context**
When using drag&drop the the white screen won't appear, only the error message

**Comment by charlag** [comment] 2021-03-29 07:47
Hi, cannot reproduce it here. Do you pick a file to attach it and that's enough? Or do you try to open it afterwards?

**Comment by akaessens** [comment] 2021-03-29 16:27
> Hi, cannot reproduce it here. Do you pick a file to attach it and that's enough? Or do you try to open it afterwards?

Yes, Just pick the file via KDE open dialog and that's enough. Alternatively drag&drop, then it will display error notification but not crash with white screen

**Comment by johnbotris** [comment] 2021-03-30 07:21
This doesn't seem to be a problem in Ubuntu. @akaessens could you please send your logs to support@tutao.de (Settings->About->Send Logs) and mention this issue? In the meantime I'll try to reproduce it in a VM

**Comment by akaessens** [comment] 2021-03-30 09:27
Hello @johnbotris, I'll send the log later this day.

I am using the AppImage binary from the website directly, without AUR makepkg wrapper. I wasn't aware it exists, is it maintained officially?

**Comment by johnbotris** [comment] 2021-03-31 07:39
@akaessens ah that's not ideal, then I'll keep trying to reproduce it for myself. Does this happen with any filetypes in particular? Also, the AUR package isn't officially managed.

**Comment by akaessens** [comment] 2021-03-31 07:43
@johnbotris thanks for the update.
This happened with pdf and text file, too.

**Comment by johnbotris** [comment] 2021-04-01 07:59
ah that looks like another problem, I've made an issue for that too #2896 

I can't reproduce this in a vm either unfortunately, could it be some sort of configuration issue? You could also send the logs from `~/.config/tutanota-desktop/logs`, but you'll have to shutdown the app completely (so quit from the taskbar icon) in order to make sure they get written to file

**Comment by akaessens** [comment] 2021-04-01 08:46
I created two logs: 
- open desktop app and close completely 
- open desttop app, new mail with attachment (then crash) then close completely 
The logs in `~/.config/tutanota-desktop/logs` are the same. Maybe you could enable some verbose logging for such cases,

I also just renamed the whole `~/.config/tutanota-desktop` folder and tried again - same issue

**Comment by johnbotris** [comment] 2021-04-12 12:55
It seems like this was somehow a system issue? So I'll close this for now, but if more information comes about we can reopen

**Closed by johnbotris** 2021-04-12 12:55 UTC
Labels: bug, desktop
