### ISSUE TITLE
Attachment downloading gets stuck sporadically

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2766] opened 2021-02-26 09:59 UTC
I'm getting stuck with an infinite progress dialog when trying to download/open attachments in the test desktop client

**Comment by johnbotris** [comment] 2021-02-26 10:09
I can't reproduce this on either local dev or dist builds.

**Comment by johnbotris** [comment] 2021-02-26 10:09
It has inexplicably started working for me now on the test system client. before the call to filedataservice was not even being triggered, but it's started working now

**Comment by johnbotris** [comment] 2021-02-26 10:14
It's started happening again, still not able to reproduce locally (sorry for  the notification spam)

**Comment by johnbotris** [comment] 2021-02-26 11:16
Server request is timing out when we try to download from the native side.

**Comment by johnbotris** [comment] 2021-03-01 08:16
No one else could reproduce this, I guess something was going wrong on my end?

**Comment by charlag** [comment] 2021-03-01 09:29
I've had it and with all kinds of downloads (native and not) and it seemes like it was getting stuck on saving but then it fixed itself

**Comment by bedhub** [comment] 2021-03-03 14:54
We should keep this error open. I ran into this situation today with desktop client version 3.82.3. I logged out and logged in back (pressed F5) but the situation did not change. Closing application window and open another one still leads to this infinite progress dialog. I had to quit the background process and then start the application again and then downloading of the same file was possible.

I currently don't have a way to reproduce this case but it is reported by users as well on each desktop client platform.

**Comment by armhub** [comment] 2021-03-03 15:22
I also had it today, but just in one newly opened desktop client window. The already open window did not show this error. Same as bedhub after stopping the desktop client completely and restarting the problem was gone.

**Comment by charlag** [comment] 2021-03-10 16:31
@bedhub managed to reproduce it somehow reliably and the issue is that window ID and webContents ID are not the same and we are relying on this. We should use `BrowserFind.fromWebContents()` instead.

**Comment by bedhub** [comment] 2021-03-11 08:02
So i added a log entry locally now in IPC.js for debugging.

```
this._electron.ipcMain.handle('to-main', (ev: WebContentsEvent, request: any) => {
   const bwId = BrowserWindow.fromWebContents(ev.sender).id;
   if (bwId !== ev.sender.id) {
      console.log("!!! Browser window id and sender id are different. bwId", bwId, "senderId", ev.sender.id)
   }
```

The easiest way to reproduce this case is to open dev tools for the first window (F12) and then create a new application window. Then sender id and window id are different then. It seems that the dev tools window is a window without a web content sender which sound logically. 

But how can a usual user run into such situation? I checked these places:

- Reloading a window with F5 (does it change web content sender id without incrementing window id?) -> No problem
- Log out/ login (kind of the same as first approach) ) -> No problem
- Opening an attachment (Is window id incremented when opening another application?) ->  No problem
- Downloading attachment (Is native file chooser considered as window?) -> No problem
- Change download location in Settings.-> No problem
- Change payment method to PayPal -> **Error**
- Change payment method to CreditCard ->  **Error**
- Clicking on a link to open in MailViewer. -> **Error**

After opening the default browser from the desktop application browser window id and sender id are different.

**Comment by johnbotris** [comment] 2021-03-15 14:25
Still getting a never-ending progress dialog when I try to open an attachment. Download/export etc seem to be working

**Comment by johnbotris** [comment] 2021-03-15 14:41
after stopping the app and restarting multiple times, it has begun working?

**Comment by bedhub** [comment] 2021-03-23 10:30
I managed to reproduce it after logging it with second factor.
1. Add second factor TOTP to account
2. Logout and login with Password and TOTP
3. Download attachment -> Error: desktop client gets stuck

It does not occur with stored credentials.

**Closed** 2021-03-24 09:05 UTC
Labels: bug, desktop, tested
