### ISSUE TITLE
Problem with the week start parameter when adding new event

### ISSUE THREAD

**Issue by EmilDey** [tutao/tutanota#3797] opened 2022-01-16 20:52 UTC
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
I have the settings  week start on monday defined
But in an Android phone when inserting a new event, there are two diferent calendars
if you click in From  a calendar (with tutanota colors )shows up that works fine
But if you click in the selected date , a new calendar shows up (diferent color set) but now the week start on sunday. and that can make that you put the wrong date.

**To Reproduce**
1. Go to Calendar
2. Click on +, and then in 1/20/2022

*

**Smartphone (please complete the following information):**
 - Device: Android

**Comment by charlag** [comment] 2022-01-17 08:28
Screenshots would help but as far as I understand the one you are talking about is a system OS for calendar, we don't have too much control over that at the moment.

**Comment by EmilDey** [comment] 2022-01-17 10:09
The problem is that from the same screen, you can go to 2 different input date calendar functions.

Probably there are two different links , one if you click from and one if you click the date.

Jan 17, 2022, 09:28 by ***@***.***:

**Comment by EmilDey** [comment] 2022-01-17 11:36
![Uploading Screenshot_20220117-093129.png…]()
![Screenshot_20220117-093142](https://user-images.githubusercontent.com/92388428/149762873-f5395333-eba7-4275-ae87-e1f8976880c6.png)

**Comment by EmilDey** [comment] 2022-01-17 11:38
![Screenshot_20220117-093129](https://user-images.githubusercontent.com/92388428/149763091-d092daa7-75a3-42ce-b4cb-bbc2e7c5730f.png)

**Comment by charlag** [comment] 2022-01-17 11:42
@EmilDey thanks for the screenshots, the second one should not be visible on mobile, this is indeed a bug. Any specific way you could open this one?

**Comment by EmilDey** [comment] 2022-01-17 11:46
Clicking in the  date field under from

**Comment by charlag** [comment] 2022-03-03 08:56
This is a duplicate of #3860

**Closed by charlag** 2022-03-03 08:56 UTC
Labels: bug
