### ISSUE TITLE
Date Picker Agenda View Not Working

### ISSUE THREAD

**Issue by bobmatyas** [tutao/tutanota#2246] opened 2020-09-08 12:09 UTC
- [ x ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

On iOs the date picker is not working properly when editing an event on the agenda view. It either doesn't save the change in date or is off by one day.

**To Reproduce**

1. Go to 'Agenda View"
2. Tap on an event
3. Tap on the pencil icon
4. When the event opens, try to change the date. It will either not change or will be off by one day (i.e. picking September 9 will result in September 8 for the event date).

**Expected behavior**

I should be able to edit the date of an event.

**Screenshots**

![tuta-date-01](https://user-images.githubusercontent.com/45246438/92474964-a567d080-f1aa-11ea-8e99-a3ee945efe47.png)

![tuta-date-02](https://user-images.githubusercontent.com/45246438/92474974-a993ee00-f1aa-11ea-9aa9-8f1ac3ec9e1a.png)

**Smartphone (please complete the following information):**

 - Device: [e.g. iPhone SE]
 - OS: [e.g. iOS 13.7]
 - Version [e.g. 3.76.7]

**Comment by charlag** [comment] 2020-09-09 07:44
Hi, thanks for the report
May I ask if you could click elsewhere after picking the date and before clicking on date picker again? I believe that it's bug in iOS where it doesn't upate the picker if you click on it again.

**Comment by bobmatyas** [comment] 2020-09-09 22:36
I gave that a try but it didn't change it. The date always seems to be off by one day (i.e. picking September 10 selects September 9, September 11 selects September 10, etc).

**Comment by bobmatyas** [comment] 2020-09-25 13:46
Came here to report that this is still an issue after upgrading to iOS 14. It also happens when creating a new event as reported on #2276

**Comment by bobmatyas** [comment] 2020-10-02 00:35
With the most recent release of the Tutanota client and new date picker the issue is still happening. Trying to change the date to Oct. 3 results in the selection of Oct. 2:

![001](https://user-images.githubusercontent.com/45246438/94876358-70574280-0425-11eb-85ab-5a77f60d6fe0.jpeg)

![002](https://user-images.githubusercontent.com/45246438/94876356-6f261580-0425-11eb-8516-2b40a954c557.jpeg)

**Comment by charlag** [comment] 2020-10-08 09:48
Duplicate of #2305

**Closed by charlag** 2020-10-08 09:48 UTC
Labels: bug
