### ISSUE TITLE
Loss of almost all my folders rules

### ISSUE THREAD

**Issue by l0f4r0** [tutao/tutanota#1383] opened 2019-07-25 21:44 UTC
Starting from today around 18:30 and 21:20 CEST, I've lost almost all my folders rules (not spam ones).

The bug seems to be on server side as both the web app (v3.55.7) and Android app (v3.55.5) have been impacted at same time.

**Comment by armhub** [comment] 2019-07-26 15:06
This is a duplicate of #1073.

**Closed by armhub** 2019-07-26 15:06 UTC
Labels: bug
