### ISSUE TITLE
Calendar reminders not working in desktop app

### ISSUE THREAD

**Issue by nikolayhg** [tutao/tutanota#1439] opened 2019-08-21 09:55 UTC
**Describe the bug**
Calendar reminders not working for desktop app.

**To Reproduce**
1. Create a calendar event with a reminder in the desktop app
2. Add a reminder
3. At the time the reminder should be triggered, nothing happens.

**Expected behavior**
To receive a event reminder, best as email or in another way.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18

**Personal comment**
Calendar is unusable for me if I don't get reminders. Best with email reminders as described in #1389

**Comment by armhub** [comment] 2019-08-21 13:40
Duplicate of 1365

**Closed by armhub** 2019-08-21 13:40 UTC
Labels: bug, desktop

**Comment by nikolayhg** [comment] 2019-12-23 11:51
@armhub , the bug still exist. The duplicate #1365 was closed, but the issue is not fixed!

**Comment by nikolayhg** [comment] 2019-12-23 11:53
Client: Linux Desktop
Tutanota version: 3.66.2
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.66.2 Chrome/78.0.3904.126 Electron/7.1.3 Safari/537.36

**Comment by nikolayhg** [comment] 2019-12-23 11:55
now it works.
