### ISSUE TITLE
macOS:  Application crashes on exit with error dialog

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1282] opened 2019-05-22 15:41 UTC
This does not happen if you just open the app and then closing it immediately. You have to work a while with the desktop client and then quit the application. Here is an example output of the error information:

Process:               Tutanota Desktop [734]
Path:                  /Applications/Tutanota Desktop.app/Contents/MacOS/Tutanota Desktop
Identifier:            de.tutao.tutanota
Version:               3.50.10 (3.50.10.361)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Tutanota Desktop [734]
User ID:               501

Date/Time:             2019-05-07 10:35:58.875 +0200
OS Version:            Mac OS X 10.14.4 (18E226)
Report Version:        12

Time Awake Since Boot: 6500 seconds
Time Since Wake:       6300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [734]

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   com.github.Electron.framework 0x0000000106c4e4df 0x104eab000 + 31077599
1   com.github.Electron.framework 0x0000000106c4b00e 0x104eab000 + 31064078
2   com.github.Electron.framework 0x0000000106c4e5ef 0x104eab000 + 31077871
3   com.github.Electron.framework 0x0000000106c4c8f0 0x104eab000 + 31070448
4   com.github.Electron.framework 0x0000000106c4404a 0x104eab000 + 31035466
5   com.github.Electron.framework 0x0000000106b9ee0e 0x104eab000 + 30359054
6   com.github.Electron.framework 0x0000000106b19558 0x104eab000 + 29812056
7   com.github.Electron.framework 0x0000000104ead5df AtomMain + 95
8   de.tutao.tutanota             0x0000000104ea4f10 0x104ea4000 + 3856
9   libdyld.dylib                 0x00007fff660cd3d5 start + 1

**Comment by bedhub** [comment] 2019-06-11 14:10
Reported by user:

> I found out it only happens when I don’t log out before quitting. So maybe you just need to force a logout at that point.

**Comment by leoncfu** [comment] 2019-07-11 22:03
I am seeing this issue as well. If I do anything in the Mac app, it will crash on exit.

**Comment by nadesco** [comment] 2019-09-05 13:01
I also had this problem for many months. The app crashed about 95% of the time on exit, mostly after I'd already logged out. 

I tried uninstalling/reinstalling tutanota.app and associated files a couple of months ago without any success. However I recently tried again and was more successful. To make sure that all files related to Tutanota were removed, I used AppCleaner (linked with instructions in the url below.)

https://www.howtogeek.com/273722/how-to-reset-any-mac-app-to-its-default-settings/

I then rebooted and reinstalled the most recent version. It's been a couple of days and I haven't had any 'unexpectedly quit' messages pop up since then so the problem seems to be resolved (touch wood). Not sure if this will work for everyone but it's worth a shot.

**Comment by charlag** [comment] 2019-10-07 10:23
It's almost certainly caused by https://github.com/electron/electron/issues/19842

**Comment by charlag** [comment] 2019-11-28 16:46
I've added a long comment with my idea of why it might happen:
https://github.com/electron/electron/issues/19842#issuecomment-559557495

**Comment by ganthern** [comment] 2020-01-21 12:43
should be fixed with https://github.com/electron/electron/pull/21709 which is part of electron [v7.1.9 ](https://electronjs.org/releases/stable#release-notes-for-v719)

**Closed** 2020-01-28 10:00 UTC
Labels: bug, desktop
