### ISSUE TITLE
Login doesn't work on Linux Manjaro Desktop Client

### ISSUE THREAD

**Issue by Solations** [tutao/tutanota#7076] opened 2024-06-05 15:45 UTC
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Describe the bug**
Since the new update there's no longer the option not to safe the login information on the PC. It is now at least on Linux Manjaro no longer possible to login, if one didn't activate the internal password storage. Error message is simply "An Error occurred." I guess an easy fix for Users would be to activate internal safe storage. However it would be nice to be able to login anyway.

**To Reproduce**
1. Login

**Expected behavior**
Login

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - KDE-Plasma-Version: 6.0.5
 - KDE-Framework-Version: 6.0.5
 - Tuta-Version: v230.240603.0

**Additional context**
Login worked fine before I updated to the version mentioned above.

**Full Error Message**
Client: linux
Type: PAID
Tutanota version: 230.240603.0
Timestamp (UTC): Thu, 06 Jun 2024 12:16:54 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/230.240603.0 Chrome/124.0.6367.207 Electron/30.0.6 Safari/537.36
DeviceStorageUnavailableError
Error message: failed to resolve/generate key> DeviceStorageUnavailableError: safeStorage API is not available
at K_.assertAvailable (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:192970)
at async K_.getPassword (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:192214)
at async mR.fetchKey (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:209968)
at async mR.fetchOrGenerateKey (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:209695)
at async _P.encryptUsingKeychain (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:25:16448)
at async qO.getOrCreateCredentialEncryptionKey (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:285976)
at async qO.setCredentialEncryptionMode (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:285020)
at async ipc (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:294946)
Stacktrace:
DeviceStorageUnavailableError: failed to resolve/generate key> DeviceStorageUnavailableError: safeStorage API is not available
at K_.assertAvailable (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:192970)
at async K_.getPassword (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:192214)
at async mR.fetchKey (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:209968)
at async mR.fetchOrGenerateKey (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:209695)
at async _P.encryptUsingKeychain (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:25:16448)
at async qO.getOrCreateCredentialEncryptionKey (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:285976)
at async qO.setCredentialEncryptionMode (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:285020)
at async ipc (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:294946)
at mR.fetchOrGenerateKey (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:209869)
at async _P.encryptUsingKeychain (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:25:16448)
at async qO.getOrCreateCredentialEncryptionKey (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:285976)
at async qO.setCredentialEncryptionMode (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:285020)
at async ipc (/tmp/.mount_tutanorQI7hx/resources/app.asar/desktop/DesktopMain.js:11:294946)

**Comment by charlag** [comment] 2024-06-10 08:17
Duplicate of  #7077

**Closed by charlag** 2024-06-10 08:17 UTC
Labels: bug, desktop
