### ISSUE TITLE
Birthdays with incomplete date showing contact age

### ISSUE THREAD

**Issue by andrehgdias** [tutao/tutanota#7785] opened 2024-10-21 14:54 UTC
If you don't put a year, it will display the # of years old as if it was 1970. For example, "(54 years old)" for a 2024 date.

Also, it will show no dates prior to 1970, although this one is probably not a big deal since it's not 1970 anymore.

_Originally posted by @paw-hub in https://github.com/tutao/tutanota/issues/7676#issuecomment-2426667765_

**Comment by wrdhub** [comment] 2024-10-22 07:06
Duplicate of  #7783

**Closed by wrdhub** 2024-10-22 07:06 UTC
Labels: dev bug, topic: calendar
