### ISSUE TITLE
Windows desktop notifications doesn't work for updating the app

### ISSUE THREAD

**Issue by Backspaze** [tutao/tutanota#4472] opened 2022-08-07 16:36 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When desktop app sends a notification about a new update being available, the notification says **Click here to update** but nothing happens when you click the notification except that the notification disappears.

**To Reproduce**
There are no exact steps for reproducing the issue, but the issue is the same for both of my Windows devices. So I guess:

1. Install the desktop app.
2. Wait for an update notification.
3. ~~Click on the update notification.~~ Don’t click the notification, instead let it land in the notification center.
4. Open the notification center.
5. Click on the notification.
6. The notification disappears but nothing else happens.

**Expected behavior**
When you click the notification, the installation of the update should start.

**Screenshots**
![bild](https://user-images.githubusercontent.com/12255362/183242874-713eba18-d68d-4eef-ad9c-3171c8f9f756.png)
Screenshot in Swedish, translated to English:

> There's an update for Tutanota desktop app (3.98.20)
> Click here to update. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Desktop Environment: NA
 - Version: 21H1 (19043.1826) and 21H2 (19044.1826)

**Additional context**
Workaround consists of going to **Settings** > **Desktop** > **Automatic Updates** and click install there or download and install the app from https://tutanota.com/. This issue has been around since the "automatic updates" were first introduced in the desktop app.

**Comment by johnbotris** [comment] 2022-08-09 15:49
I tried this locally and I couldn't reproduce the issue: clicking the notification caused the update process to begin

**Comment by Backspaze** [comment] 2022-08-09 16:52
@johnbotris did you click the notification immediately when it popped up or did you click it later when it's stored in the notification tray, or have you tried both ways and it worked either way?

I'm rarely in front of my screen to catch the notification right when it pops up, so I usually find it later in the notification tray (that's where the screenshot is from) and clicking the notification there does nothing. I can't say if it makes any difference if I manage to click the notification right when it pops up as I haven't been able to test that as there's no way to tell when the notification will appear.

Is there any way to get any relevant logs for this, maybe in Windows Event Viewer?

**Comment by Backspaze** [comment] 2022-08-09 20:30
I did a test just now by sending some test emails and if I click on the notification right when it pops up, it opens the app. It doesn't open the email I just received, it just brings the app in focus, but that's a whole other issue which I think is related to Tutanota's stance on privacy and encryption which means that the OS can only send a generic notification without knowing anything about it's contents.

Anyway, if I ignore the notification and let it land in the notification tray and then click on it, the result is the same as with the update notifications; nothing happens except that the notification disappears. This, naturally, makes me think that if I somehow manage to click on a update notification right when it pops up, it will probably trigger the update correctly. **But both email and update notifications should work even if they're in the notification tray**.

@johnbotris with the above in mind, I repeat my previous question, have you tested clicking the notifications from the notification tray as well?

**Comment by johnbotris** [comment] 2022-08-12 10:39
@Backspaze thanks for the info. I can confirm I'm seeing the same behaviour, also with email notifications. I'll assume that it's stemming from the same issue in both cases and work from that

**Comment by Backspaze** [comment] 2022-08-12 10:51
@johnbotris Thanks for confirming the issue. I’ve updated the steps under **To Reproduce** for clarity.

**Comment by johnbotris** [comment] 2022-08-12 14:15
This seems to be an issue with Electron. Clicking on a notification from the notification centre doesn't cause a 'click' event to be fired. This was noted in a comment [here](https://github.com/electron/electron/issues/32261#issuecomment-1001256037). I've also been able to confirm this with a small test app.

**Comment by johnbotris** [comment] 2022-08-12 14:17
https://github.com/electron/electron/issues/31390

**Comment by Backspaze** [comment] 2022-08-12 14:39
Ah, thanks for clearing that up. I’ve also noticed old notifications returning as described in that comment, and that’s not unique to Tutanota.

**Comment by johnbotris** [comment] 2022-08-12 15:12
I will close this issue and we can keep an eye out for any Electron updates that patch this bug.

**Closed by johnbotris** 2022-08-12 15:12 UTC
Labels: bug, desktop

**Comment by ozturkberkay** [comment] 2023-05-20 03:45
I wouldn't close this issue just yet... I'm still having the same problem, I think it would be nice to keep track of this issue until it is actually fixed.

**Comment by Backspaze** [comment] 2024-09-16 17:04
@johnbotris 

I don't know if you receive notifications for closed issues, but I just wanted to add an update to this issue, as I got reminded about this by today's iOS update for the Tuta app.

Signal managed to fix this issue for notifications in their app in version [v.6.29.1](https://github.com/signalapp/Signal-Desktop/releases/tag/v6.29.1). Since their app is open source as well, maybe you could check their code and use some or all of their solution in Tuta?

**Comment by charlag** [comment] 2024-09-30 07:39
@Backspaze  thank you for letting us know. I think this is the change:
https://github.com/signalapp/Signal-Desktop/commit/ae0aef52dd2b7c8a8450c814d09723078b1d50bf?w=1
and it was their own bug where they did not set the action on notification correctly
