### ISSUE TITLE
Navigating with arrow keys in list not working propertly

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#159] opened 2017-10-17 09:05 UTC
When navigating through a long list (emails or contacts) by holding down the up or down arrow key the navigation stops after a while and the selected element can't be changed anymore by an additional key press.

**Comment by asteintutao** [comment] 2018-10-29 14:50
i had a look into it and it happens because the browser starts throttling and the url is not set anymore can be a problem because setUrl is called to often in a short period

**Comment by charlag** [comment] 2019-10-04 14:48
Duplicate of #666

**Closed by charlag** 2019-10-04 14:48 UTC
Labels: bug
