### ISSUE TITLE
Desktop v240.240813.0 (Windows) ask multiple times for app password

### ISSUE THREAD

**Issue by MustachedMario** [tutao/tutanota#7406] opened 2024-08-15 16:42 UTC
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Describe the bug**
Latest Desktop Version for Windows ask for randomly 3 to 9 times for app password on start!

**To Reproduce**
1. Start app
2. enter app password
3. see darkened login mask
4. enter app password
5. see darkened parts of mails
6. enter app password
7. enter app password again
8. enter app password again ...

**Expected behavior**
Enter app password once

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro]
 - Version [240.240813.0]

**Additional context**
unset app password and re-set app password won't help.
entered password must allways be correct to pass.

**Comment by charlag** [comment] 2024-08-16 07:55
Duplicate of https://github.com/tutao/tutanota/issues/7382
(will get released soon)

**Closed by charlag** 2024-08-16 07:55 UTC
Labels: bug, desktop
