### ISSUE TITLE
Missing permission check when a file is shared

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#652] opened 2018-10-06 08:47 UTC
We have to check for the storage permissions when a file is shared via Tutanota. Otherwise, the following happens (if storage permission is not set):

```
Stacktrace: 
java.io.FileNotFoundException: /storage/emulated/0/textfee/pdfs/1.pdf (Permission denied)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.(FileInputStream.java:146)
at java.io.FileInputStream.(FileInputStream.java:99)
at android.content.ContentResolver.openInputStream(ContentResolver.java:700)
at de.tutao.tutanota.Crypto.aesEncryptFile(Crypto.java:188)
at de.tutao.tutanota.Native.invokeMethod(Native.java:176)
at de.tutao.tutanota.Native.lambda$invoke$2$Native(Native.java:78)
at de.tutao.tutanota.Native$$Lambda$0.run(Unknown Source)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by charlag** [comment] 2018-10-08 06:11
Duplicate of #623 / #620 ?

**Closed** 2018-10-08 08:00 UTC
