### ISSUE TITLE
Calendar events not shrinking, producing UI glitches, hiding colliding events

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#2943] opened 2021-04-15 09:29 UTC
Event bubbles in the calendar view only shrink until some fixed width. When overflowing their column the adjacent grid lanes are drown on top.

The event bubbles should just keep shrinking, cutting off more and more of the event title. Right now if the view is too narrow and there are two events at the same time, the right one (as in "not left") will not be visible at all.

![Screenshot from 2021-04-15 11-22-59](https://user-images.githubusercontent.com/6842104/114847234-c72ed300-9ddd-11eb-8992-e5b1931165ba.png)

**Comment by johnbotris** [comment] 2021-04-15 10:06
Duplicate of #2847

**Comment by johnbotris** [comment] 2021-04-15 10:06
Fix is included in this release :smiley_cat:

**Closed by johnbotris** 2021-04-15 10:06 UTC
Labels: bug
