### ISSUE TITLE
24 hour time showing 24:xx instead of 00:xx

### ISSUE THREAD

**Issue by tsumeone** [tutao/tutanota#1983] opened 2020-04-11 04:11 UTC
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Describe the bug**
The desktop app is showing a timestamp of 24:05 for an email I received at 00:05.  It is doing the same for other emails in other folders (24:02 for an email received at 00:02 for example).  The web app seems to show correctly (although it initially loads in 12 hour time, when i click somewhere else and click back it is showing 24 hour time and it is showing it correctly, eg 00:05).

**To Reproduce**
1. Set preferences to 24 hour time
2. Receive an email after midnight
3. See that the time is showing 24:xx instead of 00:xx

**Expected behavior**
Time displays correctly as 00:xx

**Screenshots**
<img width="436" alt="Tutanota_Desktop_2020-04-11_00-06-14" src="https://user-images.githubusercontent.com/63486880/79035082-ef5f7280-7b88-11ea-81be-def66788657a.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 3.69.5

**Comment by charlag** [comment] 2020-04-14 08:06
Hi
We believe it's a bug in Chromium

**Comment by charlag** [comment] 2020-11-04 09:35
Duplicate of #1870

**Closed by charlag** 2020-11-04 09:35 UTC
Labels: browser-bug, bug
