### ISSUE TITLE
Desktop app on Linux not running as tray app

### ISSUE THREAD

**Issue by cypherpunk1984** [tutao/tutanota#1905] opened 2020-03-12 14:40 UTC
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Describe the bug**
Tutanota Desktop app for Linux v 3.68.1
"Run as tray app" and "Desktop integration" both activated, and there is no app icon on tray. And when I open the app, if I minimize it, doesn't go to tray. And if you press the X it shuts down completely. So, after opening the app for the first time after booting I have 2 choices, to keep the window on the panel or to close it completely.

**Expected behavior**
 - App's icon on tray
 - Minimize or close to tray after opening

**Screenshots**
https://imgur.com/a/9oiMKeW

**Desktop (please complete the following information):**
 - OS: Linux Mint Tricia 19.3 64 bits
 - Desktop Environment: Cinnamon

**Comment by charlag** [comment] 2020-03-16 11:02
Duplicate of #1829

**Closed by charlag** 2020-03-16 11:02 UTC
Labels: bug, desktop
