### ISSUE TITLE
Make calendar event editor tests deterministic

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#4581] opened 2022-09-15 15:07 UTC
Some tests compare 'Date' objects that are created at separate times, but which should be the same exact time. Most of the time this is OK because the tests run fast, but occasionally the test will fail because of a millisecond (or nano?) difference.

**Comment by charlag** [comment] 2022-11-11 08:46
Duplicate of #4085

**Closed by charlag** 2022-11-11 08:46 UTC
Labels: improvement
