### ISSUE TITLE
Text editor improvements

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#869] opened 2018-11-30 07:35 UTC
- on iPad the dropdown for font sizes opens the keyboard and it is not possible to select a font size.
- change layout of the font size buttons from round to square layout, maybe we can also remove the labels of the font size input.
- decrease space between subject line and editor buttons.

**Comment by charlag** [comment] 2018-11-30 14:50
Duplicate of #873

**Closed by charlag** 2018-11-30 14:50 UTC
