### ISSUE TITLE
BadRequestError on GET mailbox

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#953] opened 2018-12-17 09:58 UTC

**Comment by charlag** [comment] 2018-12-17 09:58
Happening for some time and in v3.43.1

**Comment by charlag** [comment] 2019-01-14 09:32
v3.44.9

> When I clicked Buy on the create account screen it gave me an unexpected error

**Comment by bedhub** [comment] 2019-03-12 10:32
duplicate of #950

**Closed by bedhub** 2019-03-12 10:32 UTC
Labels: bug
