### ISSUE TITLE
HTML even with plain text (using GhostText)

### ISSUE THREAD

**Issue by gour** [tutao/tutanota#3993] opened 2022-03-29 12:53 UTC
- [x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
**Bug in web app**
Tutanota's desktop client does not support using external editors (e.g. vim) to compose messages, so I tried with the web client and selected 'plain text' as the format and then attempted to use Ghost Text extension in Firefox, but, alas, despite of selecting 'plain' text, Tutanota handles content in HTML and then, probably,  just convert to 'plain' before sending. :-(

At the moment, I'm also testing mailbox.org where when selecting 'plain' one gets it in the external editor.

Tutanota is great service, but for those using 3rd party clients and/or editors it is cumbersome to have limited editing capabilities provided by the desktop client or web app.

**Expected behavior**
When one selects plain text format, web app should render it as plain in the area used by GhostText extension.

**Screenshots**
Here is the shot of the web app screen:
![tutanota-webapp](https://user-images.githubusercontent.com/114592/160614914-9662998a-35fd-472c-80c2-b06cec4e6242.png)

Here is the shot in the editor:
![tutanota-editor](https://user-images.githubusercontent.com/114592/160615034-ab023ff7-60c8-4870-962e-768c71186029.png)

And here you can see how it does look in mailbox.org web app:
![mailbox-app](https://user-images.githubusercontent.com/114592/160615139-8c643b50-2643-4f29-a130-9827554e2896.png)

and how it is rendered within the editor:
![mailbox-editor](https://user-images.githubusercontent.com/114592/160615231-f99684dd-4369-4d6a-b096-7c754f83f998.png)

I subscribed for one year to Premium, but I'm afraid that due to such issues I'll subscribe to mailbox.org.

Sincerely,
Gour

**Comment by johnbotris** [comment] 2022-03-30 07:08
When in plaintext mode, the formatting is stripped before being sent

**Comment by johnbotris** [comment] 2022-03-30 07:08
duplicate of https://github.com/tutao/tutanota/issues/1588

**Closed by johnbotris** 2022-03-30 07:08 UTC
Labels: bug
