### ISSUE TITLE
Login issues on Android

### ISSUE THREAD

**Issue by blankscreengithub** [tutao/tutanota#7290] opened 2024-07-27 23:05 UTC
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in mobile app**
Does not log into my email account. The app just keeps spinning giving messages about stocking the Tuta fridge, etc. I can log into my account with a different Android device

**Describe the bug**
Can't log in.

**To Reproduce**
1. Install app on phone
2. Tap app tp open
3. Enter my email address and password
4. Login loop begins and it never asks for my 2FA

**Expected behavior**
Log into the app.

**Smartphone (please complete the following information):**
 - Device: Samsung Fold3
 - OS: Android
 - Version 14

**Comment by retorquere** [comment] 2024-07-28 05:58
Same problem on pixel 8

**Comment by yogi701** [comment] 2024-07-28 13:28
Same problem on Galaxy A53 also

**Comment by KriiXOne** [comment] 2024-07-28 16:38
Can confirm, has been happening since two full days on my Galaxy A55 as well.

**Comment by retorquere** [comment] 2024-07-28 17:45
And since this was my 2nd factor, I can't login via the web either. What does "reset 2nd factor" do?

**Comment by jboucher614** [comment] 2024-07-29 00:19
Started happening on my S22 Ultra after I enabled the new notification settings, but not sure if related. Wiping app data didn't help.

**Comment by charlag** [comment] 2024-07-29 09:05
Can anyone get logs with adb/logcat/catlog or similar? We are struggling to reproduce it and it would help a lot

**Comment by charlag** [comment] 2024-07-29 09:07
It would help us to know your Android version too

**Comment by charlag** [comment] 2024-07-29 09:26
I suspect it is a WebView issue. If you could check the WebView app version you have installed it could also help us

**Comment by charlag** [comment] 2024-07-29 09:33
I can repro it with WebView beta (128.0.6613.6)

**Comment by charlag** [comment] 2024-07-29 10:46
we conducted more testing and we are fairly certain that it is some change in Chrome WebView 128 (can reproduce on 128.0.6613.6, cannot reproduce on 127.0.6553.64).

Chrome 128 is due to be released in 2 weeks, please check whether you are on WebView beta channel.

**Comment by retorquere** [comment] 2024-07-29 10:46
Pixel 8, android 14, webview 128.0.6613.6

**Comment by retorquere** [comment] 2024-07-29 10:47
>  please check whether you are on WebView beta channel.

How do I check this?

**Comment by retorquere** [comment] 2024-07-29 10:49
I do not have https://play.google.com/store/apps/details?id=com.google.android.webview.beta installed if that's what you mean.

**Comment by charlag** [comment] 2024-07-29 10:50
> > please check whether you are on WebView beta channel.
> 
> How do I check this?

if you have it from Play Store, check if you are on Beta Track for WebView or if you have a separate app called "WebView Beta".

More info here:
https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/prerelease.md

**Comment by retorquere** [comment] 2024-07-29 10:54
I only see https://play.google.com/store/apps/details?id=com.google.android.webview.beta and https://play.google.com/store/apps/details?id=com.google.android.webview.dev in the play store, neither of which are installed. Do you have a link to the version you mean I might be on the beta track for? I do see the "regular" webview installed in my apps list in the settings.

**Comment by retorquere** [comment] 2024-07-29 10:56
Ah; if I go to https://play.google.com/store/apps/details?id=com.google.android.webview, I *do* see it listed as "Android System WebView (Beta)", and it does say "you're a beta tester", but I don't see an option to leave the beta, and I'm not sure why I would have joined the beta in the first place.

**Comment by N3OG** [comment] 2024-07-29 11:08
The WebView "bug" is in stable now, must uninstall the actual version to my system-default version. Now i can login again ....

**Comment by retorquere** [comment] 2024-07-29 11:12
Uninstall + reinstall of webview fixes the problem for me.

**Comment by charlag** [comment] 2024-07-29 11:53
What does it mean it's "in stable now"? https://chromestatus.com/roadmap shows that 128 is "stable in 2 weeks (Aug 14, 2024)

**Comment by N3OG** [comment] 2024-07-29 12:39
If i "update" this https://play.google.com/store/apps/details?id=com.google.android.webview i have the same issue... if i uninstall ist, its possible to login

**Comment by charlag** [comment] 2024-07-29 12:57
@N3OG what version do you see available for you to install or what version do you see after install?

**Comment by jboucher614** [comment] 2024-07-29 13:16
> we conducted more testing and we are fairly certain that it is some change in Chrome WebView 128 (can reproduce on 128.0.6613.6, cannot reproduce on 127.0.6553.64).
> 
> Chrome 128 is due to be released in 2 weeks, please check whether you are on WebView beta channel.

I can confirm. I was in the beta program for Webview, on version 128, and I had this issue. I left the program and uninstalled updates for Webview. I waited a few minutes, cleared Play Store cache, then updated Webview. It updated to version 126. No issue now.

**Comment by charlag** [comment] 2024-07-29 13:44
> 126.0.6478.186 is installed

is this the version you have issue with or is this the version that works?

you said that there is an issue with the version that is available to you via Play Store. What version is that?

**Comment by notojak** [comment] 2024-07-29 13:48
> > 126.0.6478.186 is installed
> 
> is this the version you have issue with or is this the version that works?
> 
> you said that there is an issue with the version that is available to you via Play Store. What version is that?

![Screenshot_20240729-154739_Settings](https://github.com/user-attachments/assets/63c5d505-7efe-44bb-874a-b31910d231da)

**Comment by N3OG** [comment] 2024-07-29 13:51
> > 126.0.6478.186 is installed
> 
> is this the version you have issue with or is this the version that works?
> 
> you said that there is an issue with the version that is available to you via Play Store. What version is that?

There was an issue with that, but restart of my phone helps... maybe some cache problems...

**Comment by seymourb61** [comment] 2024-07-29 18:19
Exact same issue for 2 days - Samsung A53 5G (model name SM-A536UI/DS), Android v13, security patch level March 1, 2023, One UI v5.1, Baseband v A5336U1UEU4CWC3. Occurs on both wifi and mobile data (Mint Mobile). Access via Windows app is fine.

**Comment by rezbyte** [comment] 2024-08-01 08:23
There is now [an issue on the Chromium tracker](https://issues.chromium.org/issues/352584425) relevant to the underlying problem in the WebView beta.

**Comment by Zukauskas** [comment] 2024-08-03 07:18
Yeah 
- leave webview beta
- clear play store cache(don't know if necessary)
- reinstall webview
Worked for me, thanks 🙏

**Comment by wpeckham** [comment] 2024-08-06 18:25
Same problem in BLU G90+ running Android 10.  Cycle opens LOGGING IN, then the cycle starts DECRYPTING EMAIL, ORGANIZING CALENDAR EVENTS, SORTING CONTACTS, UPDATING OFFLINE DATABASE, CYCLING TO WORK, RESTOCKING TUTA FRIDGE, PREPARING ROCKET LAUNCH, TURNING ON PRIVACY, DECRYPTING EMAIL.....

**Comment by ThreeTima** [comment] 2024-08-14 17:16
> Yeah
> 
>     * leave webview beta
> 
>     * clear play store cache(don't know if necessary)
> 
>     * reinstall webview
>       Worked for me, thanks 🙏

This worked for me, It's now working again... I should point out, however, that the Play store may say that the "Beta is still installed" even after you follow the steps above. However, just try it and it should work.... If it does not, try the above again with a device reboot in between the "Clear Play Store cache" and the "Re-install webview".

> There is now [an issue on the Chromium tracker](https://issues.chromium.org/issues/352584425) relevant to the underlying problem in the WebView beta.

I'm Glad someone submitted it to Android for further looking into

**Comment by DrDivan55** [comment] 2024-08-18 13:24
The issue is still not fixed. 128 is now WebView stable. Tested with WebView Canary 129, the issue is present.
Uninstalling the WebView is not a good solution, as the phone will automatically later update back to WebView 128. It might work for the initial login, but when WebView is later updated back to 128, it would stop working again if you have a biometric lock enabled.
This means the app is unusable on Android if you have the biometric lock enabled.

**Comment by DrDivan55** [comment] 2024-08-18 21:31
Update: After installing the August security patch for my Samsung Galaxy Note 20 Ultra, I was able to login successfully & everything works as intended as of now.

**Comment by jwacross** [comment] 2024-08-20 17:17
The android app is working for me now as well.
Samsung Galaxy S22
One UI version 6.2
Android version 14

**Comment by wpeckham** [comment] 2024-08-22 15:11
> Same problem in BLU G90+ running Android 10. Cycle opens LOGGING IN, then the cycle starts DECRYPTING EMAIL, ORGANIZING CALENDAR EVENTS, SORTING CONTACTS, UPDATING OFFLINE DATABASE, CYCLING TO WORK, RESTOCKING TUTA FRIDGE, PREPARING ROCKET LAUNCH, TURNING ON PRIVACY, DECRYPTING EMAIL.....

I did make sure I was not in the beta program and removed all manual webmin installs and restarted the phone. This did not affect the behavior, login was still impossible. That to the fridge must be pretty full by now.

**Comment by charlag** [comment] 2024-08-26 08:59
It seems to be fixed in Chromium, closing it as we cannot do much about it.

**Closed by charlag** 2024-08-26 08:59 UTC
Labels: bug, android
