### ISSUE TITLE
Prevent duplicate calendar event ids when importing calendar

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2324] opened 2020-10-14 09:37 UTC
This error occurred while importing a calendar file. Seems like a duplicate id has been created and the import process was aborted. We need to prevent id duplication during import. 

Client: Browser
Type: PREMIUM
Tutanota version: 3.76.11
Timestamp (UTC): Sat, 10 Oct 2020 07:39:45 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15
PreconditionFailedError
Error message: 412: db.exists | POST /rest/tutanota/calendarevent/MJGPiho--7-2
Stacktrace: 
PreconditionFailedError. 412: db.exists | POST /rest/tutanota/calendarevent/MJGPiho--7-2
PreconditionFailedError@https://mail.tutanota.com/common.js:1:255817
https://mail.tutanota.com/common.js:1:251309
https://mail.tutanota.com/worker.js:1:722080

**Comment by vitoreiji** [comment] 2020-10-14 09:55
Duplicate of #2220?

**Comment by bedhub** [comment] 2020-10-14 11:18
This happened for a calendar file exported from Tutanota. I am not sure anymore if this only happens because of duplicate UID. So i created a new issue.

**Comment by bedhub** [comment] 2020-10-14 12:04
I checked the logs and it is really a different case. In this case there is a collision with the custom id on the event. Here is the stack strace from the serer:

```
de.tutao.tutadb.rest.exceptions.PreconditionFailedException: can't override existing list element with id ["M9MV3n1--7-2","MTYwMzQ1ODI0NTMxNA"] (CalendarEvent)
	at de.tutao.tutadb.instance.resources.DefaultListElementResource.lambda$post$0(DefaultListElementResource.java:85) ~[tutadb-server-3.76.28.jar:na]
```

**Comment by charlag** [comment] 2020-11-30 09:07
Reported still for accepting invites (maybe twice?)

**Comment by charlag** [comment] 2022-11-10 15:15
I believe this is now fixed

**Closed by charlag** 2022-11-10 15:15 UTC
Labels: bug
