### ISSUE TITLE
Error Message after latest Update

### ISSUE THREAD

**Issue by HarriBuh** [tutao/tutanota#8053] opened 2024-11-28 13:09 UTC
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**To Reproduce**
1. Update app to latest Version 252.241122.0
2. Open app
3. See error

**Screenshots**
![Screenshot_20241128-140847.png](https://github.com/user-attachments/assets/fcd577ac-9d1f-42c0-9daa-d62b3aca06ec)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: Android
 - Version 15

**Additional context**

Feedback v252.241122.0 - ProgrammingError - UNKNOWN - android

 Client: android
 Type: UNKNOWN
 Tutanota version: 252.241122.0
 Timestamp (UTC): Thu, 28 Nov 2024 13:05:36 GMT
 User agent:
Mozilla/5.0 (Linux; Android 15; Pixel 7 Build/AP3A.241105.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/132.0.6834.14 Mobile Safari/537.36
ProgrammingError
 Error message: You forgot to migrate your databases! sys.version should be >= 114 but in db it is 112
Stacktrace: 
ProgrammingError: You forgot to migrate your databases! sys.version should be >= 114 but in db it is 112
    at Hc.checkStateAfterMigrations (https://assets.tutanota.com/mail-worker.js:23:63094)
    at async Hc.migrate (https://assets.tutanota.com/mail-worker.js:23:62872)
    at async Ws.init (https://assets.tutanota.com/mail-worker.js:1:19717)
    at async pc.getStorage (https://assets.tutanota.com/mail-worker.js:23:50139)
    at async pc.initialize (https://assets.tutanota.com/mail-worker.js:23:49906)
    at async qo.initCache (https://assets.tutanota.com/mail-worker.js:23:10521)
    at async qo.resumeSession (https://assets.tutanota.com/mail-worker.js:23:7331)

**Comment by charlag** [comment] 2024-11-28 13:29
Sorry, it's a duplicate of #8053

**Closed by charlag** 2024-11-28 13:29 UTC
Labels: bug

**Comment by charlag** [comment] 2024-11-28 15:49
Sorry it's #8044
