### ISSUE TITLE
The web app drops emails when an inbox filter to folder is enabled for another recepient with the same name, different domain

### ISSUE THREAD

**Issue by mckravchyk** [tutao/tutanota#6176] opened 2023-11-19 11:16 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
This is a **severe** bug that results in not being able to receive messages. Setting up an inbox rule to move to folder for a recepient with the same name / alias (before @) but different domain will make any emails coming to that address unreceivable and the Sent folder will oddly show new messages that are not there (it does not have anything to do with sending on Tuta side).

domain1 and domain2 are custom domains - I did not test the behaviour with Tuta domains, but it's possible it could also occur with those.

**To Reproduce**
1. Set up test@domain1
2. Set up a rule for emails to test@domain1 go to test1 folder
3. Send a message from another provider (actually tested Gmail) to test@domain1, the message should be received and in the folder
4. Set up test@domain2
5. Set up a rule for emails to test@domain2 go to test2 folder
6. Send an email to test@domain2 from another provider
7. Notice that the message never arrived and the count on the Sent folder has increased. It increases consistently with every message that is sent to the affected recepient.
8. Set up test2@domain2 and notice that it works (actually you may want to use something that does not start with test, it's possible the filter could be broken in this way too)

**Desktop (please complete the following information):**
Latest Chrome and Firefox. It seems to be a bug in the core logic, rather than browser / device specific quirk.

**Additional context**

I want to highlight that it's not about folder filtering not working, it's about not being able to receive messages to the affected recepient at all.

This is a brand new account. I have set up the first domain a little over 1 week ago and set up the second domain today. I'm a new user so it's not possible to determine when it stopped working and setting the first domain was not sufficient to reproduce it.

The folders were named like t@domain1, t@domain2 (t being short for test), I did not check with a folder name that did not contain @, it may or may not be a factor to reproduce this bug.

**Comment by ganthern** [comment] 2023-11-20 08:59
Hey @mckravchyk, thank you for the detailed report. 

Info for developers: I could not reproduce this yet on the test system with existing custom domains and internal senders. Need to try it with external senders.

**Comment by charlag** [comment] 2023-11-20 09:02
I am certain that inbox rules have nothing to do with this. Inbox rules are applied on the client side and they can't impede mail delivery whatsoever. They literally move mails between folders.

**Comment by ganthern** [comment] 2023-11-20 09:16
It would maybe also help if you contacted support with your specific custom domains and/or aliases so we can check if there's something about them that could cause this. Best include a link to this issue.

**Comment by mckravchyk** [comment] 2023-11-20 09:17
@ganthern  It's the web app, I did not try the desktop client at all.

@charlag I forgot to mention that removing the inbox filter made messages to test@domain2 receivable. You are right, the messages are received, but they go to a limbo, nowhere to be accessed - note how I mentioned the unread count on the Sent folder increases.

Yes, I opened a ticket first and posted the issue second. Have not checked yet, will soon.

**Comment by mckravchyk** [comment] 2023-11-20 10:08
I followed up on the email ticket and sent the actual email adresses / folder names that I have used.

I have just confirmed that it has to do with the folder name being like a shortened email address: t@domain1, t@domain2 or an email address in general (did not check that one yet). (Unless it's about the folders being named similarly, both starting with t@, but I guess it's most likely to be @)

So yes, I think that renaming the folders to not look like email addresses is a workaround.

**Comment by mckravchyk** [comment] 2023-11-20 10:12
Actually not, I renamed all folders to replace @ with an underscore. It must have something to do with both the emails and the folders being named similarly.

**Comment by kibhub** [comment] 2023-11-20 15:05
Closing this as not reproducible.

We will continue this issue in your open support ticket.

**Closed by kibhub** 2023-11-20 15:05 UTC
Labels: bug

**Comment by mckravchyk** [comment] 2023-11-21 08:50
@kibhub  I'm sorry for the confusion. I had a subfolder in Sent with the same name and the rule was set to target the Sent subfolder.  Sent folder was collapsed and I forgot I created those folders or that Sent can have subfolders. That's why Sent unread count has increased.
