### ISSUE TITLE
Calendar UI bug when tablet is in landscape

### ISSUE THREAD

**Issue by muchqs** [tutao/tutanota#6429] opened 2024-01-24 07:48 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When Android tablet is in landscape mode, the UI is bugged when viewing Calendar. The hamburger menu icon literally does nothing. And the "Today" button and "View Mode" button on top-right are both missing completely.

This makes it impossible to go back to "today" or change view mode while in landscape mode.

UI is back to normal when switched to portrait mode.

Please see pic
[Landscape](https://i.imgur.com/vHQv0PY.jpg)
[Portrait](https://i.imgur.com/Cs1WLpS.jpg)

**To Reproduce**
1. Go to Calendar on tablet in landscape mode

**Expected behavior**
Buttons should work and shouldn't be missing.

**Smartphone (please complete the following information):**
 - Device: Lenovo Yoga Tab 11
 - OS: Android 11

**Comment by rezbyte** [comment] 2024-01-24 15:03
Duplicate of #6337.

**Closed by rezbyte** 2024-01-24 15:03 UTC
Labels: bug
