### ISSUE TITLE
Can't log in. Error: invalid mac

### ISSUE THREAD

**Issue by realpixelcode** [tutao/tutanota#3884] opened 2022-02-09 10:14 UTC
When trying to log in via Tutanota desktop I get the following error message:

```
Feedback v3.91.9 - Error - PREMIUM - linux
Client: linux
Type: PREMIUM
Tutanota version: 3.91.9
Timestamp (UTC): Wed, 09 Feb 2022 09:58:56 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.91.9 Chrome/96.0.4664.110 Electron/16.0.8 Safari/537.36
Error
Error message: invalid mac
Stacktrace:
Error: invalid mac
at os (file:///app/lib/tutanota/resources/app.asar/worker.js:1:38652)
at Wu.decrypt (file:///app/lib/tutanota/resources/app.asar/worker.js:12:130667)
at file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:5590
at C.handleMessage (file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:7598)
at file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:6851
at _worker.onmessage (file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:6431)
```

I have checked that I can normally log in via browser and Android app. I disabled all firewalls etc.

I'm using the Flathub version of Tutanota Desktop 3.91.9 on my Ubuntu 20.04 LTS (GNOME Shell, Linux Kernel 5.13.0-28-generic).

Possibly related to #3111 and https://www.reddit.com/r/tutanota/comments/snq0hf/an_unexpected_error_occurred_on_tutanota_desktop/

**Comment by charlag** [comment] 2022-02-09 10:44
Duplicate of #3875

We are testing the fix and we will release it very shortly.

**Closed by charlag** 2022-02-09 10:44 UTC
Labels: bug, desktop
