### ISSUE TITLE
Attached pdf file close mail 

### ISSUE THREAD

**Issue by JlNiko** [tutao/tutanota#4013] opened 2022-04-06 10:08 UTC
Hello,
We are trying to open attached pdf file with the browser firefox when the setting "open automaticly pdf file in firefox" is selected , but the pdf file is opened in the smae window.
Is there a way that the file will be opened in a different tab? Because as that, when we click on the return botton, the session is closed.

Thank you

**Comment by charlag** [comment] 2022-04-06 10:51
Firefox broke it, we are about to release a version that works around it
duplicate of #3983

**Closed by charlag** 2022-04-06 10:51 UTC
Labels: bug
