### ISSUE TITLE
Draft not saved when exiting app

### ISSUE THREAD

**Issue by LewisMichaelHarold** [tutao/tutanota#3971] opened 2022-03-17 09:07 UTC
When you write an email and then leave the app, the app locks itself and your draft doesn't get saved. You then have to login again and re-type your whole email.

**Comment by charlag** [comment] 2022-03-17 09:46
We don't have a chance to save a draft at that point. Some sort of a local auto-save will be needed to be implemented.
I will close this for now as this is not a bug but a refined issue will be opened at the later point.

**Closed by charlag** 2022-03-17 09:46 UTC
