### ISSUE TITLE
Attachment popup window is misplaced

### ISSUE THREAD

**Issue by Alcidauk** [tutao/tutanota#6101] opened 2023-11-07 16:36 UTC
**Bug in mobile app**

**Describe the bug**
When opening a mail with several attachments, if two of them have a small name, they stand on the same line.
But this induce opening attachment actions popover is misplaced and we can't select every options.

**To Reproduce**
1. Send a mail with two or more attanchment to your inbox, with short names,
2. Receive the mail and open it
3. On the second attachment, click on the down arrow
4. See the window which is cropped on the right

**Expected behavior**

The opening popover should entirely be shown on the screen.

**Screenshots**

![1699374938738](https://github.com/tutao/tutanota/assets/1180849/a9c89642-e1b7-4486-b02b-ab3a8871731f)

**Smartphone (please complete the following information):**
 - Device: Samsung a5 2017
 - OS: LineageOs
 - Version: 18.1 (android 11)

**Additional context**

Tutanota version : 3.118.22

**Comment by charlag** [comment] 2023-11-07 17:01
Duplicate of #5919

**Closed by charlag** 2023-11-07 17:01 UTC
Labels: bug

**Comment by Alcidauk** [comment] 2023-11-07 17:11
Sorry for the duplication, did not find #5919 after a (obviously too quick) search.
