### ISSUE TITLE
Missing icons when showing team emails

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#2876] opened 2021-03-26 07:42 UTC
We do not show buttons for moving/replying/forwarding/... for mails marked as `Tutanota Team` (and as newsletter i suppose), as reported on [reddit](https://www.reddit.com/r/tutanota/comments/md20mg/please_reallow_full_array_of_operations_on/).

![Screenshot from 2021-03-26 08-40-38](https://user-images.githubusercontent.com/6842104/112598647-2b79fa80-8e0f-11eb-9ba9-3295a4a093e5.png)
![Screenshot from 2021-03-26 08-39-37](https://user-images.githubusercontent.com/6842104/112598650-2c129100-8e0f-11eb-992f-675b79ef4599.png)

We should at least show the move button in case some people would like to organize their mails. They do it anyways by using drag-n-drop.

**Comment by charlag** [comment] 2021-03-26 08:05
Duplicate of #2769

**Closed by charlag** 2021-03-26 08:05 UTC
