### ISSUE TITLE
Events with complex recurrence patterns are not supported

### ISSUE THREAD

**Issue by R-VdP** [tutao/tutanota#5721] opened 2023-08-02 21:50 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web and mobile apps**

When I receive an event for a recurring meeting on specific days only (like "every week, all weekdays" or "every week, Mon, Tue and Fri"), then only the first of those shows up in the calendar (like every Monday, but not the other days).

This does not happen for other calendar systems (e.g. google calendar).

**To Reproduce**

Import this ICS that defines a weekly recurring meeting on Mondays, Wednesdays and Fridays:
```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Europe/Paris
X-LIC-LOCATION:Europe/Paris
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Europe/Paris:20230628T170000
DTEND;TZID=Europe/Paris:20230628T175000
RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=FR,MO,WE
DTSTAMP:20230802T153102Z
ORGANIZER;CN=john@example.com:mailto:john@example.com
UID:0280k9sae71c6mom1p2ja5rem6_R20230628T150000@google.com
X-GOOGLE-CONFERENCE:https://meet.google.com/xxx
X-MICROSOFT-CDO-OWNERAPPTID:-1834798661
CREATED:20220211T110649Z
DESCRIPTION:xx
LAST-MODIFIED:20230802T152958Z
LOCATION:xx
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:xx
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

And observe that the meeting is only shown on Mondays

**Expected behavior**

The meeting should be shown every Monday, Wednesday and Friday.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 115.0.3

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 13
 - Tutanota app from play store

**Comment by vitoreiji** [comment] 2023-08-03 06:39
Duplicate of #1666

**Closed by vitoreiji** 2023-08-03 06:39 UTC
Labels: bug
