### ISSUE TITLE
Error on open 3.82.17  Error message: The name org.freedesktop.secrets was not provided by any .service files

### ISSUE THREAD

**Issue by bkmo** [tutao/tutanota#2928] opened 2021-04-09 20:43 UTC
Upon opening the recent update (3.82.17) with the Linux Appimage or unpacked version there is an error. 
Error message: The name org.freedesktop.secrets was not provided by any .service files
App seems to function normally ignoring the error.  This is on Arch with KDE Desktop.

**Comment by aliencoder-ni** [comment] 2021-04-10 08:23
This is the error I get:
the monkey has been patched
version:   3.82.17
(node:4438) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

(tutanota-desktop:4438): Gtk-WARNING **: 10:19:38.330: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
[2021-04-10T08:19:38.455Z] alarm storage failed to initialize: [Error: The name org.freedesktop.secrets was not provided by any .service files]
[2021-04-10T08:19:38.457Z] Could not load config [Error: The name org.freedesktop.secrets was not provided by any .service files]

Operating System: Manjaro Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.10-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × AMD Ryzen 3 3200G with Radeon Vega Graphics
Memory: 13,7 GiB of RAM
Graphics Processor: AMD Radeon™ Vega 8 Graphics

**Comment by bkmo** [comment] 2021-04-10 18:03
It seems that KDE does not supply org.freedesktop.secrets .service, it is supplied by Gnome keyring, but not KDE Wallet. This should not be a requirement on all desktops.

**Comment by charlag** [comment] 2021-04-10 18:17
Libsecret was co-authored by KDE Wallet and GNOME keyring, it's just that Wallet is not maintained anymore.
You need libsecret on your machine, that's all.

**Comment by bkmo** [comment] 2021-04-11 01:46
Libsecret is installed on my Arch setup. The problem is that it does not include  the optional dependency org.freedesktop secrets. If you install this it pulls in gnome-keyring. This is something that should not be needed on KDE. This must be an electron issue as chrome/chromium works fine with kdewallet.

**Comment by charlag** [comment] 2021-04-12 07:13
Duplicate of #2929 
I'll continue ver there

**Comment by jowlo** [comment] 2021-04-12 07:15
@charlag Ehm, i don't think so, this looks different (one comment of #2929 was a duplicate of this)...

**Comment by charlag** [comment] 2021-04-12 07:18
It's not rendering issue, it also says "Could not load config" and that is a real problem. We didn't change anything about rendering, we encrypt config now.

**Comment by jowlo** [comment] 2021-04-12 07:18
Oh no, i just reread the error in #2929 and you are right, there also is the `libsecrets` problem.
Sorry @aliencoder-ni for the confusion...

**Closed** 2021-04-12 07:19 UTC
Labels: bug, desktop, duplicate

**Comment by matthk0309** [comment] 2021-04-12 16:44
The same with me. Debian 9 with KDE-Plasma 5.8.6 KDE-Framework 5.28.0. After the last update the desktop client does not start anymore.


``Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
the monkey has been patched
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
version:   3.82.17
(node:7083) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files

(tutanota-desktop:7083): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(tutanota-desktop:7083): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(tutanota-desktop:7083): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
[2021-04-12T16:43:43.420Z] alarm storage failed to initialize: [Error: The name org.freedesktop.secrets was not provided by any .service files]
[2021-04-12T16:43:43.421Z] Could not load config [Error: The name org.freedesktop.secrets was not provided by any .service files]
