### ISSUE TITLE
Blank screen after installing via Flatpak

### ISSUE THREAD

**Issue by HannanAkbar** [tutao/tutanota#1393] opened 2019-07-28 23:07 UTC
Desktop app is giving a blank white screen after fresh installation via Flatpak. Tried restarting a couple of times. Does it require any special permissions?

Running Debian/Deepin

**Comment by charlag** [comment] 2019-07-29 07:08
Flatpak is in preview state. After closing the window and opening another one the second window does not work and we can't find out why.
Duplicate of #1257

**Closed by charlag** 2019-07-29 07:08 UTC
Labels: bug, desktop
