### ISSUE TITLE
System Tray Icon not appearing in 3.72 - Linux Mint 9.3 Cinnamon

### ISSUE THREAD

**Issue by dosenfleisch** [tutao/tutanota#2028] opened 2020-05-03 13:21 UTC
This is straight forward.  I was precluded today from opening the app because the version I had was no longer supported.  I had to update to 3.72.  With that, the systray icon no longer appears.  This was confirmed by rebuilds to two other machines that I downloaded 3.72 to and the same problem was present.

**Comment by charlag** [comment] 2020-05-04 07:13
Duplicate of #1829

**Closed by charlag** 2020-05-04 07:13 UTC
Labels: bug, desktop
