### ISSUE TITLE
No confirmation dialog when removing participant from calendar

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1635] opened 2019-11-22 14:21 UTC

**Comment by vitoreiji** [comment] 2019-11-22 14:34
Are you sure you can remove *yourself*? I could not reproduce this.

But yes, removing others has no confirmation dialog. Do you really think we need one?

**Comment by armhub** [comment] 2019-11-22 15:49
Yes, you can remove yourself if the calendar was shared with you.

I think we definitely need a confirmation dialog. Removing someone from a group is a major operation which will also e.g. include deleting your local search index for that group, so we should make sure this does not happen by accident.

**Comment by charlag** [comment] 2019-11-25 15:35
fixed by c8ba684

**Comment by mpfau** [comment] 2019-11-26 08:18
There is still no confirmation dialog if you remove yourself from the calendar. The confirmation dialog when removing a participant is displayed correctly, now.

**Comment by vitoreiji** [comment] 2019-11-26 10:08
Not quite, the confirmation dialog is displayed when removing an invitation, but not a participant.

**Closed** 2019-11-26 11:03 UTC
Labels: dev bug
