### ISSUE TITLE
Calender: date changes if set to full-time

### ISSUE THREAD

**Issue by killathe** [tutao/tutanota#1818] opened 2020-02-13 12:17 UTC
**Bug in mobile app**
Calender date changes when setting event to full-time.

**Describe the bug**
I created a calender entry for 28.02.2020 at 12 o'clock. Later I changed it to full-time (ganztags). After saving the event, the entry has magically "switched" to 27.02.2020. (The Desktop client however still shows the right date.)

**To Reproduce**
1. Go to calender.
2. Click on 28.02.2020, 12:00 and create a new event.
3. Save event.
4. Change event to full-time, save it.
5. See error: Event changed date to 27.02.2020.

**Expected behavior**
Entry stays at date 28.02.

**Smartphone (please complete the following information):**
 - OS: Android
 - Version [9, 10]

**Comment by charlag** [comment] 2020-02-13 12:18
Duplicate of #1808

**Closed by charlag** 2020-02-13 12:18 UTC
Labels: bug
