### ISSUE TITLE
iOS app: saved login password not recognized

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1226] opened 2019-04-11 13:06 UTC
This occurs only in the iOS app, but not in mobile Safari. iOS 12.2

1. Save password by a password manager
2. Open Tutanota login in the mobile app
3. Select saved password
4. Try to login -> Invalid login message
Additionally, passwords overlap if typing in another password.

**Comment by charlag** [comment] 2019-04-23 08:50
Duplicate of #734

**Closed by charlag** 2019-04-23 08:50 UTC
Labels: bug
