### ISSUE TITLE
Desktop app doubles the number of attachments inserted if you leave the mail as a draft

### ISSUE THREAD

**Issue by prentakias** [tutao/tutanota#3347] opened 2021-08-05 06:34 UTC
Desktop app doubles the number of attachments inserted if you leave the mail as a draft

Tutanota Desktop: v3.85.6
Windows 10 Pro
Version: 20H2
Build: 9042.1110

**Comment by johnbotris** [comment] 2021-08-05 06:58
Duplicate of #3310

**Closed by johnbotris** 2021-08-05 06:58 UTC
Labels: bug, desktop

**Comment by prentakias** [comment] 2021-08-06 09:30
> Duplicate of #3310

Thank you. I will check the list of issues more closely in the future
