### ISSUE TITLE
calendar event pop-up persists after deleting event

### ISSUE THREAD

**Issue by kib42** [tutao/tutanota#7127] opened 2024-06-24 10:48 UTC
After deleting a calendar event, the event's pop-up persists until clicked away.

Tested on mobile, web and desktop
Version: v230.240603.0

See screenshot:

![image](https://github.com/tutao/tutanota/assets/104761667/e42052f7-1d25-40e7-8278-d43e1e7252e3)

**Comment by rezbyte** [comment] 2024-06-25 07:10
Thanks for the report.
This will be fixed in the next release by #7110.
Duplicate of #7107.

**Closed by rezbyte** 2024-06-25 07:10 UTC
Labels: bug, topic: calendar
