### ISSUE TITLE
Calendar: description field does not soft-wrap

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1716] opened 2020-01-02 09:52 UTC
When the text in the description field becomes long, the text is not soft-wrapped but rather becomes scrollable. I think we need to break text on word in such case.

**Comment by charlag** [comment] 2020-01-06 15:02
I've found out that we manually set pre-wrap and we set the heigh to the number of newlines. There might be some corner cases where we wanted this horizontal scroll behaviour instead of soft-wrapping. We probably should change it if we don't want this behaviour anywhere or we should add it as a parameter.

**Comment by charlag** [comment] 2020-03-10 14:03
It *is* possible to wrap manually though so I'm not sure if we should change this.

**Comment by ganthern** [comment] 2022-08-03 16:28
duplicate of https://github.com/tutao/tutanota/issues/1336

**Closed by ganthern** 2022-08-03 16:28 UTC
Labels: bug
