### ISSUE TITLE
Calendar work day

### ISSUE THREAD

**Issue by 2E0PGS** [tutao/tutanota#1737] opened 2020-01-10 22:03 UTC
**Bug in mobile app && Bug in web app**

**Describe the bug**

The calendar does not allow me to specify reoccurring events for work days (Monday - Friday). 

**To Reproduce**

Click on calendar, select recurring event, select daily.

**Expected behavior**

Option for days in week to repeat on. e.g. Mon - Fri.

I want to have a event for my work days and not have it occur on the weekend.

I see no option for this in the web app or mobile apps.

**Comment by 2E0PGS** [comment] 2020-01-10 22:34
#### Screenshot 

![image](https://user-images.githubusercontent.com/15659301/72191176-51c59d00-33f9-11ea-96fb-790cd3159f4d.png)

**Comment by charlag** [comment] 2020-01-13 15:18
Duplicate of #1666

**Closed by charlag** 2020-01-13 15:18 UTC
Labels: bug
