### ISSUE TITLE
Incorrect display of multiple day event

### ISSUE THREAD

**Issue by ctrlvd** [tutao/tutanota#5839] opened 2023-09-01 15:16 UTC
When creating a calendar event between years that is 14 days or less, the days in the new year are not displayed as part of the event.

1. Go to Calendar.
2. Create an event between years. The event should be 14 days or less.
3. Days in the new year are not displayed as part of the event.

![Screenshot from 2023-09-01 17-05-00](https://github.com/tutao/tutanota/assets/124799622/78bceb48-69f1-4e80-8f4e-ce0e7ab87deb)
![Screenshot from 2023-09-01 17-04-40](https://github.com/tutao/tutanota/assets/124799622/65c29c62-2993-44ea-9441-556a4dd68950)

Reproduced on web, Desktop, and Android app.

**Comment by ganthern** [comment] 2023-09-19 09:30
should be a duplicate of #5896 (or rather, that one is a dupe of this one)

**Closed by ganthern** 2023-09-19 09:30 UTC
Labels: bug, topic:calendar, ui
