### ISSUE TITLE
Login stalls on iOS 15.1

### ISSUE THREAD

**Issue by Spacedoggie** [tutao/tutanota#6169] opened 2023-11-16 12:28 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Endless delay after tapping "Log in"

**To Reproduce**
1. Install v.3.118.30 on an iPhone SE running iOS 15.1
2. Enter valid email address and username
3. Tap "Log in"
4. App says "Logging in...." Arrows rotate endlessly.

**Expected behavior**
The same credentials, when entered on an iPhone 8 running iOS 16.7.2, successfully log in.

**Screenshots**
![IMG_1217_2](https://github.com/tutao/tutanota/assets/151033050/ad58ed0d-af63-467b-b8cd-ac2abdcc2f8a)
![IMG_1218](https://github.com/tutao/tutanota/assets/151033050/ef631c82-40b4-4b03-8fe5-41349c6d4920)

**Smartphone (please complete the following information):**
 - Device: iPhone SE MHG43LL/A
 - OS: iOS 15.1
 - Version: 15.1 (19B74)

**Comment by charlag** [comment] 2023-11-16 12:31
Duplicate of  #6056

**Closed by charlag** 2023-11-16 12:31 UTC
Labels: bug, state:wontfix

**Comment by Spacedoggie** [comment] 2023-11-16 12:35
I apologize for the duplicate post - I did see #6056 but I didn't read it all the way through. Thanks, that answers my question!
