### ISSUE TITLE
cannot switch calendar view on mobile apps with three column layout

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#6337] opened 2023-12-29 13:54 UTC
This issue happens on mobile screens with enough resolution to use the three column layout.
To reproduce:

1. open "Responsive design mode" in dev tools
2. set resolution to 1920x1080 for example
3. use a mobile User Agent, like `Mozilla/5.0 (iPad; CPU OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1`
4. open calendar
5. see error

![image](https://github.com/tutao/tutanota/assets/104761667/609562c3-8e38-4f50-8f6b-20a11202a1aa)

### Test notes

- [x] On a phone, ensure the view/day buttons are present like so: ![image](https://github.com/tutao/tutanota/assets/104824185/6a5289dc-8f39-41d9-a318-c96576dd67be)
- [x] On a tablet with a screen large enough to display Agenda view with three columns (or with developer tools with a mobile user agent), ensure the view/day buttons are present even in landscape mode

**Comment by rezbyte** [comment] 2024-01-15 14:05
The view/day buttons are not visible on three day view on tablet. I tested it using Chromes dev tools.
![Screenshot from 2024-01-15 15-02-41(1)](https://github.com/tutao/tutanota/assets/48037381/c67c43a7-d1ba-4b97-b7dd-92629d4a1445)

**Comment by paw-hub** [comment] 2024-01-16 08:58
It seems all of the changes got reverted for some reason.

I'll just make another branch and pull request.

**Comment by paw-hub** [comment] 2024-01-16 09:06
On second look, it never actually got merged into master but into some integration branch. The code is right there, and when I checked it out, it worked as intended.

Please note that you will need to load the web client with the device toolbar already open in order to simulate a mobile device.

![image](https://github.com/tutao/tutanota/assets/104824185/138dc490-bb30-4064-931e-1b5c975279ed)

**Comment by rezbyte** [comment] 2024-01-16 14:54
> On second look, it never actually got merged into master but into some integration branch. The code is right there, and when I checked it out, it worked as intended.
> 
> Please note that you will need to load the web client with the device toolbar already open in order to simulate a mobile device.
> 
> ![image](https://private-user-images.githubusercontent.com/104824185/296990403-138dc490-bb30-4064-931e-1b5c975279ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTcwMzIsIm5iZiI6MTcwNTQxNjczMiwicGF0aCI6Ii8xMDQ4MjQxODUvMjk2OTkwNDAzLTEzOGRjNDkwLWJiMzAtNDA2NC05MzFlLTFiNWM5NzUyNzllZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxNDUyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDAzMWYyZDk5N2ZlN2ZhNjM5NjkyNDFiN2I2NmRiNzliMTY1NzFkOGI0OGRiOGJmMDcwOTM2NWUxNGM3MjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jLoSGI-mhv8GOCPw9rgVMIaPYBFDrwiTxJ-a9NhChsI)

I just tried this out and can confirm loaded the client with the mobile simulation on fixed it. I have changed the state tag.

**Closed** 2024-01-18 10:22 UTC
Labels: bug, state:tested, state:done, topic:calendar, ui
