### ISSUE TITLE
Icon not showing up - Linux AppImage

### ISSUE THREAD

**Issue by saraneth0o** [tutao/tutanota#1022] opened 2019-01-12 01:20 UTC
When I integrate the AppImage the Menu icon for it doesn't show up. It is just invisible. If I open the app with it the icon on the taskbar is also invisible. If I open directly with the AppImage the icon is there.

I found a way to add the icon after some troubleshooting though. In the '`appimagekit-tutanota-desktop.desktop`' file I changed the 'Icon=' field from '`Icon=appimagekit-tutanota-desktop`' to '`Icon=/home/username/.local/share/icons/hicolor/0x0/apps/appimagekit-tutanota-desktop.png`'.

That is the default icon that the AppImage makes but for some reason doesn't link to it properly.

I saw that there were similar issues here, but they have been closed and this is still a problem.

**Comment by ganthern** [comment] 2019-01-14 07:33
duplicate of https://github.com/tutao/tutanota/issues/981 which will be part of the next release.

**Closed by ganthern** 2019-01-14 07:33 UTC

**Comment by saraneth0o** [comment] 2019-01-14 07:34
Alright. Thanks
