### ISSUE TITLE
Email notifications from logged out account

### ISSUE THREAD

**Issue by starsep** [tutao/tutanota#4471] opened 2022-08-06 09:26 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
I am getting new email notifications from the account I logged out.

**To Reproduce**
1. Log in to multiple email accounts
2. Log out to one of them
3. Send email to this account

**Expected behavior**
Email notification is not displayed

**Comment by ganthern** [comment] 2022-08-08 07:16
Hey there, 

we have some users that don't save their credentials in the desktop app and still want to see the notifications. You can unlink your device from the notifications by going to Settings -> Email -> Notifications and selecting "Delete" on the row that says "This device". Then log out & delete your credentials.

I'm going to leave this open because the behaviour is poorly specified and needs some work when we look at credentials management in the desktop apps again.

**Comment by charlag** [comment] 2022-08-23 06:15
As this is intended behavior at the moment I will close it, we will open another issue to track credentials logic changes.

**Closed by charlag** 2022-08-23 06:15 UTC
Labels: bug
