### ISSUE TITLE
Error when changing existing whitelabel to 'manual'

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#3129] opened 2021-05-27 14:33 UTC
Setup whitelabel domain, then press Edit and change certificate type from 'automatic' to 'manual'. 
Throws an empty Error message and also breaks the client.

We should prevent the user from changing it to 'manual' after a whitelabel domain has been setup

**Comment by armhub** [comment] 2021-05-27 19:03
Duplicate of #2554.

**Closed by armhub** 2021-05-27 19:03 UTC
Labels: bug
