### ISSUE TITLE
Lock App With PIN/Any "Password"

### ISSUE THREAD

**Issue by trpWWW** [tutao/tutanota#1837] opened 2020-02-21 04:40 UTC
A similar feature request was added almost 2 years ago, still no updates.
Using encrypted email and having it decrypted 24 hours a day on your phone is very counter productive.

**There is no reason at all to use Tutanota** as long as this feature does not exist (in my opinion).

Many other apps already have an option to lock them using some sort of password, I would be very grateful if you could add this feature.
If you do, please let us use a PIN code longer than 4 numbers, maybe even a password, fingerprint or swipe pattern.

Also, make sure the app actually re-encrypts the inbox, unlike some other apps where you can just open the phones file system and still access the contents.

**Comment by charlag** [comment] 2020-02-21 09:27
Duplicate of  #545

**Closed by charlag** 2020-02-21 09:27 UTC
Labels: bug
