### ISSUE TITLE
Failed to map shared segment

### ISSUE THREAD

**Issue by jander049** [tutao/tutanota#1618] opened 2019-11-11 17:25 UTC
When I try to launch the appimage I get the following error:
/tmp/.org.chromium.Chromium.z5bAif: failed to map segment from shared object

**To Reproduce**
This started happening this morning and now I see the error every time I try to start from the command line. When I click on the AppImage itself to launch it just fails silently.

**Desktop (please complete the following information):**
 - OS: Debian Testing
 - Desktop Environment, if applicable (on Linux)
 - XFCE 4.14

**Additional context**
I'm not sure but this could be because my /tmp directory is mounted with nosuid,noexec,nosuid permissions but it hasn't been a problem until now.

User namespaces are also disable on my system.

**Comment by charlag** [comment] 2019-11-11 17:26
Hi
> User namespaces are also disable on my system.
Did you see #1565 ? Can it be it?
I'm also not sure how it should run with noexec

**Comment by jander049** [comment] 2019-11-11 17:28
I have to use the no-sandbox option to run it and have been without issue until nown

**Comment by charlag** [comment] 2019-11-11 17:44
We have updated Electron few versions ago already and enabled sandbox there. 
As far as I understand it worked for you and it's a duplicate of #1565.
You can apply any of the solutions (suid binary, user namespaces or no sandbox).

**Comment by jander049** [comment] 2019-11-11 18:24
It doesn't start for me even with the no sandbox option now, it used to up until this morning though. This is the full error I see:

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/user/1000/.org.chromium.Chromium.N6ybiE: failed to map segment from shared object
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/tmp/user/1000/.mount_tutanoCpaaxi/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)

**Comment by charlag** [comment] 2019-11-12 08:53
Okay, it's a different problem. Can you try setting `TMPDIR` as described here https://github.com/balena-io/etcher/issues/1699 or here https://github.com/balena-io-modules/drivelist/pull/209
?

**Comment by jander049** [comment] 2019-11-12 18:12
Yes this worked for me

TMPDIR=$XDG_RUNTIME_DIR /path/to/appimage

**Comment by charlag** [comment] 2019-11-13 08:58
I wonder if we could fix it on our side somewhere. Judging by the stacktrace it seems like it's inside keytar somewhere.

**Comment by charlag** [comment] 2020-02-18 18:52
@jander049 AppImage devs at https://github.com/AppImage/AppImageKit/issues/1021#issuecomment-587271417 asked for an image, maybe you could make one for them

**Closed by charlag** 2020-02-18 18:52 UTC
Labels: bug, desktop
