### ISSUE TITLE
Error: No group with grouId

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#5885] opened 2023-09-14 14:37 UTC
When creating a contact list with entries, this error occurs:

Client: linux
Type: PAID
Tutanota version: 3.118.5
Timestamp (UTC): Tue, 12 Sep 2023 08:07:25 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop-test/3.118.5 Chrome/116.0.5845.97 Electron/26.1.0 Safari/537.36
Error
Error message: No group with groupId Ne7Q_1-----0 found!
Stacktrace:
Error: No group with groupId Ne7Q_1-----0 found!
at La.getMembership (asset://app/worker.js:12:46779)
at asset://app/worker.js:12:46655
at v (asset://app/common-min-400ee161.js:1:15371)
at La.getGroupKey (asset://app/worker.js:12:46599)
at ji.setNewOwnerEncSessionKey (asset://app/worker.js:12:7521)
at As.setup (asset://app/worker.js:1:27434)

**Comment by charlag** [comment] 2023-09-14 15:30
Duplicate of #5875

**Closed by charlag** 2023-09-14 15:30 UTC
Labels: bug
