### ISSUE TITLE
Weird string appears when uploading multiple contacts as .vcf file

### ISSUE THREAD

**Issue by webverbinder** [tutao/tutanota#1712] opened 2020-01-01 20:03 UTC
I uploaded a .vcf file with over 200 contacts (including contact name, mobile number, email and birthday). It seems that all contact names having an umlaut (ä,ü,ö) get a weird string in the first name field.

Example weird string looks like this: '=4D=6F=72=69=74=7A'
Maybe this is some kind of encoding?

- Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
- Ubuntu 18.04.3 LTS Operating System

**Comment by charlag** [comment] 2020-01-02 11:17
Hi
There's a problem with encoding currently
duplicate of #1513

**Closed by charlag** 2020-01-02 11:17 UTC
Labels: bug
