### ISSUE TITLE
sqlite is compiled against glibc that is too new

### ISSUE THREAD

**Issue by locomotif18** [tutao/tutanota#4730] opened 2022-11-10 20:09 UTC
Good afternoon,
   after recently upgrading to V.103.3 desktop client on my Debian Linux 10 workstation, I received the following error message:

******************
Feedback v3.103.3 - Error - UNKNOWN - linux

 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.103.3
 Timestamp (UTC): Thu, 10 Nov 2022 19:53:38 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.103.3 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
Error
 Error message: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_tutanoMDnv1J/resources/app.asar.unpacked/desktop/better_sqlite3.node)
Stacktrace: 
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_tutanoMDnv1J/resources/app.asar.unpacked/desktop/better_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new hm (/tmp/.mount_tutanoMDnv1J/resources/app.asar/desktop/DesktopMain.js:13:130526)
    at vm.openDb (/tmp/.mount_tutanoMDnv1J/resources/app.asar/desktop/DesktopMain.js:13:136061)
*****************

**Comment by locomotif18** [comment] 2022-11-14 20:12
Charlag, your deduction was correct.  I ran _ldd --version_ to find the the version of glibc. The system returned:  ldd (Debian GLIBC 2.28-10+deb10u2) 2.28

**Comment by charlag** [comment] 2023-02-10 08:58
duplicate of #4349

**Closed by charlag** 2023-02-10 08:58 UTC
Labels: bug, desktop
