### ISSUE TITLE
PRIVACY BUG - Mobile app connects to GOOGLE!

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [tutao/tutanota#6934] opened 2024-05-13 22:43 UTC
**Bug in mobile app**
Mobile app connects to GOOGLE:
android.googleapis.com = ajax.googleapis.com on :443

**To Reproduce**
install app from fdroid (de.tutao.tutanota)
monitor network usage with netguard => even before logging in, the app attempts connections to google

**Expected behavior**
no connection to GOOGLE

**Smartphone (please complete the following information):**
 - Device: OP7
 - OS: android 12
 - Tuta Version 227.240502.0

**Comment by rezbyte** [comment] 2024-05-16 08:40
Hi @Uj947nXmRqV2nRaWshKtHzTvckUUpD,
Thank you for your report.

We are investigating the cause of this connection and would like to ask you some questions. What keyboard (GBoard etc.) are you using on your device? Are you using the stock version of Android included on your device (OxygenOS) or a custom distribution?

Kind regards,
rezbyte

**Comment by kib42** [comment] 2024-05-24 08:25
we are not able to reproduce this connection to google's servers. The issue appears to be related to your specific device or setup. 

Please contact our support with more details so we could investigate this further. Closing as not planned.

**Closed by kib42** 2024-05-24 08:25 UTC
Labels: bug
