### ISSUE TITLE
[iOS] cursor cannot be moved to edit the text an event title

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1453] opened 2019-08-30 11:11 UTC
When typing a new event in the calendar, the cursor cannot be moved to edit the text of the title. Attempts to do so added text or deletes text at the end of the title. 

The same happens when editing a folder name but input fields in the mail editor are fine.

**Comment by ganthern** [comment] 2022-08-02 12:25
Can't reproduce in 3.98.17 (folder and event title behave the same as ie the subject line in the mail editor). I'll close this. Maybe we can reopen it if there's a detailed repro.

**Closed by ganthern** 2022-08-02 12:25 UTC
Labels: bug, ios
