### ISSUE TITLE
[desktop] The taskbar icon is very dark

### ISSUE THREAD

**Issue by Strappazzon** [tutao/tutanota#1105] opened 2019-02-10 14:37 UTC
It looks like that the behaviour reported in this issue https://github.com/tutao/tutanota/issues/1001 is back.

The taskbar icon is very dark, as well as the icon that appears inside the Properties dialog.

## Screenshots
![Taskbar](https://user-images.githubusercontent.com/19752093/52534980-d373fd00-2d48-11e9-9b05-ea51eebc3b1c.png)

![Properties](https://user-images.githubusercontent.com/19752093/52534978-d373fd00-2d48-11e9-8c03-1fa6ec70ef7f.png)

## Desktop
 - OS: Windows 10 Enterprise 1809 Build 17763.292
 - Version: 3.47.3.261

**Comment by ganthern** [comment] 2019-03-06 10:28
This is still happening, and I still don't know why :roll_eyes:

**Comment by biscober** [comment] 2019-05-20 19:24
This seems to be related to display DPI.  If my DPI scaling is set to either 100% or 225% or above, it's fine.  If it's set to 125%, 150%, 175%, or 200% then I have the mostly black icon.  Since I use a 4k monitor my display DPI is set to 150% so I always see the black icon.  Hope this information helps solve the issue.

**Comment by charlag** [comment] 2019-05-21 13:23
@biscober thanks for the info! It sounds like a good lead but on our test device it is also reproducible but that machine doesn't use DPI scaling. We will double check, thanks in any case!

**Comment by ganthern** [comment] 2020-01-28 10:11
closing for now, please comment if this still occurs

**Closed by ganthern** 2020-01-28 10:11 UTC
Labels: bug, desktop

**Comment by Strappazzon** [comment] 2020-01-28 14:18
![](https://user-images.githubusercontent.com/19752093/73270774-a9c51780-41df-11ea-95c9-a60629db5ec8.png)

Tutanota Desktop version 3.66.7.747
Windows 10 Enterprise LTSC 1809 Build 17763.1012
