### ISSUE TITLE
Set the app as default email client on iOS

### ISSUE THREAD

**Issue by vilmotz** [tutao/tutanota#2452] opened 2020-11-23 22:06 UTC
This feature would be perfect by Tutanota also😉
![PNG-Bild](https://user-images.githubusercontent.com/69350416/100020566-4fd1b600-2de0-11eb-81c1-72b2d32c36c5.png)

**Comment by bedhub** [comment] 2020-11-24 12:06
duplicate of #2294

**Closed by bedhub** 2020-11-24 12:06 UTC
Labels: duplicate
