### ISSUE TITLE
The end date must not be after start date. - Search form

### ISSUE THREAD

**Issue by EliasGabrielsson** [tutao/tutanota#660] opened 2018-10-09 10:15 UTC
Tried to search and set fields according to this image below.
Noticed that my account where created after search date if that have something to to with it.

![enddate](https://user-images.githubusercontent.com/4204655/46662803-aeb22200-cbbc-11e8-8599-45ea6c2e57e3.jpeg)

```
Client: Browser
Tutanota version: 3.38.1
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
```

**Comment by charlag** [comment] 2018-10-09 14:43
Sorry, it is actually the duplicate of this thing:
https://github.com/tutao/tutanota/issues/423
they're... the other way around. Everyone is confused. We will change it soon.

**Closed by charlag** 2018-10-09 14:43 UTC
