### ISSUE TITLE
Add adaptive icon support for android

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#877] opened 2018-12-02 05:25 UTC
Add adaptive icon support for android version

**Comment by charlag** [comment] 2018-12-02 08:48
We would be glad to accept a PR for this

**Comment by Rakleed** [comment] 2019-03-14 21:42
Link: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by charlag** [comment] 2019-09-09 13:34
Duplicate of #1271

**Closed by charlag** 2019-09-09 13:34 UTC
