### ISSUE TITLE
Cannot display mail content

### ISSUE THREAD

**Issue by umg339** [tutao/tutanota#5265] opened 2023-03-14 19:24 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
The android app does not display Mail content. I cannot read any emails. The mail view recently got this collapse/expand button (see link below) but it does not do anything when pressed.

**To Reproduce**
1. Open any E-Mail
2. Click on expand/collapse button (...)
3. Nothing happens

**Expected behavior**
Mail text/content should appear or disappear.

**Screenshots**
[Example](https://imgur.com/a/MbADXr9)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: Lineage OS
 - Version 16.0

**Comment by charlag** [comment] 2023-03-15 08:50
Duplicate of #5221

**Closed by charlag** 2023-03-15 08:50 UTC
Labels: bug
