### ISSUE TITLE
Incomplete notification

### ISSUE THREAD

**Issue by Lolonoumea** [tutao/tutanota#6682] opened 2024-03-08 05:03 UTC
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

[ with translate google ;-) ]
Hello

When I receive a notification of receiving a message on my phone, this notification does not provide any information about the message received. 
I checked if there was a possibility (application settings) so that we could see 1) who sent the message, 2) subject of the message and 3) the first lines of this message.
This additional notification exists on the other email application and is VERY practical because it allows you to adjust its level of responsiveness according to the importance read in the notification

Is this a bug?

Best regards

**To Reproduce**

**Expected behavior**
so that we could see 1) who sent the message, 2) subject of the message and 3) the first lines of this message.

**Screenshots**
![Tuta](https://github.com/tutao/tutanota/assets/162663614/64954a4c-f3fd-4c51-b95a-731140dfc22a)
]

**Smartphone (please complete the following information):**
 - Device: [OPPO CPH2375
 - OS: [Android]
 - Version [13]

**Additional context**

**Comment by rezbyte** [comment] 2024-03-08 07:29
Hi @Lolonoumea,
Thank you for your message.

This is not a bug however, the notifications are currently planned to be expanded with more information. See the [roadmap](https://tuta.com/roadmap) for more information.

(Veuillez excuser les éventuelles fautes de français car il s'agit d'une traduction automatique)
Cher @Lolonoumea,
Nous vous remercions pour votre message.

Il ne s'agit pas d'un bogue, mais il est prévu de compléter les notifications avec davantage d'informations. Voir la [feuille de route](https://tuta.com/roadmap) pour plus d'informations.

Bien à vous.

Duplicate of #6579

**Closed by rezbyte** 2024-03-08 07:29 UTC
Labels: bug
