### ISSUE TITLE
Desktop gets stuck when exporting eml files

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2798] opened 2021-03-04 17:16 UTC
Happening inconsistently, sometimes when exporting on desktop the save file dialog never opens. When this happens, the "send logs" button also stops working. Seems like something is getting stuck in the IPC.

**Comment by bedhub** [comment] 2021-03-12 09:01
duplicate of #2766

**Closed by bedhub** 2021-03-12 09:01 UTC
Labels: bug, desktop, duplicate
