### ISSUE TITLE
Search Results are appearing more than once upon rebuilding search index

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#3317] opened 2021-07-26 11:11 UTC
Occurs in web and desktop app 

**Describe the bug**
When searching for an email search results are duplicated. They can be duplicated multiple times if "enter" is pressed repeatedly.

**To Reproduce**
1. Search for an email
2. While the client searches for the email tap enter a few times
3. The search results are duplicated

**Expected behavior**
The search results should not be duplicated.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version 3.85.6

**Additional context**
A GIF of this error can be found in the comments of issue #1972

**Comment by johnbotris** [comment] 2021-08-02 07:11
duplicate of https://github.com/tutao/tutanota/issues/1972

**Closed by johnbotris** 2021-08-02 07:11 UTC
Labels: bug
