### ISSUE TITLE
Won't work on KDE Plasma Mobile

### ISSUE THREAD

**Issue by Alias001** [tutao/tutanota#4540] opened 2022-08-26 01:25 UTC
I've downloaded the linux app.image from the Tutanota website.  It installs but doesn't run past start screen.  I've tried the flatpack but it's outdated and won't update when attempting to update at login screen.

The desktop linux version will probably not run ideal on a mobile phone, Pinephone Pro.  A build using Mauikit or Krigami would help cross platfrom building that is scalable for more users.

**Comment by charlag** [comment] 2022-08-26 06:43
It doesn't work for you because it's not built for ARM. Same goes for ARM version of flatpak.
Duplicate of #1891

**Closed by charlag** 2022-08-26 06:43 UTC
