### ISSUE TITLE
Getting loged in after canceling lost account access dialog from log in view

### ISSUE THREAD

**Issue by asteintutao** [tutao/tutanota#931] opened 2018-12-12 12:41 UTC
Need stored credentials 
click "more" dropdown on log in page get into Lost account access dialog then cancel it
expected: not being logged in 
practical: getting logged in automaticaly

**Comment by asteintutao** [comment] 2018-12-12 12:45
other dialogs, like canceling the sign up process, behave the same

**Comment by yopfox** [comment] 2023-06-13 08:27
Closed as duplicate of #2549 which has been fixed

**Closed by yopfox** 2023-06-13 08:27 UTC
