### ISSUE TITLE
Calendar date choosing picks previous date

### ISSUE THREAD

**Issue by mlazlo** [tutao/tutanota#2276] opened 2020-09-21 23:11 UTC
If you create or modify calendar event date start or end and choose the date number, let's say today, 21. What gets populated is the 20th. This happens for any date chosen in the future.

**Comment by mlazlo** [comment] 2020-09-26 14:41
Mine is working but if start date for your event should be x, you have to choose x+1 to get x start date

**Comment by charlag** [comment] 2020-10-08 09:49
Duplicate of #2305

**Closed by charlag** 2020-10-08 09:49 UTC
