### ISSUE TITLE
Add an option to view e-mails in cleartext

### ISSUE THREAD

**Issue by OffifialMITX** [tutao/tutanota#1847] opened 2020-02-26 21:00 UTC
I'm glad there is an option to disable images, but I frankly don't trust any kind of parsing, especially in a web(view)-based client.

Could there please be an option to view e-mails in only cleartext? Maybe with a latter addition to automatically clear tags and other content that are not meant to be seen?

**Comment by charlag** [comment] 2020-02-28 16:00
This is a feature request, we don't accept them here
duplicate of #1588

**Closed by charlag** 2020-02-28 16:00 UTC
