### ISSUE TITLE
Emails in the list are not selected correctly after opening and closing an email.

### ISSUE THREAD

**Issue by akosnikhazy** [tutao/tutanota#5851] opened 2023-09-05 15:38 UTC
**Bug in mobile app**

**Describe the bug**
After I open an email and go back to the email list, when I select another email (other than the one I just closed), the previously opened email is also selected.

**To Reproduce**
1. Go to any email list
2. Open an email
3. Close the email
4. Select another email by long pressing
5. Notice that the previously opened email is also selected

**Expected behavior**
When I select an email after closing another only that one should be selected.

**Screenshots**
Here is a video of it happening: https://www.youtube.com/watch?v=siskI68RZqQ

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS16.6
 - Version: Tutanota v3.117.0

**Comment by ne0zepG** [comment] 2023-11-07 14:36
This bug can also be easily reproduced on Android.

Smartphone:
• Samsung S23 Ultra
• OS: Android 14 (One UI 6)
• Version: Tutanota 3.118.22 (F-Droid .apk)

Over two months since this issue has been opened, and not a single acknowledge on this?

**Comment by kibhub** [comment] 2023-11-08 10:53
Already fixed. Duplicate of #5696

**Closed by kibhub** 2023-11-08 10:53 UTC
Labels: bug
