### ISSUE TITLE
Plaint text URLs hyperlinked incorrectly

### ISSUE THREAD

**Issue by odanoburu** [tutao/tutanota#3218] opened 2021-06-25 13:20 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
A URI such as `<https://www.ietf.org/rfc/rfc2396.txt>` enclosed in angle brackets (as permitted by <https://www.ietf.org/rfc/rfc2396.txt>) is hyperlinked to `https://www.ietf.org/rfc/rfc2396.txt>`, not `https://www.ietf.org/rfc/rfc2396.txt`. Per the same RFC, angle brackets may not be a part of a URI (e.g., note how the github markdown parser handles an erroneous link: <<https://www.ietf.org/rfc/rfc2396.txt>>). I'm pretty sure the web client used to handle such URLs correctly in the past.

**To Reproduce**
1. Send a plain text email to your tutanota address with a link to a valid URL enclosed in angle brackets like in the example above.
2. Open the mail client, and click on the link.
3. Note it does not work because of the trailing bracket.
4. Fix the link and refresh the page (now it works!)

**Expected behavior**
The hyperlink should not include the closing angle bracket (or any angle bracket, for that matter)

**Additional context**
The Android mobile app doesn't recognize the link, and does not hyperlink it (which is inconsistent).

**Comment by charlag** [comment] 2021-06-28 07:20
Hi, thanks for report. We changed linkifying implementation recently and we should report this to them.

**Comment by charlag** [comment] 2021-06-28 07:23
They already had an issue about that 6 years ago which was marked as fixed:
https://github.com/Soapbox/linkifyjs/issues/89

so we should probably re-check that on isolated example

**Comment by odanoburu** [comment] 2021-06-28 13:30
They have a demo in their website (<https://soapbox.github.io/linkifyjs/>) and it seems to work there. But it doesn't work on the tutanota web client; I just got a new email today which did not have the proper link. Example emails whose links don't work properly are those from wikipedia's daily article mailing list (<https://lists.wikimedia.org/postorius/lists/daily-article-l.lists.wikimedia.org/>)

**Comment by charlag** [comment] 2022-04-25 07:54
It might be a problem with sanitizer and not with linkifying per se.

**Comment by ganthern** [comment] 2022-08-16 07:30
https://lists.wikimedia.org/hyperkitty/list/daily-article-l@lists.wikimedia.org/thread/UYWBESIQSWX5EDKCZFNER7LVXUIENIY4/

```
The speed of light in  vacuum, denoted c, is a physical constant that is
exactly equal to 299,792,458 metres per second (approximately 186,282
miles per second, or one foot per nanosecond). According to standard
modern physics, visible light and all other electromagnetic radiation
moves at this constant speed in vacuum, and c is the fastest speed at
which matter, energy or any signal carrying information can travel
through space. Ole Rømer first demonstrated in 1676 that light does not
travel instantaneously by studying the apparent motion of Jupiter's moon
Io (diagram shown). In an 1865 paper, James Clerk Maxwell proposed that
light was an electromagnetic wave, and therefore travelled at the speed
c. According to the theory of special relativity, which interrelates
space and time, all observers will measure the speed of light as being
the same, regardless of the inertial reference frame of the observer or
the velocity of the object emitting the light.

Read more: <https://en.wikipedia.org/wiki/Speed_of_light>

_______________________________
Today's selected anniversaries:

1942:

The Holocaust: During the deportation of Jews from Slovakia,
President Jozef Tiso gave a speech describing Jews as "parasites" and
"the eternal enemy".
<https://en.wikipedia.org/wiki/Jozef_Tiso%27s_speech_in_Holi%C4%8D>

1945:

The Stanley Internment Camp in Hong Kong was liberated
following the announcement of the surrender of Japan in World War II.
<https://en.wikipedia.org/wiki/Stanley_Internment_Camp>

1962:

The English rock band the Beatles fired their drummer Pete
Best, replacing him with Ringo Starr (pictured).
<https://en.wikipedia.org/wiki/Ringo_Starr>

1986:

Typhoon Wayne formed over the South China Sea, going on to
become one of the longest-lived tropical cyclones in the north-western
Pacific, lasting 21 days.
<https://en.wikipedia.org/wiki/Typhoon_Wayne_%281986%29>

_____________________________
Wiktionary's word of the day:

catapeltic:
1. (military, weaponry, archaic) Pertaining to a catapult or catapults.
2. (military, weaponry, obsolete, rare) A catapult.
<https://en.wiktionary.org/wiki/catapeltic>

___________________________
Wikiquote quote of the day:

      Take heed of doing irrevocable acts in thy passion, As the
revealing of secrets, which makes thee a bankrupt for society ever
after: neither do such things which done once are done for ever, so that
no bemoaning can amend them. Sampsons hair grew again, but not his eyes:
Time may restore some losses, others are never to be repaird. Wherefore
in thy rage make no Persian decree which cannot be revers'd or repeald;
but rather Polonian laws which (they say) last but three dayes: Do not
in an instant what an age cannot recompence.      
  --Thomas Fuller
<https://en.wikiquote.org/wiki/Thomas_Fuller>
```

Currently results in this HTML:
```
The speed of light in  vacuum, denoted c, is a physical constant that is<br>exactly equal to 299,792,458 metres per second (approximately 186,282<br>miles per second, or one foot per nanosecond). According to standard<br>modern physics, visible light and all other electromagnetic radiation<br>moves at this constant speed in vacuum, and c is the fastest speed at<br>which matter, energy or any signal carrying information can travel<br>through space. Ole Rømer first demonstrated in 1676 that light does not<br>travel instantaneously by studying the apparent motion of Jupiter's moon<br>Io (diagram shown). In an 1865 paper, James Clerk Maxwell proposed that<br>light was an electromagnetic wave, and therefore travelled at the speed<br>c. According to the theory of special relativity, which interrelates<br>space and time, all observers will measure the speed of light as being<br>the same, regardless of the inertial reference frame of the observer or<br>the velocity of the object emitting the light.<br><br>Read more: &lt;<a rel="noopener noreferrer" target="_blank" href="https://en.wikipedia.org/wiki/Speed_of_light>">https://en.wikipedia.org/wiki/Speed_of_light&gt;</a>;<br><br>_______________________________<br>Today's selected anniversaries:<br><br>1942:<br><br>The Holocaust: During the deportation of Jews from Slovakia,<br>President Jozef Tiso gave a speech describing Jews as "parasites" and<br>"the eternal enemy".<br>&lt;<a rel="noopener noreferrer" target="_blank" href="https://en.wikipedia.org/wiki/Jozef_Tiso%27s_speech_in_Holi%C4%8D>">https://en.wikipedia.org/wiki/Jozef_Tiso%27s_speech_in_Holi%C4%8D&gt;</a>;<br><br>1945:<br><br>The Stanley Internment Camp in Hong Kong was liberated<br>following the announcement of the surrender of Japan in World War&nbsp;II.<br>&lt;<a rel="noopener noreferrer" target="_blank" href="https://en.wikipedia.org/wiki/Stanley_Internment_Camp>">https://en.wikipedia.org/wiki/Stanley_Internment_Camp&gt;</a>;<br><br>1962:<br><br>The English rock band the Beatles fired their drummer Pete<br>Best, replacing him with Ringo Starr (pictured).<br>&lt;<a rel="noopener noreferrer" target="_blank" href="https://en.wikipedia.org/wiki/Ringo_Starr>">https://en.wikipedia.org/wiki/Ringo_Starr&gt;</a>;<br><br>1986:<br><br>Typhoon Wayne formed over the South China Sea, going on to<br>become one of the longest-lived tropical cyclones in the north-western<br>Pacific, lasting 21 days.<br>&lt;<a rel="noopener noreferrer" target="_blank" href="https://en.wikipedia.org/wiki/Typhoon_Wayne_%281986%29>">https://en.wikipedia.org/wiki/Typhoon_Wayne_%281986%29&gt;</a>;<br><br>_____________________________<br>Wiktionary's word of the day:<br><br>catapeltic:<br>1. (military, weaponry, archaic) Pertaining to a catapult or catapults.<br>2. (military, weaponry, obsolete, rare) A catapult.<br>&lt;<a rel="noopener noreferrer" target="_blank" href="https://en.wiktionary.org/wiki/catapeltic>">https://en.wiktionary.org/wiki/catapeltic&gt;</a>;<br><br>___________________________<br>Wikiquote quote of the day:<br><br>&nbsp;     Take heed of doing irrevocable acts in thy passion, As the<br>revealing of secrets, which makes thee a bankrupt for society ever<br>after: neither do such things which done once are done for ever, so that<br>no bemoaning can amend them. Sampsons hair grew again, but not his eyes:<br>Time may restore some losses, others are never to be repaird. Wherefore<br>in thy rage make no Persian decree which cannot be revers'd or repeald;<br>but rather Polonian laws which (they say) last but three dayes: Do not<br>in an instant what an age cannot recompence.     &nbsp;<br>  --Thomas Fuller<br>&lt;<a rel="noopener noreferrer" target="_blank" href="https://en.wikiquote.org/wiki/Thomas_Fuller>">https://en.wikiquote.org/wiki/Thomas_Fuller&gt;</a>;<br>_______________________________________________<br>Wikipedia Daily Article mailing list.<br>To unsubscribe write to: <a rel="noopener noreferrer" target="_blank" href="mailto:daily-article-l-leave@lists.wikimedia.org">daily-article-l-leave@lists.wikimedia.org</a><br>Questions or comments? Contact <a rel="noopener noreferrer" target="_blank" href="mailto:dal-feedback@wikimedia.org">dal-feedback@wikimedia.org</a>
```

**Comment by paw-hub** [comment] 2024-02-29 18:47
This doesn't seem to be reproducible anymore or was resolved by some sort past commit. Here's a plain-text email I sent to myself and received on Android.

![image](https://github.com/tutao/tutanota/assets/104824185/60ea9acf-192e-4427-827c-93363a4b5ce0)

I've also tested on the desktop client, and this seems to be fine as well.

**Closed** 2024-03-04 15:34 UTC
Labels: bug
