### ISSUE TITLE
I also can't receive emails from TikTok to create an account

### ISSUE THREAD

**Issue by Samme89** [tutao/tutanota#7264] opened 2024-07-23 22:07 UTC
I am having the same problem. I created all of the above spam rules and tried again to sign up for a tiktok account and I still can't receive the tiktok email with the code to confirm my email address, so I'm unable to create a tiktok account. Also, when I go to Rejected emails, nothing shows up. Can you help with this situation?

_Originally posted by @Samme89 in https://github.com/tutao/tutanota/issues/7002#issuecomment-2246392492_

**Comment by rezbyte** [comment] 2024-07-24 07:41
Hi @Samme89,
I am sorry to hear about your issues with receiving emails from TikTok.

In order for us to better keep track of problems, we would ask you to avoid duplicating issues. Feel free to leave a comment on the original issue as you have done however. We will attend to this issue when possible.
Duplicate of #7002.

Kind regards,
rezbyte

**Closed by rezbyte** 2024-07-24 07:41 UTC
