### ISSUE TITLE
Desktop app cannot login and cannot connect to tutanota server

### ISSUE THREAD

**Issue by TakagiAkito00** [tutao/tutanota#5294] opened 2023-03-23 15:08 UTC
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Describe the bug**
Updated to desktop app version 3.110.1 onward and I cannot login with the desktop app and/or the desktop app cannot connect to tutanota server.

**To Reproduce**
1. Using 3.110 Windows desktop app, can login and connect to server;
2. Close app (without logout, just close the app), and confirm no tutanota app instant is running;
3. Update app using install downloaded from official website (I am not sure if Github version is different from app from official website version, but I always update using official website version); 
4. Then open the app again and problem happens.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Winddows 10 21H2 build 19045.2728
 - OS Language: Japanese

**Additional context**

**Comment by charlag** [comment] 2023-03-23 15:28
Duplicate of  #5295 

(keeping the other one because we have an idea there)

**Closed by charlag** 2023-03-23 15:28 UTC
Labels: bug, desktop
