### ISSUE TITLE
(Oneplus One // CM11) Sideway scrolling is not possible with some mails

### ISSUE THREAD

**Issue by StocPhil** [tutao/tutanota#11] opened 2015-03-17 19:53 UTC
Hey,

I noticed that i am not able to scroll sideways with some mails but on others it works fine. The problem is that the same mail i cant scroll also cant display text-overflow. Some parts of the mail are not readable on my android device. 

It would also be nice to be able to have the option to zoom in on mails and their content. 

Greetings, Phil

**Comment by armhub** [comment] 2015-03-20 09:14
Could you send us an email which you can not scroll sideways, so we can reproduce it (support@tutao.de)? Thanks a lot!

**Comment by armhub** [comment] 2015-04-07 10:47
We close the issue tracker on gibhub because the official issue tracker is here and we do not want to handle two trackers: https://tutanota.uservoice.com/forums/237921-general
If your issue is not listed there, please add it. Thanks!

**Closed** 2017-09-04 14:17 UTC
