### ISSUE TITLE
Android APP does not work

### ISSUE THREAD

**Issue by Lamdarer** [tutao/tutanota#2116] opened 2020-06-19 10:44 UTC
I always get this error code if I start the app or try to login.
No matter if I use the Google Play or F-Droid version.
(Android 6.0)
(not sure if this error was already issued)

`Feedback v3.73.1 - TypeError - UNKNOWN - 

 Client: 
 Type: UNKNOWN
 Tutanota version: 3.73.1
 Timestamp (UTC): Fri, 19 Jun 2020 09:34:14 GMT
 User agent:
Mozilla/5.0 (Linux; Android 6.0; Apollo Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36
TypeError
 Error message: Cannot read property '0' of undefined
Stacktrace: 
TypeError: Cannot read property '0' of undefined
    at WorkerClient._queue.setCommands.error (file:///android_asset/tutanota/dist/main.js:1:1852758)
    at Queue._createClass.value (file:///android_asset/tutanota/dist/common.js:1:277565)
    at Worker.Queue._transport._transport.onmessage (file:///android_asset/tutanota/dist/common.js:1:276925)`

**Comment by charlag** [comment] 2020-06-19 10:46
Duplicate of #2107

Please update your WebView
https://tutanota.com/faq/#webview

**Closed by charlag** 2020-06-19 10:46 UTC
