### ISSUE TITLE
Android: Calender one week off in the App

### ISSUE THREAD

**Issue by norio-sh** [tutao/tutanota#6815] opened 2024-04-02 18:43 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
In my Android app (version 220.240321.0) the calendar shows one week off. It shows the dates for the past week in week-view. If I press one day in the line of weekdays at the top, it scrolls back one week too.
I have the same account/calendar on iOS and Linux desktop and they show correctly.

I have tried to reinstall the tuta-app on the android device but it's the same. The fault occurred for me first sometime in February.

**To Reproduce**
I just have one Android device, so I can't verify on a second device

1. Open the app
2. Click on calendar
3. It opens with the past week on the line at the top
4. If I press on the "today" button (which shows correct date) I'm taken to the same day but last week.
5. If I press on one of the days in the week-view, it scrolls back one week

**Expected behavior**
Before February it worked like it should, the date was in sync on the week-view. 

**Screenshots**
![screenshot_tuta](https://github.com/tutao/tutanota/assets/123622592/46dae921-1611-4b60-b7fb-5bd969f99ba7)

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 14
 - Version 220.240321.0

**Additional context**

**Comment by rezbyte** [comment] 2024-04-03 06:30
Hi @norio-sh,
I am sorry to hear you are having issues with the calendar.

Thank you for reporting this problem. We are already aware of this issue and a fix is planned. Stay tuned for the coming updates!

Duplicate of #6734.

**Closed by rezbyte** 2024-04-03 06:30 UTC
Labels: bug
