### ISSUE TITLE
UserNotAuthenticatedException when logging in on android

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3723] opened 2021-12-08 10:52 UTC
I started getting intermittent KeyStoreExceptions this morning when trying to log in. I have system password mode enabled. It could be an issue with android, since I updated to LineageOS 18 on sunday, but also maybe not?

 Client: android
 Type: UNKNOWN
 Tutanota version: 3.89.20
 Timestamp (UTC): Wed, 08 Dec 2021 07:27:46 GMT
 User agent:
Mozilla/5.0 (Linux; Android 11; moto g(7) power Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.50 Mobile Safari/537.36
java.security.KeyStoreException
 Error message: android.security.keystore.UserNotAuthenticatedException: User not authenticated
Stacktrace: 
java.security.KeyStoreException: android.security.keystore.UserNotAuthenticatedException: User not authenticated
 at de.tutao.tutanota.AndroidKeyStoreFacade.getCipherForDecryptionMode(AndroidKeyStoreFacade.java:216)
 at de.tutao.tutanota.credentials.CredentialsEncryptionFromAPI30.decryptUsingKeychain(CredentialsEncryptionFromAPI30.java:46)
 at de.tutao.tutanota.Native.invokeMethod(Native.java:325)
 at de.tutao.tutanota.Native.lambda$invoke$2(Native.java:98)
 at de.tutao.tutanota.Native.$r8$lambda$f7qJ0eoqELxVifjuL5uWd7yLx-I(Unknown Source:0)
 at de.tutao.tutanota.Native$$ExternalSyntheticLambda2.run(Unknown Source:4)
 at java.lang.Thread.run(Thread.java:923)
Caused by: android.security.keystore.UserNotAuthenticatedException: User not authenticated
 at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1346)
 at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1388)
 at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:54)
 at android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
 at android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:265)
 at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:148)
 at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2980)
 at javax.crypto.Cipher.tryCombinations(Cipher.java:2877)
 at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2796)
 at javax.crypto.Cipher.chooseProvider(Cipher.java:773)
 at javax.crypto.Cipher.init(Cipher.java:1288)
 at javax.crypto.Cipher.init(Cipher.java:1223)
 at de.tutao.tutanota.AndroidKeyStoreFacade.getCipherForDecryptionMode(AndroidKeyStoreFacade.java:211)
 ... 6 more

**Comment by johnbotris** [comment] 2021-12-08 10:54
It seems like initially unlocking works, and then if I try to use the key again before the system has locked the keychain, I get this error. Once the keychain has been locked, I am again able to login

**Comment by charlag** [comment] 2022-09-05 07:22
Duplicate of #3645

**Closed by charlag** 2022-09-05 07:22 UTC
Labels: bug, android
