### ISSUE TITLE
Notifications of deleted events still appear

### ISSUE THREAD

**Issue by ThracianKnight1907** [tutao/tutanota#2523] opened 2020-12-24 10:15 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

I have created some recurrent events from october to january. Now I deleted them, but i still receive notifications regarding these events from the calendar (iOS only, desktop and android don't seem to be affected).

**To Reproduce**
1. Create a recurring event e. g. from december to march next year
2. Delete it after a while e.g in january
3. See error

**Expected behavior**

No notifications would appear

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Ipad Air 3
 - OS: iPadOS 
 - Version 14.3

**Additional context**

**Comment by ThracianKnight1907** [comment] 2021-01-03 19:26
Well, I just received a notification about a deleted event on my laptop, so this is not iOS only.

**Comment by charlag** [comment] 2021-01-04 08:14
Thanks for letting us know, that's really weird. Is is the same one?

**Comment by ThracianKnight1907** [comment] 2021-01-05 07:44
I think so far I received 3 notifications of deleted events. 2 on iOS (event A and B) and 1 on Linux (event A).

**Comment by brshub** [comment] 2021-07-05 08:47
We just received a report that this is occurring on Android as well. The events are deleted on a Mac/Windows machine, but notifications still appear on the Android device. When checking the Android calendar the events are not present.

**Comment by charlag** [comment] 2021-08-03 06:44
For iOS it is likely caused by #3331

**Comment by charlag** [comment] 2021-09-02 13:49
Closing this as this should be fixed by #3331

**Comment by brshub** [comment] 2021-10-21 07:30
A recent report encountering this error occurs on the following devices:
Desktop PC - Windows 10 Pro version 2004 build 19041.1288
Client v 3.88.4
Ethernet connection

Cell phone - Huawei P10 Lite WAS-LX1, Android 8.0.0, Tutanota v3.88.3
WiFi and mobile data.

**Comment by charlag** [comment] 2022-10-19 07:55
duplicate of #4264

**Closed by charlag** 2022-10-19 07:55 UTC
Labels: bug, ios
