### ISSUE TITLE
Calendar does not show events that span a month boundary if the month ends on a Saturday

### ISSUE THREAD

**Issue by drglove** [tutao/tutanota#5920] opened 2023-09-21 22:33 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Calendar entries that span multiple days at the end of the month may not show up if the last day of the month is on the right edge of the calendar grid (i.e. a Saturday when viewing Sat-Sun).

**To Reproduce**
1. Go to your calendar
2. Add a new all-day event that starts on September 29th 2023 and ends on October 1st 2023. Alternatively August 31st 2024 -> September 1st 2024.
3. Note in the grid calendar view that the event apparently does not continue on October 1st and ends on September 30th instead. Or for the alternative dates, it does not continue on September 1st 2024 and ends on August 31st 2024.

**Expected behavior**
The calendar should show the event spanning over all dates visible.

**Screenshots**
![image](https://github.com/tutao/tutanota/assets/607460/0a04adaf-0e0e-4442-a668-100980cf0b11)
![image](https://github.com/tutao/tutanota/assets/607460/6a73b128-1440-4095-a93d-d1a563fa6c71)
![image](https://github.com/tutao/tutanota/assets/607460/f140b771-9d84-4c81-8ea1-05828e48e4ca)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tutanota v3.118.7

**Additional context**
- I found this because I have an event spanning September 29th -> October 1st this year in my calendar, but the view does not show it happening on October 1st. I tried this on a few other dates and it seems important that the last day of the month is in the bottom-right most box in the calendar grid. The next time this happens in August 24th 2024 (on a Sun-Sat calendar).
- This also happens even if the event is not an all-day event.
- Appears to happen on mobile as well as desktop.

**Comment by drglove** [comment] 2023-09-21 22:36
I just noticed it also doesn't appear in the agenda view either.

**Comment by ganthern** [comment] 2023-09-22 07:49
Thank you for the report!

it's probably a duplicate of https://github.com/tutao/tutanota/issues/5896

should be fixed with https://github.com/tutao/tutanota/pull/5904

**Closed by ganthern** 2023-09-22 07:49 UTC
Labels: bug, desktop
