### ISSUE TITLE
Calendar does not display events for next month

### ISSUE THREAD

**Issue by bobmatyas** [tutao/tutanota#1590] opened 2019-10-31 15:30 UTC
**Describe the bug**

The agenda view of the calendar isn't showing the next day's events. This seems to be related to the date (10/31) being the last day of the month.

This is happening on the Windows desktop app as well as the iOS app. 

**To Reproduce**

1. Open Tutanota client
2. Navigate to the "Agenda" view of the calendar
3. Agenda shows today's (10/31) events but not tomorrow's (11/1).

**Expected behavior**

Agenda should show upcoming events for subsequent days even if they are in a new month.

**Screenshots**

![tuta-screenshot](https://user-images.githubusercontent.com/45246438/67960947-630c5500-fbd1-11e9-90e9-0403c98d4226.png)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Version: Desktop 3.60.9

**Additional context**

If you navigate to the calendar view and then go back to the agenda view, it will show the events as would be expected.

**Comment by armhub** [comment] 2019-11-01 08:05
I observed a similar behavior in the Android app, so it is probably not a specific desktop client problem.

**Comment by vitoreiji** [comment] 2020-03-31 09:57
I have observed that this is not limited to the Agenda view. When the month or week view displays the first few days of the next month, events on those days should be displayed.

**To Reproduce**
1. Create event on the first day of next month
2. Log out
3. Log in
4. Go to calendar

**Expected behavior**
The event is displayed on the bottom row where the first few days of the next month are.

**Actual behavior**
The even is not displayed

**Additional info**
Only relevant if the month ends in the middle of a week.

**Comment by charlag** [comment] 2021-09-02 15:00
Duplicate of #3136

**Closed by charlag** 2021-09-02 15:00 UTC
Labels: bug
