### ISSUE TITLE
Duplicate event entry if changing end date of all day event

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1670] opened 2019-12-11 14:58 UTC
Reported by user:

> Add All day entry, eg. 11.12.2019 - 13.12.2019
> Edit entry
> Change date eg. 11.12.2019 - 11.12.2019
> Save changes
> Entry will duplicate
> After delete duplicate primary entry will also delete
> No profit

It seems like it is just a missing update in the ui. The event on the server is updated.

**Comment by charlag** [comment] 2019-12-11 15:56
Duplicate of #1668

(and yes it's just a UI glitch)

**Closed by charlag** 2019-12-11 15:56 UTC
Labels: bug
