### ISSUE TITLE
Tutanota for Linux has a problem with Debian 10

### ISSUE THREAD

**Issue by rmotao** [tutao/tutanota#1934] opened 2020-03-27 12:23 UTC
I download Tutanota for Linux direct from the site.

When I execute the AppImage file... the message below apear:

**[7605:0327/120946.379317:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_TutaNo3op6Qo/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap**

I am using Linux Debian 10.3 and no problem with the OS.

There is something else. If a use this command:

**./tutanota-desktop-linux.AppImage --no-sandbox**

The program just work fine!

OBS: Please, rename the file to a shorter name... like Tutanota.AppImage.

**Comment by charlag** [comment] 2020-03-27 12:24
Duplicate of #1565

**Closed by charlag** 2020-03-27 12:24 UTC
Labels: bug, desktop
