### ISSUE TITLE
Arabic contact names don't appear correctly

### ISSUE THREAD

**Issue by Ahmed-E-86** [tutao/tutanota#2233] opened 2020-08-30 22:08 UTC
**Describe the bug**
I tried to import .vcf that I exported from my android phone, and all the names are messed up. (not all of them, the English names are fine, but the Arabic names are messed up).

**Screenshots**
![Screenshot_20200830_235836](https://user-images.githubusercontent.com/29783425/91670397-59b78600-eb1d-11ea-9524-a2dd3d4f73fa.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04.1
 - Version: 3.75.3

**Comment by charlag** [comment] 2020-08-31 08:25
Duplicate of #1513

**Closed by charlag** 2020-08-31 08:25 UTC
Labels: bug, desktop
