### ISSUE TITLE
Failed to import ics file with a CN tag containing a comma

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2962] opened 2021-04-21 07:28 UTC
The CN attribute in an attendee field contains a comma and that causes an import failure. I haven't checked the rfc if this is an allowed case. It was reported by a user and i have created an example ics file which we can use to reproduce the problem.

BEGIN:VCALENDAR
PRODID:-//Tutao GmbH//Tutanota 3.82.18//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
DTSTART:20210421T073000Z
DTEND:20210421T080000Z
DTSTAMP:20210421T071403Z
UID:M7mFSJI----21618989210512@tutanota.com
SEQUENCE:2
SUMMARY:test with name
ORGANIZER;EMAIL=test@example.com:mailto:test@example.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE;EMAIL=test@example.com:mailto:test@example.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=lastname, firstname;EMAIL=attendee@example.com:mailto:attendee@example.com
END:VEVENT
END:VCALENDAR

**Comment by charlag** [comment] 2021-04-21 07:30
It is not allowed but it's export from us, see #2910

**Comment by johnbotris** [comment] 2021-04-21 07:30
Looks like a duplicate of #2910

**Closed by johnbotris** 2021-04-21 07:30 UTC
Labels: bug
