### ISSUE TITLE
[macOS] Copy hotkey not working

### ISSUE THREAD

**Issue by MosaicOrange** [tutao/tutanota#992] opened 2018-12-29 11:23 UTC
{Command + C} doesn’t work to copy highlighted text, however right clicking and selecting “copy” does copy text       
Using macOS High Sierra with new desktop clients

**Comment by dinoo** [comment] 2019-01-01 15:46
I am having the same issue with the desktop client (beta).

I would like to add that paste also isn't working inside the app.

I am using
MacOS Mojave 10.14.2

**Comment by dinoo** [comment] 2019-01-01 15:48
This a duplicate off [#988](https://github.com/tutao/tutanota/issues/988)

**Comment by ganthern** [comment] 2019-01-02 07:33
#988

**Closed by ganthern** 2019-01-02 07:33 UTC
