### ISSUE TITLE
Samsung One UI navigation bar not following the app theme

### ISSUE THREAD

**Issue by Krafting** [tutao/tutanota#1771] opened 2020-01-24 17:21 UTC
**Bug in mobile app**

**Describe the bug**
The bottom bar doesnt follow the app theme

**To Reproduce**
1. Go to the app
4. See the bottom bar doesn't follow the dark theme

**Expected behavior**
I expect it to be dark instead of white

**Screenshots**
![20200124_181522](https://user-images.githubusercontent.com/36538123/73089282-33ba6b00-3ed6-11ea-954f-882acf61fc63.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Note 9
 - OS: One UI 1.0 (Android Pie)
 - Version 3.66.5

**Comment by charlag** [comment] 2020-01-27 10:30
Duplicate of #1585

**Closed by charlag** 2020-01-27 10:30 UTC
Labels: bug
