### ISSUE TITLE
Emails with just inline attachments are marked with attachment icon in email list

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#3259] opened 2021-07-07 09:42 UTC
This is misleading as there is no attachment in the email shown. This is especially true for inline attachments of email signatures.
Expected: For just inline attachments we do not show the attachment icon in the email list on the email.

**Comment by bedhub** [comment] 2021-07-12 07:04
duplicate of #1734

**Closed by bedhub** 2021-07-12 07:04 UTC
Labels: bug
