### ISSUE TITLE
Show more details on push notification message / preview

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#1758] opened 2020-01-17 11:18 UTC
At least recipient should be displayed.

**Comment by lionirdeadman** [comment] 2020-06-23 03:50
Only iOS or also Android?

**Comment by charlag** [comment] 2020-06-23 07:17
@lionirdeadman on Android we already show the recipient. If we add more info, we will add it to both

**Comment by 1ennard** [comment] 2020-07-20 14:50
You see the recipient but what you don't see is **sender** and **email subject**.
It would be nice to have this information in the push notification.

**Comment by petiteoffense** [comment] 2020-07-21 00:14
Short of this or in addition to this, it would be useful if we could disable notifications for particular aliases or folders so that we don’t need to start up the app every time a semi-spam/unimportant email is received.

**Comment by bedhub** [comment] 2020-08-26 06:57
duplicate of #557

**Closed by bedhub** 2020-08-26 06:57 UTC
Labels: ios, new feature
