### ISSUE TITLE
Whitelabel setup breaks if you select manual certificate

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3265] opened 2021-07-08 08:22 UTC
* Open up whitelabel domain editor
* Select _Manual_ certificate (this shouldn't even be offered as an option?)
* You can't change back to automatic
* Click close
* An error report dialog opens up
* Click send report
* The report dialog is empty
* Hitting close will open up another broken error dialog (ad infinitum)
* Open up the whitelabel setup dialog
* It is empty

**Comment by armhub** [comment] 2021-07-08 11:07
Seems to be related to #2554

**Comment by bedhub** [comment] 2021-07-12 06:57
duplicate of #2554

**Closed by bedhub** 2021-07-12 06:57 UTC
Labels: bug, duplicate
