### ISSUE TITLE
Update service worker if only one tab is opened

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#607] opened 2018-09-12 14:16 UTC
Currently, every user has to close the Tutanota tab, open a new tab and enter https://mail.tutanota.com again. It would be nice if closing tabs would only be needed, if multiple tabs are open.

**Comment by charlag** [comment] 2018-10-09 06:30
Using [this article](https://redfin.engineering/how-to-fix-the-refresh-button-when-using-service-workers-a8e27af6df68) as a reference:
- We would like to update when there's only one client which is loading the page.
  - The problem is that it doesn't work anywhere but Chrome
    - We're blocked by FF not exposing `registartion.active / registration.waiting` inside ServiceWorker so we cannot communicate between active/waiting worker to respond to navigation requests
  - I've tried sending a message to SW on page reload and get clients at this moment but results are inconsistent (especially in Chrome: id of client before/after reload is different and client is connected too soon after reloading so in Chrome it looks like we always have another tab)
- Another option is option 3 from the article: prompt user to refresh.
  - When update is found we should the message (like we do now) and we show the button to update
  - When user pressed update button we active new worker and reload all pages (on `controllerchange` event)
  - This is not a perfect UX (we don't want to break "refresh" button) we cannot do better right now. We can change it when browsers are updated and more consistent.
  - We need to clearly say that we will reload other tabs. Maybe we should poll other tabs before switching the controller so that drafts can be saved.

**Comment by charlag** [comment] 2018-10-11 10:02
Fixed by 0602c16
![screenshot from 2018-10-11 11-57-20](https://user-images.githubusercontent.com/3099142/46796648-78f07300-cd4d-11e8-996d-68ab73847a9a.png)

**Comment by mpfau** [comment] 2018-10-16 15:03
Release notes link points to `https://github.com/tutao/tutanota/releases/tag/tutanota-release-$%7Benv.versionNumber%7D`

**Closed** 2018-10-17 06:28 UTC
Labels: improvement
