### ISSUE TITLE
Unread in Inbox count is off by 1

### ISSUE THREAD

**Issue by rgb-one** [tutao/tutanota#1703] opened 2019-12-24 17:32 UTC
**Bug in web app**

**Describe the bug**
Whenever unread mail is in the inbox, the Inbox count is 1 less than the actual number of items in the inbox. 

**To Reproduce**

1. Ensure there is more than one unread mail in the main 'Inbox'
2. Go to 'Inbox'
3. Observe the unread in inbox count (beside the 'Inbox' text), it should be one less than the number of items in the inbox.

**Expected behavior**
The unread mail count for Inbox should be the same as the number of unread mail in the inbox.

**Screenshots**
I'll add a screenshot later when it happens again.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 71.0 (64-bit)

**Smartphone (please complete the following information):**

I haven't used Tutanota on a mobile phone before. 

**Additional context**
I only remember observing this issue with the Inbox. I don't know if this happens with the other options like 'Spam', or 'Trash'.

**Comment by armhub** [comment] 2019-12-28 23:45
Duplicate of #1267

**Closed by armhub** 2019-12-28 23:45 UTC
Labels: duplicate
