### ISSUE TITLE
Android application keeps loading and mail items are not received

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1524] opened 2019-10-01 08:49 UTC
When I open the mail app from my mobile, new items has not been received and the loading 'candybar' strip in the top of the screen just keeps running.

When I reboot my phone, re-open my mobile phone application, new items are received, but when I leave the application in the background, it will be stuck again after a while. Then when I open the application from application icon, the loading strip keeps running.

**Comment by charlag** [comment] 2019-10-02 12:09
Duplicate of #1517

**Closed by charlag** 2019-10-02 12:09 UTC
Labels: bug
