### ISSUE TITLE
Desktop file download is broken

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3611] opened 2021-10-27 12:22 UTC
The desktop implementation of file download is out of sync with it's usage in the web side

see the return value of `DesktopDownloadManager.downloadNative`:
https://github.com/tutao/tutanota/blob/01aff612118cdb5ca1fc809b1f631ceba3af530f/src/desktop/DesktopDownloadManager.js#L56

compared to the return value of `FileApp.download`:
https://github.com/tutao/tutanota/blob/d9317831b931c85802fc0420e769e2c62c84760f/src/native/common/FileApp.js#L116

Specifically, the web side expects `{ statusCode, encryptedFileUri, errorId, precondition, suspensionTime }`
but native returns `{ statusCode, statusMessage, encryptedFileUri }`, and will reject if it receives any non-200 response code. Also the code is pretty incomprehensible.

In general it still works when nothing goes wrong, but client at least client suspension is not handled properly

**Comment by charlag** [comment] 2022-03-04 12:48
duplicate of  #3382

**Closed by charlag** 2022-03-04 12:48 UTC
Labels: bug
