### ISSUE TITLE
  Tutanota-Desktop-bin has been crashing here continuously since today.

### ISSUE THREAD

**Issue by HeinzDo58** [tutao/tutanota#1806] opened 2020-02-11 15:41 UTC
Tutanota-Desktop-bin has been crashing here continuously since today. 
https://pastebin.com/57CmGKWi
I use arch linux.

**Comment by charlag** [comment] 2020-02-12 16:53
Hi
It's not clear what's going on there to be honest. Is there anything special, location, read-only, possible missing deps? 
You can try installing libsecret even though it should not be necessary

**Comment by ganthern** [comment] 2020-02-13 08:11
Did this problem persist with the package version 3.67.3-4 from the AUR? They seem to have made some changes in the past few hours. I'm also on Arch Linux, but have the client installed manually. No crashes here.

We would also need a little more information about your environment since Arch Linux ist pretty close to a DIY-Distro with respect to the possible setups. At least your DE and installed extensions with versions and a better description of the process from arch boot to tutanota crash.
This is also the reason we have a template for reporting bugs.

Thanks for the report!

**Comment by HeinzDo58** [comment] 2020-02-13 08:15
Yes, the problem unfortunately still exists.
 It keeps crashing and then restarting. And in an endless loop.
I use arch linux with KDE Plasma 5.18.
I have this problem since 2 days.

**Comment by HeinzDo58** [comment] 2020-02-13 10:31
I Maybe this helps here?
These are the messages when the desktop client starts.

tutanota-desktop 
[2020-02-13T10:27:33.887Z] the monkey has been patched
libsecret-Message: 11:27:33.908: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
[2020-02-13T10:27:33.912Z] _connectedSseInfo undefined
[2020-02-13T10:27:33.913Z] scheduling to reconnect sse in 1 seconds
[2020-02-13T10:27:33.913Z] argv:  [ '/opt/tutanota-desktop/tutanota-desktop' ]
[2020-02-13T10:27:33.914Z] version:   3.67.3
[2020-02-13T10:27:33.929Z] alarm storage failed to initialize: [Error: The name org.freedesktop.secrets was not provided by any .service files]
[2020-02-13T10:27:33.933Z] startFile:  file:///opt/tutanota-desktop/resources/app.asar/desktop.html
[2020-02-13T10:27:33.984Z] default mailto handler: false
[2020-02-13T10:27:34.581Z] Webapp ready
[2020-02-13T10:27:34.582Z] checking for /home/heinz/.local/share/applications/tutanota-desktop.desktop ...
[2020-02-13T10:27:34.582Z] desktop file exists, checking version...
[2020-02-13T10:27:34.914Z] scheduling to reconnect sse in 10 seconds
[2020-02-13T10:27:34.914Z] sse info not available, skip reconnect
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
[2020-02-13T10:27:38.524Z] browserWindow crashed, trying to reopen at /login
[2020-02-13T10:27:38.528Z] startFile:  file:///opt/tutanota-desktop/resources/app.asar/desktop.html
[2020-02-13T10:27:39.853Z] saving bounds: {
  fullscreen: false,
  rect: { x: 560, y: 251, width: 800, height: 607 },
  scale: 1
}
[2020-02-13T10:27:44.917Z] scheduling to reconnect sse in 10 seconds
[2020-02-13T10:27:44.917Z] sse info not available, skip reconnect

**Comment by sofiageo** [comment] 2020-02-13 12:24
> Did this problem persist with the package version 3.67.3-4 from the AUR? They seem to have made some changes in the past few hours. I'm also on Arch Linux, but have the client installed manually. No crashes here.

I was having the same issue after updating my Arch installation. I'm using the Tutanota appImage so It's not just an issue of the AUR package. I'm on Gnome by the way. The issue kept happening when using the Desktop entry. When I tried to run the client from the appImage file in my terminal so I can see what's wrong, it stopped crashing. So I guess it's something wrong with the Desktop integration.

**Comment by sofiageo** [comment] 2020-02-13 12:55
Googling a bit reveals it might be an issue with glibc and Chromium. So I post my verisons here as well:

glibc: 2.31-1 (build date: 02 Feb 2020)
Chromium: 80.0.3987.100-1 (build 11 Feb 2020). 

So it looks like a regression on Chromium ?

**Comment by sofiageo** [comment] 2020-02-13 13:17
I'm not really sure how Tutanota electron client is working but I noticed that electron 8 has been packaged today. I just installed it and waiting for another crash at the moment. Will report if that was the issue.

**Comment by sofiageo** [comment] 2020-02-13 13:22
This issue is definitely fixed, the problem was electron 7 package which was using an old version of chromium: https://git.archlinux.org/svntogit/community.git/commit/trunk/PKGBUILD?h=packages/electron&id=0e42d343f51dc6a9bbd5fa2afbd8f8ac4ca8112a

The fix landed in chromium 80.0.3983.2 as you can see here: https://bugs.chromium.org/p/chromium/issues/detail?id=1025739

Electron 8 fixes it which is now available in Arch Linux.

**Comment by HeinzDo58** [comment] 2020-02-13 13:27
Then this fix only has to land in Tutanota.
So far, the desktop client has been crashing every second.

**Comment by charlag** [comment] 2020-02-13 13:28
We will depend on Electron 8 with the next version so should be fixed soon.

**Comment by sofiageo** [comment] 2020-02-13 13:45
> Then this fix only has to land in Tutanota.
> So far, the desktop client has been crashing every second.

Yeap, took about 22 minutes this time but it crashed again even with electron 8 in Arch. I'm not sure why it takes so long to crash on my PC :)

**Comment by sofiageo** [comment] 2020-02-15 01:00
I confirm that after about 3 hours with 3.67.4 no crashes have occurred. Thanks.

**Comment by ganthern** [comment] 2020-02-18 13:37
I'll close this then.

**Closed by ganthern** 2020-02-18 13:37 UTC
Labels: bug, desktop
