### ISSUE TITLE
Event creation in Agenda View defaults to today, not selected date

### ISSUE THREAD

**Issue by matrop** [tutao/tutanota#6321] opened 2023-12-20 14:15 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

The following bug appears in the calendar on iOS: When I'm in the agenda view for a day thats not today, and click the '+' to create a new event, the event creation dialog shows up. The dialog defaults to todays date and an event time from 00:00 to 00:30.

**To Reproduce**
1. Open the calendar in the iOS app
2. Click on some day in the future
3. Click on '+' to add a new event
4. Notice that the pre-filled date and time is today's date and 00:00-00:30

**Expected behavior**
I would expect the event creation dialog to set the event date to the one currently selected in the agenda view and the event time to the next half hour.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Mini
 - OS: 17.1.2
 - Version 21B101

**Comment by ganthern** [comment] 2023-12-21 08:23
Hello there :wave:

Can you add which version is shown on the bottom of the login screen?

**Comment by matrop** [comment] 2023-12-21 08:52
It's Version 3.119.3

**Comment by ganthern** [comment] 2023-12-21 09:33
Okay, this problem should be fixed with the next version. Apple's App Review take their sweet time at the moment.

The relevant release is here:
https://github.com/tutao/tutanota/releases/tag/tutanota-ios-release-3.119.8

The issue for the problem is here:
https://github.com/tutao/tutanota/issues/6294

Thanks for looking out!

**Closed by ganthern** 2023-12-21 09:33 UTC
Labels: bug
