### ISSUE TITLE
DbError: "The database connection is closing"

### ISSUE THREAD

**Issue by asteintutao** [tutao/tutanota#452] opened 2018-07-10 14:10 UTC
before i got this error the client was open for several hours. Then after waking the pc this error occurred also i wanted to write an email after this error happend but clicking into the recipient files triggered the same error again. Error was gone after reloging. 

error DbError: could not create transaction: InvalidStateError, Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.> Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at https://mail.tutanota.com/worker.js:1:392192
    at r (https://mail.tutanota.com/libs.js:32:9004)
    at i._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:31:14217)
    at i._settlePromise (https://mail.tutanota.com/libs.js:31:15020)
    at i._settlePromiseCtx (https://mail.tutanota.com/libs.js:31:15528)
    at r._drainQueue (https://mail.tutanota.com/libs.js:30:3039)
    at r._drainQueues (https://mail.tutanota.com/libs.js:30:3117)
    at drainQueues (https://mail.tutanota.com/libs.js:30:1238)
    at https://mail.tutanota.com/worker.js:1:392266
    at r (https://mail.tutanota.com/libs.js:32:9004)
    at i._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:31:14217)
    at i._settlePromise (https://mail.tutanota.com/libs.js:31:15020)
    at i._settlePromiseCtx (https://mail.tutanota.com/libs.js:31:15528)
    at r._drainQueue (https://mail.tutanota.com/libs.js:30:3039)
    at r._drainQueues (https://mail.tutanota.com/libs.js:30:3117)
    at drainQueues (https://mail.tutanota.com/libs.js:30:1238)

**Comment by mpfau** [comment] 2018-11-06 11:19
@asteintutao does this error still occur?

**Comment by mpfau** [comment] 2018-11-12 09:46
related to #738

**Comment by armhub** [comment] 2018-11-15 10:05
Also occurs when trying to write the address in a new mail

**Comment by charlag** [comment] 2018-11-15 13:42
Looks like
https://github.com/jensarps/IDBWrapper/issues/80
https://github.com/pouchdb/pouchdb/issues/3415#issuecomment-71058793 (ni Nolan!)

**Comment by charlag** [comment] 2018-11-16 09:59
Cannot reproduce, assume tested

**Comment by charlag** [comment] 2018-11-19 07:33
Still occurs in iOS app with 3.40.3

**Comment by charlag** [comment] 2018-11-19 08:00
"Connection closed on Chrome (IndexedDB) in long sessions" https://github.com/localForage/localForage/issues/581
"try reconnect to the DB after InvalidStateError" https://github.com/localForage/localForage/pull/694
"Chrome - Random Closing Database issue (hard/impossible to reproduce)" https://github.com/dfahlander/Dexie.js/issues/613

**Comment by charlag** [comment] 2018-11-19 08:00
Also occurs on Android 3.40.3

**Comment by armhub** [comment] 2018-11-21 12:08
Was fixed in 3.41.1

**Comment by charlag** [comment] 2018-11-28 07:39
> .was just sending an email after clearing old emails to keep under 1Gb limit

```
Client: Browser
Tutanota version: 3.41.5
User agent: 
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

Error message: 
could not create transaction: InvalidStateError, Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.> Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
at https://mail.tutanota.com/worker.js:1:413095
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromiseCtx (https://mail.tutanota.com/libs.js:26:47848)
at h (https://mail.tutanota.com/libs.js:26:1699)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at drainQueues (https://mail.tutanota.com/libs.js:26:1327)

Stacktrace: 
DbError: could not create transaction: InvalidStateError, Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.> Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
at https://mail.tutanota.com/worker.js:1:413095
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromiseCtx (https://mail.tutanota.com/libs.js:26:47848)
at h (https://mail.tutanota.com/libs.js:26:1699)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at drainQueues (https://mail.tutanota.com/libs.js:26:1327)
at https://mail.tutanota.com/worker.js:1:413286
at a (https://mail.tutanota.com/libs.js:26:73165)
at F._settlePromiseFromHandler (https://mail.tutanota.com/libs.js:26:46542)
at F._settlePromise (https://mail.tutanota.com/libs.js:26:47342)
at F._settlePromiseCtx (https://mail.tutanota.com/libs.js:26:47848)
at h (https://mail.tutanota.com/libs.js:26:1699)
at p (https://mail.tutanota.com/libs.js:26:1585)
at a._drainQueues (https://mail.tutanota.com/libs.js:26:3078)
at drainQueues (https://mail.tutanota.com/libs.js:26:1327)
```

and some other reports

**Comment by charlag** [comment] 2019-05-22 14:18
Re-surfaced after 3.52.1

**Comment by charlag** [comment] 2020-02-28 16:07
This is a different issue
#1855

**Closed by charlag** 2020-02-28 16:07 UTC
Labels: bug
