### ISSUE TITLE
[android] notification service always in notification area

### ISSUE THREAD

**Issue by guoyunhe** [tutao/tutanota#1908] opened 2020-03-14 13:39 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

After upgrade to Android 10 (MIUI 11), I saw this notification cannot be removed:

**To Reproduce**
1. Android 10 & MIUI 11 phone
2. Open Tutanota
3. Check notification area

**Expected behavior**
Here should not be notification when here is no new mails.

**Screenshots**
![Screenshot_2020-03-14-15-32-53-006_com reddit frontpage](https://user-images.githubusercontent.com/5836790/76683043-7ad8f880-6609-11ea-9327-f2239ddb96e3.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi Max 3
 - OS: Android 10 & MIUI 11
 - Version 3.68.1

**Additional context**

**Comment by charlag** [comment] 2020-03-16 10:58
duplicate of #1793

**Closed by charlag** 2020-03-16 10:58 UTC
Labels: bug
