### ISSUE TITLE
Old links to external confidential Emails don't show an expiry notification

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4184] opened 2022-05-19 14:37 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
When you send multiple external confidential Emails to the same recipient, the older links (opened or otherwise) do not display an expiry notification.

**To Reproduce**
1. Send an external email with a password
2. Send a second email to the same recipient
3. On the recipient's end, use the first link to the Email and login
4. The message "Invalid login credentials, please try again" is displayed

**Expected behavior**
I expect to get a message telling me that the link isn't active or has expired.

##  Test notes
* [ ] Normal internal login still works (saved credentiials and form login)
* [ ] External mailbox link looks like mail.tutanota.com/ext#mail/someBase64hashHere. When the link from notification email is opened, userId and salt are extracted from the hash at the end of the url: generated user id is concatenated with base64url of salt
* [ ] If the sender sends another email the new link is generated. Logging in with the old one no longer works, instead it shows a message that the link is outdated. This is true for both saved credentials and new logins. Existing sessions are not closed nor credentials are deleted when using an outdated link.
* [ ] If the sender changes the password for the mailbox, existing sessions will no longer work. Existing session must be closed and stored credentials deleted. Outdated links handling has higher priority. The sessions are not closed automatically on the password change and no external users are kicked out of their mailboxes.
* [ ] If the link is up-to-date and the password/session are correct the user can log into the external mailbox. It looks similar to the normal one but is more restricted

**Comment by johnbotris** [comment] 2022-06-15 15:36
I can't reproduce this bug. If I try to use an old link i get shown the correct error message: 

![Image](https://user-images.githubusercontent.com/22109738/173867795-5f14c4e8-4808-415f-8907-d1480d436393.png)

@kibhub could you elaborate on what the issue was or try to reproduce it? maybe it was fixed by accident.

**Comment by armhub** [comment] 2022-10-14 07:18
This is reproducible with the steps mentioned above.

**Comment by charlag** [comment] 2022-10-19 09:35
The issue does not occur if you don't save the password. However, if you try to log in with saved credentials it will tell you that they are not valid anymore instead of showing the message.

**Closed** 2022-10-27 13:58 UTC
Labels: bug, done
