### ISSUE TITLE
Can’t open Tutanota app or login on website via IOS

### ISSUE THREAD

**Issue by Lololore** [tutao/tutanota#6093] opened 2023-11-04 00:49 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Cant login anymore from my IPhone, either with the app or on the website. I can login through my laptop though. Shows a message with SecurityError.

Feedback v3.118.22 - SecurityError - UNKNOWN - ios

 Client: ios
 Type: UNKNOWN
 Tutanota version: 3.118.22
 Timestamp (UTC): Sat, 04 Nov 2023 00:40:44 GMT
 User agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 15_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
SecurityError
 Error message: The operation is insecure.
Stacktrace: 
@[native code]
@asset://app/main-8d12a609.js:1:15117
asyncFunctionResume@[native code]
@asset://app/main-8d12a609.js:1:95273
@asset://app/main-8d12a609.js:1:95342
asyncFunctionResume@[native code]
@asset://app/app.js:1:77839
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]

**To Reproduce**
1. Login with the app (either typing password or with fingerprint)

**Expected behavior**
Should login in the mailbox.

**Screenshots**
![1BA5F9CC-E843-4E80-819C-1C1A97387804](https://github.com/tutao/tutanota/assets/149845714/404a46d2-9197-4342-965b-865396aa062b)

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: 
 - Version 15.2.1

**Additional context**

**Comment by charlag** [comment] 2023-11-06 08:41
Duplicate of #6056

**Closed by charlag** 2023-11-06 08:41 UTC
Labels: bug
