### ISSUE TITLE
[Improvement] Enable image display for a sender email/domain

### ISSUE THREAD

**Issue by l0f4r0** [tutao/tutanota#1386] opened 2019-07-25 22:05 UTC
It seems that Tutanota doesn't remember when the user chose to accept image display for an email. Maybe it's intended but maybe we could let the user choose whether (s)he wants to allow image display for some identical emails so (s)he doesn't need to do it for each email sent from the same address/domain.

**Comment by armhub** [comment] 2019-07-26 14:59
This is a duplicate of #147

**Closed by armhub** 2019-07-26 14:59 UTC
Labels: bug
