### ISSUE TITLE
Win10 3.122.4 Update Error on Login

### ISSUE THREAD

**Issue by anotheruserwhowantstohelp** [tutao/tutanota#6524] opened 2024-02-09 14:27 UTC
- [ Yes] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ Yes] I've searched and did not find a similar issue.

**Describe the bug**

First downloaded [3.122.3] when I woke up, encountered the same error. Then downloaded [3.122.4], restarted computer and ecounterd the same problem. Bellow was the error given. 

Feedback v3.122.4 - Error - UNKNOWN - win32

 Client: win32
 Type: UNKNOWN
 Tutanota version: 3.122.4
 Timestamp (UTC): Fri, 09 Feb 2024 14:21:38 GMT
 User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.122.4 Chrome/120.0.6099.268 Electron/28.2.1 Safari/537.36
Error
 Error message: EBUSY: resource busy or locked, unlink 'C:\Users\USERNAME\AppData\Roaming\tutanota-desktop\offline_NFJnUVo----9.sqlite'
Stacktrace: 
Error: EBUSY: resource busy or locked, unlink 'C:\Users\USERNAME\AppData\Roaming\tutanota-desktop\offline_NFJnUVo----9.sqlite'

**Expected behavior**
Download new update -> Tutanota opens just as usual. 

**Desktop (please complete the following information):**
OS: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.122.4 Chrome/120.0.6099.268 Electron/28.2.1 Safari/537.36
Version 3.122.4

**Comment by anotheruserwhowantstohelp** [comment] 2024-02-09 15:26
Hi Charlag, my tuta is only installed on one user, and when updating to 3.122.3 and 3.1224 respectfully, after installing I always restart my PC. 

Tried it again just before writing this, same error occures. 

I could rollback to the update from last week but am keeping this ticket open until a team member responds.

**Comment by SirHazza** [comment] 2024-02-09 15:41
I just updated to the latest client and I'm getting this same issue. I'm on Windows 11.

```
Feedback v3.122.4 - Error - UNKNOWN - win32

 Client: win32
 Type: UNKNOWN
 Tutanota version: 3.122.4
 Timestamp (UTC): Fri, 09 Feb 2024 15:39:12 GMT
 User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.122.4 Chrome/120.0.6099.268 Electron/28.2.1 Safari/537.36
Error
 Error message: EBUSY: resource busy or locked, unlink 'C:\Users\USERNAME\AppData\Roaming\tutanota-desktop\offline_MSKXQ1I----2.sqlite'
Stacktrace: 
Error: EBUSY: resource busy or locked, unlink 'C:\Users\USERNAME\AppData\Roaming\tutanota-desktop\offline_MSKXQ1I----2.sqlite'
```

**Comment by anotheruserwhowantstohelp** [comment] 2024-02-09 15:49
> I just updated to the latest client and I'm getting this same issue. I'm on Windows 11.
> 
> ```
> Feedback v3.122.4 - Error - UNKNOWN - win32
> 
>  Client: win32
>  Type: UNKNOWN
>  Tutanota version: 3.122.4
>  Timestamp (UTC): Fri, 09 Feb 2024 15:39:12 GMT
>  User agent:
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.122.4 Chrome/120.0.6099.268 Electron/28.2.1 Safari/537.36
> Error
>  Error message: EBUSY: resource busy or locked, unlink 'C:\Users\USERNAME\AppData\Roaming\tutanota-desktop\offline_MSKXQ1I----2.sqlite'
> Stacktrace: 
> Error: EBUSY: resource busy or locked, unlink 'C:\Users\USERNAME\AppData\Roaming\tutanota-desktop\offline_MSKXQ1I----2.sqlite'
> ```

Hi SirHazza, 

Were you able to restart your PC and get the same error as well? Want to make sure my case isn't isolated.

**Comment by SirHazza** [comment] 2024-02-09 16:23
Restarted and issue persisted. 

Doesn't seem like an isolated case: https://github.com/tutao/tutanota/issues/6528

**Comment by ne0zepG** [comment] 2024-02-09 18:13
I'm having this issue as well and have sent an email to support. Hopefully this get immediately fixed. 🤞

**Comment by MustachedMario** [comment] 2024-02-09 19:14
Same here. Happend while updating from 3.121.4 to 3.122.3, and still happend on 3.122.4.
Deleting the offline_xxxx.sqlite file in the user profile (and rebuilding it at next start) fixes this issue.

**Comment by M1Screw** [comment] 2024-02-10 15:51
> Same here. Happend while updating from 3.121.4 to 3.122.3, and still happend on 3.122.4. Deleting the offline_xxxx.sqlite file in the user profile (and rebuilding it at next start) fixes this issue.

This indeed fixed the issue, btw the full path is `C:\Users\UserName\AppData\Roaming\tutanota-desktop` in case anyone wondering.

**Comment by anotheruserwhowantstohelp** [comment] 2024-02-10 18:01
> > Same here. Happend while updating from 3.121.4 to 3.122.3, and still happend on 3.122.4. Deleting the offline_xxxx.sqlite file in the user profile (and rebuilding it at next start) fixes this issue.
> 
> This indeed fixed the issue, btw the full path is `C:\Users\UserName\AppData\Roaming\tutanota-desktop` in case anyone wondering.

This fix did work thankfully, waiting for devs to respond and see what the real issue was.

**Comment by charlag** [comment] 2024-02-12 09:06
Duplicate of #5063

**Closed by charlag** 2024-02-12 09:06 UTC
Labels: bug, desktop
