### ISSUE TITLE
add offline indexes search db

### ISSUE THREAD

**Issue by europound** [tutao/tutanota#2681] opened 2021-02-07 18:42 UTC
every time when i try to search, i have to reindex entire mailbox, takes ages
please add offline local db sync even if it take 10 GB or whatever the size of my paid mailbox

**Comment by charlag** [comment] 2021-02-08 08:06
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.

duplicate of #590

**Closed by charlag** 2021-02-08 08:06 UTC
