### ISSUE TITLE
Mobile device native back button does not work in the contact details view

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1545] opened 2019-10-10 10:17 UTC
How to reproduce:
1. open a contact on a mobile device, so the contact list is not visible.
2. Press the device's back button
-> Nothing happens
Expected: the contact list is shown

**Comment by charlag** [comment] 2019-10-10 10:20
Duplicate of #1532

**Closed by charlag** 2019-10-10 10:20 UTC
Labels: bug
