### ISSUE TITLE
Closing empty mail dialog results in draft being saved

### ISSUE THREAD

**Issue by paw-hub** [tutao/tutanota#4105] opened 2022-05-06 06:49 UTC
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Closing an empty mail dialog with no recipients, body, or subject results in a draft being saved

**To Reproduce**
1. Create a new Mail
2. Close the Mail

**Expected behavior**
Nothing should happen except the mail being closed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Browser: Chromium
 - Version 100.0

**Comment by Jlll1** [comment] 2022-05-06 07:21
Possibly duplicate of #3580

**Comment by charlag** [comment] 2022-05-09 07:13
It is

**Closed by charlag** 2022-05-09 07:13 UTC
Labels: bug

**Comment by charlag** [comment] 2022-05-09 11:45
@paw-hub that issue is not closed, I just described what we decided before the issue was opened
