### ISSUE TITLE
Text is pasted twice in the composer window

### ISSUE THREAD

**Issue by dinoo** [tutao/tutanota#1581] opened 2019-10-24 21:40 UTC
**Description**
When i copy some text from my newly composed message and paste it inside the message again, it will copy the text twice.

**Steps to reproduce**
- Go to 'New message'
- Type 'qwerty' in the message area
- Select newly typed line
- Press Cmd+C
- Go to new line
- Press Cmd+V

**Expected result**
The selected text is copied and pasted once

**Actual result**
The selected text is copied, but pasted twice

**Additional information**
Desktop
- OS: macOS Mojave (10.14.6)
- Version 3.60.9

**Comment by mpfau** [comment] 2019-10-24 21:58
duplicate of #1572, fix will be released soon

**Closed by mpfau** 2019-10-24 21:58 UTC
Labels: duplicate
