### ISSUE TITLE
Sporadically blank window after logout

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1503] opened 2019-09-24 07:35 UTC
This console output is: file:///tmp/.mount_tutanoGrjnfw/resources/app.asar/desktop.html/login?requestedPath=%3Fr%3D%252Flogin%253FnoAutoLogin%253Dtrue

After reloading (F5) Tutanota is visible again.

Seen in v3.59.12 on Ubuntu

**Comment by ganthern** [comment] 2019-11-07 10:21
i'm going to call this a dupe of #1382

**Closed by ganthern** 2019-11-07 10:21 UTC
Labels: bug, desktop
