### ISSUE TITLE
Missing toolbar

### ISSUE THREAD

**Issue by nadesco** [tutao/tutanota#5354] opened 2023-04-07 04:33 UTC
In the past week or so I've noticed that the toolbar occasionally disappears after going back online. It's happened maybe 3 or 4 times. The issue always resolves itself after closing and reopening the app.

It's somewhat random and hard to reproduce but, like I say, it happens when I've been offline and reconnect. Expected behaviour is that whenever the client is open the toolbar should be visible at all times.

[Screenshot](https://imgur.com/a/grSmrM7)

Mac 12.6
Desktop client ver3.112.6

Edit: It just happened again, although this time without having been offline. The first screenshot shows an _Offline Reconnect_ status. The second screenshot shows _Online_. The _New email_ box is also missing.

I don't know what triggered it because over a period of about 30 minutes I'd logged in/out a few times without issue. 

[Screenshot 2](https://imgur.com/a/7xmY4dz)

**Comment by charlag** [comment] 2023-04-11 07:57
Could this be a duplicate of #5349 ?

**Comment by nadesco** [comment] 2023-04-11 09:12
Yes, it looks like the same bug. Shall I close this post?

**Closed** 2023-04-11 09:58 UTC
Labels: bug, desktop
