### ISSUE TITLE
Contacts search does not clear when pressing x button

### ISSUE THREAD

**Issue by treewolf** [tutao/tutanota#6704] opened 2024-03-13 19:39 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app and android app**
When trying to clear the search field by pressing "x" for contacts, nothing happens.

**Describe the bug**
The "x" in the search bar is expected to remove all text from the field so one can type in a new search without using the backspace key.

**To Reproduce**
1. Go to "Contacts"
2. Click in the search bar
3. Type any text
4. Click the "x" to clear text

**Expected behavior**
Expect to have search bar clear, removing all text that was entered as input.

**Screenshots**

**Desktop (please complete the following information):**
 - Device: Laptop
 - OS: Macos Ventura 13.6.4 (22G513)
 - Browser: Firefox 123.0
 - Version : Tuta v218.240307.1

**Smartphone (please complete the following information):**
 - Device: Samsung S21
 - OS: Android 14
 - Browser: Tuta Mobile App
 - Version : Tutanota v218.240227.0

MP4 of web version attached.

https://github.com/tutao/tutanota/assets/12214656/5ef40e5a-4fc3-4ba8-bce3-05ac0ff5e467

**Comment by rezbyte** [comment] 2024-03-14 06:42
Hi @treewolf ,
I am sorry to hear you are having issues with the search bar.

Thank you for reporting this problem. We are already aware of this issue and a fix is planned. Stay tuned for the coming updates!

Duplicate of #6604

**Closed by rezbyte** 2024-03-14 06:42 UTC
Labels: bug
