### ISSUE TITLE
Are email threads an option?

### ISSUE THREAD

**Issue by kimbriggsdotcom** [tutao/tutanota#1003] opened 2019-01-03 03:35 UTC
Re:  Feature Request.  I have used the search feature but do not find an issue concerning this very common practice.  I have also search through the Email Settings in the app.

I am new to the software and just discovered that emails with friends are not kept in a single thread when replying normally with "Reply" option.  In other words, their next email starts a new message.  Is this not possible with your technology?  It is going to make finding social information more difficult and fill up my Inbox too quickly.

If this is not going to be the default behavior, please let me know if it is planned for the future or it is not possible, etc.  Thank you.

**Comment by mpfau** [comment] 2019-01-03 07:34
Duplicate of #6

**Closed by mpfau** 2019-01-03 07:34 UTC
