### ISSUE TITLE
non readed messages count error

### ISSUE THREAD

**Issue by Unsourire** [tutao/tutanota#1508] opened 2019-09-25 12:30 UTC
**Bug in web app**

**Describe the bug**
When i have all the messages reded, i just want for rembered me to let the e-mail as non-read. But it's not the good amout.

**To Reproduce**
mark as unread one message, you will se that the number of non-readed message don't change. When you select one more nnreadedmessage the amount will start to 1 .  

**Expected behavior**
To have the correct amout of nonreaded message

i'm using firefox

**Comment by rdvincent** [comment] 2019-09-27 19:49
I have also observed this with the current web app. The Inbox folder reports one fewer unread messages than are actually present. The WebsocketCounterData structure seems to contain -1 for the Inbox count at line MailModel.js line 244 if there are no unread messages. Other folders display the correct value.

**Comment by x80486** [comment] 2019-10-17 22:41
There is currently a glitch on the app for this; it doesn't work in the mobile nor in the Web...using the very latest.

**Comment by charlag** [comment] 2019-12-10 14:14
duplicate of #1267

**Closed by charlag** 2019-12-10 14:14 UTC
Labels: bug
