### ISSUE TITLE
415: ResourceError

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2391] opened 2020-11-02 14:40 UTC
We're getting alot of these errors in feedback:

Client: Browser
Type: FREE
Tutanota version: 3.77.1
Timestamp (UTC): Sat, 31 Oct 2020 04:39:33 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
ResourceError
Error message: 415: | DELETE /rest/tutanota/contact/M2eIkPS--B-2/MJqJ-a5----2
Stacktrace:
ResourceError. 415: | DELETE /rest/tutanota/contact/M2eIkPS--B-2/MJqJ-a5----2
ResourceError@https://mail.tutanota.com/common.js:1:267600
@https://mail.tutanota.com/common.js:1:257537
value/

from when people are trying to delete a contact. It's also happening on DELETE /rest/sys/session/

It looks like the server is just sending back a 415 and client defaults to throwing a ResourceError in that case as we don't handle it specifically.

Not sure where this 415 is coming from

**Comment by charlag** [comment] 2020-11-02 14:42
I had one user in support who got stuck on tab closing and seems like the problem is similar

**Comment by charlag** [comment] 2020-11-02 14:43
https://github.com/tutao/tutanota/blob/master/src/api/main/UserController.js#L187-L232

**Comment by johnbotris** [comment] 2020-11-05 13:01
Navigator.sendBeacon makes a request with Content-Type=text/plain. we should handle this as an exception on the server if we can't tell beacon which content type to use. 
This is maybe not the root cause for the other cases?

**Comment by charlag** [comment] 2020-11-17 08:30
I believe that when 415 when removing contacts is a browser bug. For all the reported cases it occurs with Firefox older than current ESR (which we shouldn't support and neither does mithril). It's always 44 (what), 52, 53 (WaterFox), 68 (PaleMoon?)

**Comment by charlag** [comment] 2020-11-17 09:27
I tried to download Firefox 68.0.1 ESR from here http://ftp.mozilla.org/pub/firefox/releases/ and indeed it does send text/plain, maybe because there's no content?

```
Host: mail.tutanota.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
accessToken: REDACTED
v: 42
cv: 3.77.4
Content-Type: text/plain;charset=UTF-8
Content-Length: 0
Connection: keep-alive
TE: Trailers
```

I think it's because we don't set Content-Type when there's no body:

https://github.com/tutao/tutanota/blob/c76ca300e0335807fb462ea578509b1e38cb97ac/src/api/worker/rest/RestClient.js#L156-L170

But setting it without body also feels wrong.

**Closed** 2020-11-19 10:11 UTC
Labels: bug

**Comment by charlag** [comment] 2020-11-20 09:42
Session was closed when I tested
