### ISSUE TITLE
Contact syncing not working on Android with some contact apps

### ISSUE THREAD

**Issue by dorianve** [tutao/tutanota#6568] opened 2024-02-16 18:39 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
I wanted to try the new "contact syncing feature" that was presented in a blog post, I activated the setting, but contacts are not syncing.

**To Reproduce**
1. Go to tuta android app 'settings'
2. Click on 'contacts'
3. Enable "contact synchronization"
4. Tuta now has an "account" in android seetings
5. The contacts do not sync. It says "synchronization is disabled for all element" (with no possibility to enable anything)
6. Clicking on the "account sync", it's blank, there is no element to sync

**Expected behavior**
The contacts should sync.

**Screenshots**
![Screenshot_20240216-192343-275](https://github.com/tutao/tutanota/assets/48653005/ed8313f0-04de-4654-abc1-3fd6817120b6)
![Screenshot_20240216-192254-055](https://github.com/tutao/tutanota/assets/48653005/32bab2a1-4020-47db-be85-1beca880e41b)
![Screenshot_20240216-192452-266](https://github.com/tutao/tutanota/assets/48653005/668ed0a0-3551-4d3c-91f1-0aa73f3a4fb8)
![Screenshot_20240216-193139-948](https://github.com/tutao/tutanota/assets/48653005/85e2da3b-2b61-421c-a3e7-f271d5afcb48)

**Smartphone (please complete the following information):**
 - Device: Motorola moto G 5G (kiev)
 - OS: Android 11 (stock version)
 - Version: Tuta  3.122.4, fdroid (also uninstalled and reinstalled on the play store: same behaviour)

**Additional context**
"Revolutionary" plan

 I will be happy to provide more context if needed, please tell me what you need.

## Test notes
Test on an Android device with Fossify Contacts installed. Turn contact synchronization off if it is already on.
- [x] After turning on contact synchronization, the contacts from the tuta account appear in Fossify Contacts.
- [x] After turning off contact synchronization, the contacts from the tuta account disappear in Fossify Contacts.
- [x] Turn contact synchronization back on
- [x] Creating a new contact in Fossify Contacts causes the same contact to appear in Tuta Mail.
- [x] Creating a new contact in Tuta Mail causes the same contact to appear in Fossify Contacts.
- [x] Editing a contact in Fossify Contacts causes the same contact to change in Tuta Mail.
- [x] Editing a contact in Tuta Mail causes the same contact to change in Fossify Contacts.
- [x] Editing multiple contacts in Fossify Contacts causes the same contacts to change in Tuta Mail.
- [x] Editing multiple contacts in Tuta Mail causes the same contacts to change in Fossify Contacts.
- [x] Deleting a contact in Fossify Contacts causes the same contact to disappear in Tuta Mail.
- [x] Deleting a contact in Tuta Mail causes the same contact to disappear in Fossify Contacts.

**Comment by dorianve** [comment] 2024-02-19 22:41
Hi,

Thanks for your answer.

I see the issue was closed but the bug remains: the contacts created in the tuta app are not showing in the phone contact list.

Since the contacts were not syncing, I was looking around and found it odd no 'sync element' was showing in the Android Sync settings. 

I thought it was probably not the expected behaviour, and maybe an indication of where the bug was stemming from, but since it's expected: why do you think could be the cause for the tuta contacts not showing in the phone contact app, then?

If it wasn't clear, the article on the tuta blog describes the expected behaviour "**creating a contact in your Tuta account will automatically sync to your device contacts**".
However, creating a contact in the tuta app, even though "contacts synchronization" is enabled, does absolutely nothing; **the newly created contact is still only available in the tuta app, not phone contact app**

Tuta blog article: https://tuta.com/blog/full-device-contact-integration-is-here

**Comment by charlag** [comment] 2024-02-20 08:33
Hey, sorry for misunderstanding.
When tuta contacts are synced you should see a new account in your contacts app (the same one you've found in setting). Do you see it there? can you filter to show contacts for that account?
Apologies if you already checked that.

**Comment by SteamPumkin** [comment] 2024-02-27 22:29
This is not an isolated issue, I unfortunately have the same problem.

**Issue:** Contact synchronisation is activated in Tuta android app, yet contacts are not appearing in my phone's contacts app.

Specifically, I have tried viewing contacts in both my OS default contacts app (Google Contacts) and in an F-Droid downloaded contacts app called 'Fossify Contacts'. Neither has any contacts from Tuta appearing.

**Device:** Oppo A54 5G
**Android OS:** ColorOS 13.0 (Android 13)
**Tuta Version:** 218.240219.0 (F-Droid Version)

Currently I'm on the free plan (moving to revolutionary plan soon when my current custom domain email hosting package with another provider ends - I will update if anything changes)

**Comment by dorianve** [comment] 2024-02-28 06:48
Hi, 

I'm also using fossify Phone and Contacts, and Tuta is not showing as synced account in the filter list.

The default Google Contacts app that came with the device was disabled, but I reenabled it temporarily to see what was happening. And, there, in my case, Tuta contacts actually do show up.

I found that surprising and digged a little in the direction of fossify. It appears that it has open issues related to synced contact account not showing (the issue is accounted for since "Simple Contacts" Fossify was forked from). So, maybe the issue is on Fossify's side?
https://github.com/FossifyOrg/Phone/issues/28

But then again, @SteamPumkin just mentionned having the issue with the default Google app ⬆️

**Comment by SteamPumkin** [comment] 2024-02-28 16:23
@dorianve you're absolutely right.

I thought they weren't showing in Google Contacts but I must have not checked properly/not realised it was merging my Google and Tuta duplicate contacts. I've just re-enabled my Google Contacts app and checked and Tuta contacts are showing there. Good find!

This issue must in fact be with the Fossify Contacts/Phone/Messages apps, please disregard.

**Comment by charlag** [comment] 2024-02-29 08:56
We are writing "raw contacts" to Android to a separate account from Google. Android is designed to merge raw contacts from different sources into a user-visible "contact".

If you want to see only tuta info you should filter by an account in your contacts app.

**Comment by gmanaud** [comment] 2024-08-10 10:27
Hi,
I have exactly the same problem with /e/ OS (Android 12) on my GS290 and tuta app 235.240712.0.

The app add a Tuta account in Android settings, but it doesn't synchronize and there is no possibilty to activate it.

**Comment by ivoarch** [comment] 2024-08-22 12:02
I can confirm that I have same issue on my GrapheneOS (Pixel 6 PRO) . For now Tuta only sync changes makes in Tuta > Contact app .

Enabled sync in Tuta app ✅
Permission given to Tuta app ✅
APK - Gplay, Fdroid (ssme issue)
Current Ver: v240.240816.0

in my default GOS contacts app from menu > Create contact > In the option to "Save to" I see only Device or Gmail . Tuta is missing ?  Also Tuta account is missing from Contact app and , when I try to add manualy nothing happen, just send to previos screen with no tuta added .

````
type: logcat
osVersion: google/raven/raven:14/AP2A.240805.005.F1/2024080600:user/release-keys
buffers: main,system,crash,events,kernel
level: verbose
filterRegex: tutanota

--------- beginning of crash
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: FATAL EXCEPTION: main
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: Process: de.tutao.tutanota:pushprocess, PID: 4562
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{58e98a1 u0 de.tutao.tutanota/.push.PushNotificationService c:android}
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2250)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2221)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2527)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8623)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-18 06:29:16.375 10329  4562  4562 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
--------- beginning of system
08-22 11:35:16.920  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:35:53.098  1000  1467 12300 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:35:53.102  1000  1467  2834 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:35:53.112  1000  1467  1995 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:37:00.237  1000  1467  2644 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:37:00.240  1000  1467 12300 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:37:00.252  1000  1467  1995 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:37:10.528  1000  1467 11446 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:37:10.534  1000  1467 12300 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:37:10.554  1000  1467  1995 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:37:41.942  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:37:41.953  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:01.221  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:01.646  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:02.015  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:02.023  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:13.962  1000  1467 13497 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:38:13.965  1000  1467 13497 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:38:13.979  1000  1467  1995 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:38:14.801  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:15.268  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:15.659  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:15.669  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:30.096  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:30.745  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:32.028  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:32.562  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:34.768  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:35.561  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:36.997  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:37.533  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:43.993  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:44.694  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:45.228  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:45.761  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:58.509  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:38:59.155  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:39:01.060  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:39:23.505  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:39:24.643  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:39:25.185  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:02.198  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:02.863  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:03.003  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:03.548  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:07.873  1000  1467 12300 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:40:07.891  1000  1467  1995 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:40:08.440  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:08.852  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:09.248  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:09.253  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:23.150  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:24.490  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:25.068  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:26.638  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:26.737  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:26.739  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:44.160  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:44.815  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:45.522  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:40:45.903  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:41:48.656  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:41:49.316  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:41:52.192  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:41:52.722  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:41:52.885  1000  1467  2641 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:42:13.849  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:42:14.417  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:44:33.288  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:44:33.301  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:45:23.229  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:45:23.794  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:45:29.437  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:45:31.450  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:45:32.040  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:45:32.049  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:45:33.736  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:45:33.744  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:45:33.854  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:45:33.858  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:46:54.927  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:46:55.871  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:46:56.262  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:46:56.272  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:46:57.938  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:46:58.353  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:46:58.729  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:46:58.734  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:46:59.754  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:47:00.237  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:47:00.582  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:47:00.587  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:47:21.369  1000  1467  2651 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:47:21.386  1000  1467  1995 E ClipboardService: Denying clipboard access to de.tutao.tutanota, application is not in focus nor is it a system service for user 0
08-22 11:47:21.923  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:47:22.364  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:47:22.727  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:47:22.735  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:48:28.829  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:48:29.513  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:48:36.027  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:48:36.617  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
--------- beginning of main
08-22 11:48:47.586  1000  2378  2378 D AccountPrefController: No sync authorities for account type: de.tutao.tutanota
08-22 11:48:47.619  1000  2378  2378 D AccountPrefController: No sync authorities for account type: de.tutao.tutanota
--------- switch to system
08-22 11:48:48.060  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
--------- beginning of events
08-22 11:48:51.503  1000  2378  2378 I sysui_multi_action: content=[757,830,758,4,833,10,854,de.tutao.tutanota]
--------- switch to system
08-22 11:48:51.525  1000  1467 13497 D ActivityManager: sync unfroze 25137 de.tutao.tutanota for 6
08-22 11:48:51.529  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
--------- switch to events
08-22 11:48:51.531  1000  1467  1867 I am_unfreeze: [Pid=25137,Process Name=de.tutao.tutanota,6]
--------- switch to main
08-22 11:48:51.566 10329 25137 25208 W AccountAuthenticator: addAccount(de.tutao.tutanota)
08-22 11:48:51.566 10329 25137 25208 W AccountAuthenticator: java.lang.NullPointerException: Parameter specified as non-null is null: method de.tutao.tutanota.credentials.AccountManagerAuthenticator.addAccount, parameter authTokenType
08-22 11:48:51.566 10329 25137 25208 W AccountAuthenticator: 	at de.tutao.tutanota.credentials.AccountManagerAuthenticator.addAccount(Unknown Source:12)
08-22 11:48:51.566 10329 25137 25208 W AccountAuthenticator: 	at android.accounts.AbstractAccountAuthenticator$Transport.addAccount(AbstractAccountAuthenticator.java:162)
08-22 11:48:51.566 10329 25137 25208 W AccountAuthenticator: 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:224)
08-22 11:48:51.566 10329 25137 25208 W AccountAuthenticator: 	at android.os.Binder.execTransactInternal(Binder.java:1534)
08-22 11:48:51.566 10329 25137 25208 W AccountAuthenticator: 	at android.os.Binder.execTransact(Binder.java:1468)
08-22 11:48:51.597  1000  2378  2378 D AccountPrefController: No sync authorities for account type: de.tutao.tutanota
--------- switch to system
08-22 11:48:55.007  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:48:56.251  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:48:56.650  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:49:01.027  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:49:01.571  1000  1467  1867 D ActivityManager: freezing 25137 de.tutao.tutanota
--------- switch to events
08-22 11:49:01.573  1000  1467  1867 I am_freeze: [Pid=25137,Process Name=de.tutao.tutanota]
--------- switch to system
08-22 11:49:06.431  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
--------- switch to events
08-22 11:49:06.533  1000  1467  1655 I am_cpu  : [Pid=25137,UID=10329,Base Name=.tutao.tutanota,Uptime=5210.074s,Stime=90ms,Utime=20ms]
--------- switch to system
08-22 11:49:41.552  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:49:51.579  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:51:45.621  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:51:46.428  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:51:48.159  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:51:51.302  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:51:51.675  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:52:28.130  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:52:29.761  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:52:30.129  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:52:30.137  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
08-22 11:52:33.397  1000  1467  1855 W JobScheduler.JobStatus: Exempted app de.tutao.tutanota considered buggy
--------- switch to main
08-22 11:52:34.742 10141 18895 18895 D LogcatActivity: command: logcat --buffer=main,system,crash,events,kernel -d --dividers --format=UTC,printable,descriptive --regex=tutanota *:V --uid=10076
08-22 11:52:44.389 10141 18895 18895 D LogcatActivity: command: logcat --buffer=main,system,crash,events,kernel -d --dividers --format=UTC,printable,uid,descriptive --regex=tutanota *:V
```
`

**Comment by charlag** [comment] 2024-08-22 12:04
Hi, we plan to look into this issue soon, it looks like some contacts apps don't let you save to Tuta account but some do (like Google Contacts) and we need to investigate what is missing

**Comment by Mangoes** [comment] 2024-09-13 17:22
This still doesn't work on Grapheneos. (With the fixed version released today)

Everything is the same as was reported originally. (Only 1 way sync tuta>contacts works).

Logging in, out, uninstalling/reinatalling the app... It doesn't work.

Tuta has all of the authorizations, including contacts, enabled.

Please reopen this issue.

**Comment by charlag** [comment] 2024-09-13 17:34
@Mangoes 
Re-enabling sync should be enough for e.g. Fossify contacts to see the app as a valid destination. What app are you testing it with?

**Comment by Mangoes** [comment] 2024-09-13 18:37
> Re-enabling sync should be enough for e.g. Fossify contacts to see the app as a valid destination. What app are you testing it with?

It works with the Fossify contacts.

But not with the Grapheneos default contacts. I also see that the Grapheneos contacts only appears to create the contacts on the device (there is no mention of the tuta account in the contacts app settings, but clicking on the accounts option in the contacts app settings > it opens the system accounts settings and the tuta account is there).

In the Grapheneos contacts app settings, there is an option to select the default account for newly created contacts, but the only option available is "on device".

**Comment by tomcolley1962** [comment] 2024-09-14 05:48
Like @Mangoes , I too am using GrapheneOS Contacts with Tuta and finding that sync occurs only one-way: from Tuta to Contacts. For example:
- a new contact created in Tuta will be seen in the GrapheneOS contacts app
- a new contact created in GrapheneOS will NOT be seen in the Tuta app
Like @Mangoes , I also find that the GrapheneOS Contacts app allows me to choose which account to save a new contact to, but it shows no option for Tuta. This happens even though Tuta shows as one of my accounts under Phone Settings > Passwords, passkeys and autofill > Accounts for [user]

**Comment by Mangoes** [comment] 2024-09-21 17:36
@charlag  Why is this bug still marked as closed?

Or should we open a new issue?

**Comment by charlag** [comment] 2024-09-30 07:25
I would suggest asking GrapheneOS devs what heuristics they use for showing contact sync providers. It could be that there's something also wrong on our side but it would need some investigation and if there's something to fix on our side I would open another issue.

**Comment by charlag** [comment] 2024-10-01 07:31
I did some digging into AOSP and if I understand it right then it looks for certain properties in the manifest:
https://android.googlesource.com/platform/packages/apps/Contacts/+/refs/heads/main/src/com/android/contacts/model/account/ExternalAccountType.java#368

which is further confirmed by this SO answer:
https://stackoverflow.com/a/33788621/1923879

so I think we need to experiment with AOSP app or a fork of such and declaring more things in the manifest.

**Comment by marcosdiasalves** [comment] 2024-10-11 03:24
I observe exactly the same situation using Google Contacts on on two Samsung devices (a smartphone and a tablet) both running Android 14 One UI 6.1. 
Tuta is not listed when adding a contact on Google Contacts. Tuta account on settings is deactivated for syncing.
Removed and reinstalled the app several times as well turned the contacts sync off/on - nothing helps.

**Comment by charlag** [comment] 2024-10-11 07:58
@marcosdiasalves I wanted to write that we never had a problem with Google Contacts but I could not actually get it to work now. We will look into that.

**Closed** 2024-11-21 15:00 UTC
Labels: bug, android, goal: mobile integration, feature: phone book

**Comment by charlag** [comment] 2024-12-05 08:53
@Elaborendum hi, thank you for the update. We are unsure how to approach this since we don't know how OneUI is deciding which accounts can be used to store contacts.
