### ISSUE TITLE
Shortcuts appear multiple times in help dialog

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1876] opened 2020-03-05 12:45 UTC
How to reproduce:
1. Switch between mail view and settings view a couple of times
2. Press F1
-> the keyboard shortcut group switch to mail/contact/calendar/logout is shown multiple times

Seems not to be client specific. Can be reproduced at least in web and desktop client.

**Comment by vitoreiji** [comment] 2020-03-05 12:50
Duplicate of #1700

**Closed by vitoreiji** 2020-03-05 12:50 UTC
Labels: bug
