### ISSUE TITLE
Duplicate event after update

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2509] opened 2020-12-21 10:28 UTC
user report:

>When creating an event that spans midnight and then is edited to all occur on the same day causes a second event to be created with the same name.
Start with an empty calendar.
Create an event that spans midnight. This event goes from 11:30m on September 1 to 12:30pm on September 2. The event duration is 1 hour. Create the event with several notifications.
You should now have the event showing up in your calendar.
Edit the event so that its duration in 15 minutes and the entire event takes place on September 1. Save the event.
Looking at the calendar, there are now two events with the same title.

I was able to reproduce it. After reloading the page there is only one event so it is an error with finding the right event to update after we receive ws message.

**Comment by mandm-pt** [comment] 2021-05-07 10:44
I received an update of an event today (a 1h meeting that now is 30 min), and I am not sure is duplicated for me because I only see 1 slot booked in the calendar (maybe if I delete the 1 hour slot, underneath there's a 30 min slot, not sure) but in the calendar I still see the 1h booked. I was expecting to see the event updated

**Comment by johnbotris** [comment] 2021-11-17 09:30
@sarashub That would mean that this is fixed then? I can't reproduce it so I will close this for now

**Closed by johnbotris** 2021-11-17 09:30 UTC
Labels: bug, duplicate
