### ISSUE TITLE
Secret storage issue on Windows 11

### ISSUE THREAD

**Issue by njmulsqb** [tutao/tutanota#7270] opened 2024-07-24 15:54 UTC
- [x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x ] I've searched and did not find a similar issue.

**Describe the bug**
I am facing https://tuta.com/support/#secretstorage issue on Windows 11, tried reinstalling the client but the issue persist.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Desktop Environment, if applicable (on Linux)

**Additional context**

**Comment by charlag** [comment] 2024-07-25 09:38
Duplicate of #7247

**Closed by charlag** 2024-07-25 09:38 UTC
Labels: bug, desktop
