### ISSUE TITLE
Clicking the notification should take you to related mailbox

### ISSUE THREAD

**Issue by snaggen** [tutao/tutanota#1076] opened 2019-02-01 16:23 UTC
Currently with 3.46.3 on android, when I get a mail that is sorted to a mailbox, I get a notification. Then I click the notification,  but is then taken to my empty Inbox. My expectation was to be taken to the mailbox for the mail in the notification.  If only one mail was received, maybe go directly and show that mail. 
If the notification is for multiple mails in multiple mailboxes, it should probably take me to the mailbox for the first one.

**Comment by charlag** [comment] 2019-02-04 08:22
Hey, thanks for reporting, it *should* work like that but it stopped at some point of time and I didn't look into that yet.

**Comment by gpa** [comment] 2020-03-28 12:53
I'm also affected by this but slightly differently,
When the app is not running in the background and I get a new email notification and click on it I'm taken to the login screen as in the image below and then nothing happens. 
First of all it took me a really long time to figure out that I have to click the red panel to select the account, secondly why would I have to do it, I only have a single account and I don't have to select it when I open the app directly.
![20200328_134823](https://user-images.githubusercontent.com/18526190/77823394-29496700-70fb-11ea-8f96-996129cc84cd.jpg)

**Comment by bedhub** [comment] 2020-06-25 07:30
More information from a user:

"This only happens if the app has not been previously opened (for example, after booting the phone or if removed from the recent applications list). If the app has been previously opened, when clicking on the notification I go directly to the email message, which should be the expected behaviour in every case."

**Comment by snaggen** [comment] 2020-06-25 07:35
Actually tested with the notification for this. I first opened the tutanota app, it was in a subfolder. I then clicked the notification, which should have taken me to the new message in the bugs subfolder. However, the result was that Tutanota was shown but with the Index folder list showing.
So clicking on the notification clearly instructed the tutanota app to do something, since it changed from a subfolder to the index folder, but it did not open the correct mail in my bugs subfolder as expected.

**Comment by bedhub** [comment] 2020-07-21 11:12
Seems to be an annoying bug as it is still reported by users. We will try to fix this for the next release. We should also take care of this issue maybe it is related:

https://github.com/tutao/tutanota/issues/1426

**Comment by johnbotris** [comment] 2020-10-20 11:43
notes for testing:
click on email notifications while already in a mailbox (of the same and of a different user), while viewing the login screen, while the app is in the background and while an app instance isn't running, and make sure that the correct mailbox is opened up.

**Comment by charlag** [comment] 2020-10-22 07:45
Closed by https://github.com/tutao/tutanota/commit/3b3b9812dd20aa50971c2fdc2a3d36811fd53422

**Closed by charlag** 2020-10-22 07:45 UTC
Labels: android, bug
