### ISSUE TITLE
Not possible to clear text selection: context menu remains onscreen

### ISSUE THREAD

**Issue by Jackalaq** [tutao/tutanota#6079] opened 2023-11-03 08:03 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
After selecting text in an email, the context menu appears [Copy  |  Share  |  Select all  |  Search]
It is then impossible to cancel the selection. Single clicking elsewhere does nothing and hitting Android back button closes the email. Reopenning the same email shows selection still current and context menu open, which is a nice feature actually.
Selecting different text is possible, but is not the desired action.

**To Reproduce**
1. Clearly described above.

**Expected behavior**
Single click on other text would cancel selection and make context menu disappear.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T Pro
 - OS:  /e/ v1.16
 - Version: Android T

**Additional context**

**Comment by rezbyte** [comment] 2023-11-13 12:04
Duplicate of #2873

**Closed by rezbyte** 2023-11-13 12:04 UTC
Labels: bug, state:duplicate
