### ISSUE TITLE
Duplicate entries in Keyboard shortcuts popup (F1)

### ISSUE THREAD

**Issue by 2ynn** [tutao/tutanota#3206] opened 2021-06-21 22:36 UTC
- using desktop AppImage on void linux
- many duplicate keybindings are listed when pressing F1
- attached is a sample of some duplicates (e.g. the same `UP = select previous` appears 4 times)

![screenshot_2021-06-21_18:29:06](https://user-images.githubusercontent.com/41802320/122835584-9e83f780-d2be-11eb-83bf-84f2eaa94919.png)

If someone can give me some guidance on which files to look at I'd be down to help investiguate more.

Thanks!

**Comment by johnbotris** [comment] 2021-06-22 06:59
This is a duplicate of #3008, the fix is out in the webclient but the new desktop version isn't released yet

**Closed by johnbotris** 2021-06-22 06:59 UTC
