### ISSUE TITLE
Can't login on desktop client after update to 3.91.9

### ISSUE THREAD

**Issue by Neyl-123** [tutao/tutanota#3877] opened 2022-02-08 11:50 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Login fails after update to Flatpak version 3.91.9

**To Reproduce**
1. Open the desktop client
2. Login
    - Autologin after opening the client
    - Click on the button with the accounts email address

**Expected behavior**
Successful login

**Desktop:**
 - OS: Pop!_OS 21.10
 - Desktop Environment: GNOME 40.4.0

**Additional context**
Error message:
```
Feedback v3.91.9 - Error - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.91.9
 Timestamp (UTC): Tue, 08 Feb 2022 11:13:16 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.91.9 Chrome/96.0.4664.110 Electron/16.0.8 Safari/537.36
Error
 Error message: invalid mac
Stacktrace: 
Error: invalid mac
    at os (file:///app/lib/tutanota/resources/app.asar/worker.js:1:38652)
    at Wu.decrypt (file:///app/lib/tutanota/resources/app.asar/worker.js:12:130667)
    at file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:5590
    at C.handleMessage (file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:7598)
    at file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:6851
    at _worker.onmessage (file:///app/lib/tutanota/resources/app.asar/common-1f953fca.js:1:6431)

```

**Comment by HarlemSquirrel** [comment] 2022-02-08 12:54
Not sure what happened but I was able to get it working again by uninstalling the flatpak, deleting `~/.var/app/com.tutanota.Tutanota/config/tutanota-desktop`, and then installing the flatpak again.

**Comment by charlag** [comment] 2022-02-08 14:00
The issue was, unsurprisingly, keytar, we worked around it and now we want to clean up remaining problems related to it.

**Comment by charlag** [comment] 2022-02-08 14:01
Duplicate of #3875

**Closed by charlag** 2022-02-08 14:01 UTC
Labels: bug, desktop
