### ISSUE TITLE
Each time you start the app from the launcher the new render process is started

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1164] opened 2019-03-10 08:43 UTC
**Describe the bug**
Each time you open a Tutanota window it spins up a new render process. When you close the window it is not removed.

**To Reproduce**
1. Open Tutanota
2. Close window with close button
3. Open Tutanota again

**Expected behavior**
There's only one render process.

**Screenshots**
![Screenshot from 2019-03-10 09-40-03](https://user-images.githubusercontent.com/3099142/54082604-bbc47000-4318-11e9-8353-801b21a8e07b.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Desktop Environment: GNOME 3.30.2
 - Version: 3.48.1

**Comment by ganthern** [comment] 2019-03-19 13:18
duplicate of #1186

**Closed by ganthern** 2019-03-19 13:18 UTC
Labels: bug, desktop
