### ISSUE TITLE
 PreconditionFailedException is not handled correctly when adding WhitelabelDomain 

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1898] opened 2020-03-12 09:08 UTC
* Add a whitelabel domain to customer a.
* Try to add same domain for customer b.

-> Unknown error dialog appears.

Expected: Error dialog with message "Domain is not available/ already in use"

**Comment by mpfau** [comment] 2020-03-12 14:17
duplicate of server error https://next.tutao.de/gitlab/tuta/tutadb/issues/387

**Closed by mpfau** 2020-03-12 14:17 UTC
Labels: bug
