### ISSUE TITLE
mails unreadable on android app

### ISSUE THREAD

**Issue by nikoPLP** [tutao/tutanota#5246] opened 2023-03-10 07:56 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

**To Reproduce**
1.open app on android
2. tap on an email title
3. Scroll down and see there is no body of the email
4. notice a 3 doted button that does nothing

**Expected behavior**
the body of the email should be displayed below the title and the subject and date
it was working well until few days ago.

**Screenshots**
see attached screenshot
![Screenshot_2023-03-09-11-49-03-810_de tutao tutanota](https://user-images.githubusercontent.com/57370730/224256781-c63dd730-8719-4faa-882c-81ca42c09c4c.jpg)

**Smartphone (please complete the following information):**
 - Device: redmi 7a
 - OS: android 10
 - Version of tutanota app 3.110.0

**Additional context**
i didnt do any upgrade of the app or of the OS recently

**Comment by charlag** [comment] 2023-03-10 08:29
There's a very good chance your webview is very old
https://tutanota.com/faq#webview

duplicate of #5221

**Closed by charlag** 2023-03-10 08:29 UTC
Labels: bug

**Comment by nikoPLP** [comment] 2023-03-11 08:44
Hello, 
thanks for the pointer to the other issue.
It was indeed a problem with the webview.

2 feedbacks on that :
- i followed your guide about update the webview. it turns out on my android, the situation is different from what you have described. I am running Android 10 and I have google chrome app installed. I updated it, but it did not solve the issue. Then i went to developers settings, and saw the default webview implementation was android system webview version 87. i searched for this app "android system webview" in the google play store, but it was not installed (i guess the webview i had was very old and was bundled with the OEM android i got from the phone manufacturer). So i installed the webview app, and then went again in the programming settings where i could now see a second "Android System Webview" with the "Dev" suffix, and version 113, and i switched to this newer version as default. And then, and only then, did tutanota app started to display the email bodies again. You could possibly update your guide about how to troubleshoot. I saw you did a commit 2 days ago to address the silent failure of the webview. I hope that the next version of tutanota app will display some message to the user in case of failure with the webview, because i believe it might affect quite a lot of users (free users like me i guess) and they will not find an easy way to contact you about this technical failure, and they will just stop using your amazing app. As a developer myself, I found a way to reach you, but the normal user will not. And they wont upgrade to premium in order to get support, so the consequence will just be a drop in your user base. I take this opportunity to thank you for your great work and service ! When I will be able to afford it I will upgrade to premium. 
- second feedback is that you could have waited that i confirm the resolution of the issue (5246) before closing it.

**Comment by charlag** [comment] 2023-03-13 09:17
Hey, thanks for the confirmation, yes, usually we show the message about the outdated webview but in this case we've missed adding a CSS compatibility checks, that's why so many people are affected by this bug now.

We should update FAQ entry though, thank you for pointing it out

**Comment by nasi87** [comment] 2023-03-19 12:01
Hello,
so I have this bug too on my smartphone and fail to fix it.
I'm using latest SailfishOS (4.5) which has Android App Support (something like an emulator/virtual environment for Android). 
The installed WebView version is pretty old (83...) even if the Android Version itself is not that old - Android 11 with API Level 30. 
I can't update WebView. PlayStore is not available and not an option. If I try to update with AuroraStore I get an error due to missing Trichromelibrary. If I install different versions of said library and WebView downloaded from apkmirror.com they get installed but I can't choose to use them. The system still uses the old default WebView. 
So I'm kind of stuck and can't use Tutanota on my smartphone anymore. Tutanota version 3.109.4 is working but I get an email that I need to update.

**Comment by nasi87** [comment] 2023-03-31 11:41
Thanks for that answer. That's what I assumed (regarding your support) and totally understand.
Unfortunately the developer settings don't show any other installed version to select. It's like they don't exist for Sailfish Android App Support no matter which version I try to install. 
There are other users affected by this issue so we hope there will be a solution provided by Sailfish/Jolla (see https://forum.sailfishos.org/t/tutanota-does-not-work-anymore/15250).
