### ISSUE TITLE
Tutanota Desktop won't re-create secret

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3244] opened 2021-07-05 11:32 UTC
User feedback

> Per the title, Tutanota Desktop doesn't create a new secret (in Seahorse or KeePassXC) after removing an previous secret
> I removed the secret from my KeePassXC database, but a new secret won't manifest in KeePassXC or GNOME Keyring (Seahorse).
> I also tried removing the .config and .cache Tutanota subdirectories with no change.

![Region_28-06-21_15-00-35](https://user-images.githubusercontent.com/8296817/124465499-ccc10700-dd95-11eb-9dc4-d9acfb283e04.png)

**Comment by kibhub** [comment] 2022-05-18 12:03
Could not recreate as of client v3.96.3
Tested Gnome Keyring (Seahorse) and KeepassXC
OS: Manjaro Gnome Edition

**Steps**
- login using the desktop client and store credentials
- open Keyring or KeepassXC and delete credentials
- log out if client still open or open client again
- upon trying to login again new secret is created

**Comment by Kaoticz** [comment] 2024-01-15 16:29
I've recently been hit with this issue on version 3.120.4, AppImage release, using the KeePassXC secret integration.
This is the error that I get on the client:
```
Feedback v3.120.4 - DeviceStorageUnavailableError - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.120.4
 Timestamp (UTC): Mon, 15 Jan 2024 16:23:56 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.120.4 Chrome/116.0.5845.228 Electron/26.6.2 Safari/537.36
DeviceStorageUnavailableError
 Error message: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Pw.getPassword (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async oR.fetchKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210958)
    at async oR.fetchOrGenerateKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210685)
    at async kb.decryptUsingKeychain (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:286982)
    at async ipc (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:297200)
Stacktrace: 
DeviceStorageUnavailableError: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Pw.getPassword (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async oR.fetchKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210958)
    at async oR.fetchOrGenerateKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210685)
    at async kb.decryptUsingKeychain (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:286982)
    at async ipc (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:297200)
    at oR.fetchOrGenerateKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210859)
    at async kb.decryptUsingKeychain (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:286982)
    at async ipc (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:297200)
```

And this is what I get when I execute the application from the terminal:
```
$ /usr/bin/tutanota-desktop 
the monkey has been patched pid: 5731
(node:5731) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 13:06:02.914: Failed to load module "appmenu-gtk-module"
version:   3.120.4
resolving key... tutanota-vault
config up to date
libva error: vaGetDriverNames() failed with unknown libva error
[2024-01-15T16:06:04.661Z] using safeStorage with backend gnome_libsecret
Failed to resolve/generate key:  tutanota-vault Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Pw.getPassword (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async oR.fetchKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210958)
    at async oR.fetchOrGenerateKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210685)
[2024-01-15T16:06:06.057Z] Create tray:true
resolving key... tutanota-vault
[ApplicationWindow] webAssetsPath:  /opt/tutanota-desktop/resources/app.asar
[ApplicationWindow] getting dictionaries from: https://app.tuta.com/desktop/dictionaries/
default mailto handler: false
Webapp ready
[2024-01-15T16:06:06.128Z] [ElectronUpdater] WARN: APPIMAGE env is not defined, current application is not an AppImage
[ApplicationWindow] spellcheck-dictionary-initialized en-US
desktop file exists, checking version...
version mismatch, reintegrating...
Failed to resolve/generate key:  tutanota-vault Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Pw.getPassword (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async oR.fetchKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210958)
    at async oR.fetchOrGenerateKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210685)
[DesktopWindowManager] Failed to get sseInfo W [DeviceStorageUnavailableError]: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Pw.getPassword (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async oR.fetchKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210958)
    at async oR.fetchOrGenerateKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210685)
    at oR.fetchOrGenerateKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210859)
unable to start sse client W [DeviceStorageUnavailableError]: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Pw.getPassword (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async oR.fetchKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210958)
    at async oR.fetchOrGenerateKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210685)
    at oR.fetchOrGenerateKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210859)
resolving key... tutanota-credentials
Failed to resolve/generate key:  tutanota-credentials Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Pw.getPassword (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async oR.fetchKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210958)
    at async oR.fetchOrGenerateKey (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:210685)
    at async kb.decryptUsingKeychain (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:286982)
    at async ipc (/opt/tutanota-desktop/resources/app.asar/desktop/DesktopMain.js:5:297200)

(tutanota-desktop:5731): LIBDBUSMENU-GLIB-WARNING **: 13:06:06.484: About to Show called on an item wihtout submenus.  We're ignoring it.

(tutanota-desktop:5731): LIBDBUSMENU-GLIB-WARNING **: 13:06:06.485: About to Show called on an item wihtout submenus.  We're ignoring it.
```
It used to work fine on version `3.119.x`. I didn't change my KeePassXC setup, so I don't know what could've caused this issue.

**Comment by kibhub** [comment] 2024-01-16 08:51
closing this issue as irrelevant

**Closed by kibhub** 2024-01-16 08:51 UTC
Labels: bug, desktop

**Comment by Kaoticz** [comment] 2024-01-16 15:09
Writing to confirm that the issue is gone after deleting `~/.config/tutanota-desktop`. Thanks for the tip.
