### ISSUE TITLE
[Regression] Newly created folders cannot receive action

### ISSUE THREAD

**Issue by MasterInQuestion** [tutao/tutanota#7687] opened 2024-10-08 06:33 UTC
E.g. moving emails into; or deleting the folder just created: Seemingly as if no-op.
    Console warning:
    "Mailbox detail for mail folder does not exist"
    .
    Reloading the client (web page) to workaround.

    Likely recent regression: 246.241002 -> 244.240917

## Test notes
 - [ ] Create a new folder. Switching to that folder should work.
 - [ ] Create a new folder. Moving mails to that folder should work.
 - [ ] Create a new shared mailbox. Add yourself to that shared mailbox. It should correctly show up in mail view with all folders without reloading. Creating subfolders in that mailbox works. Folder interactions with that mailbox works.
 - [ ] Creating and displaying inbox rules works. It also works in the presence of multiple mailboxes.
 - [ ] Opening folder by URL should work.
 - [ ] Inbox rules are applied correctly still.
 - [ ] Moving mails works, also via dropdown. Move destinations are filtered correctly.
 - [ ] Trashed drafts do not show up in the conversation
 - [ ] Modal for editing folders works.
 - [ ] Opening mailbox from notification works on desktop
 - [ ] Search shows available folder filter correctly
 - [ ] Search view does not break when new mailbox is available (e.g. shared mailbox)

**Comment by charlag** [comment] 2024-10-08 08:18
Likely duplicate of #7687

**Comment by MasterInQuestion** [comment] 2024-10-08 10:47
Probably not..?
    I can send emails normally. (tested Firefox)

    And the issue is tested across mainstream Firefox, Chrome:
    Directly reproducible in Incognito / Private Browsing.

**Comment by charlag** [comment] 2024-10-08 15:31
Oh yeah, sorry, we did reproduce it quite easily

**Closed** 2024-10-18 08:28 UTC
Labels: bug
