### ISSUE TITLE
App v3.118.22 does not open in iOS 15.4

### ISSUE THREAD

**Issue by PaulLerner** [tutao/tutanota#6088] opened 2023-11-03 13:33 UTC
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Hi, it's pretty much all in the title: after updating to the mobile app v3.118.22 on my iPhone (iOS 15.4), I cannot login anymore. 
The screen stays stuck on "logging in..." ("connexion en cours" in French).

**To Reproduce**
1. Get the latest update on in the Apple App Store (v3.118.22)
2. Open the app

**Smartphone (please complete the following information):**
 - Device: iPhone 12 
 - OS: iOS 15.4
 - Version: 3.118.22

**Comment by charlag** [comment] 2023-11-03 13:56
Duplicate of #6056

**Closed by charlag** 2023-11-03 13:56 UTC
Labels: bug
