### ISSUE TITLE
Duplicate checkbox in move mail to spam folder dialog

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#3810] opened 2022-01-18 09:19 UTC
![spam-folder-dialog](https://user-images.githubusercontent.com/227270/149907487-2909f4d0-134b-40ff-8728-419529f4cb17.png)

**Comment by charlag** [comment] 2022-01-18 09:19
Duplicate of #3804

**Closed by charlag** 2022-01-18 09:19 UTC
Labels: dev bug
