### ISSUE TITLE
Broken image preview

### ISSUE THREAD

**Issue by mbellitti** [tutao/tutanota#1123] opened 2019-02-15 21:25 UTC
**Description**
Remote images are not shown even when allowing remote content.
They are still shown as attachments and can be downloaded.
 
**To Reproduce**
1. Click on "load remote images"
2. The images are not loaded

**Expected behavior**
The images should be loaded and visible in the email body

**Screenshots**
![broken_previews](https://user-images.githubusercontent.com/5868852/52885044-e9653180-313d-11e9-9010-70c4fe9bc579.png)

**Desktop (please complete the following information):**
 - OS: Manjaro 18
 - Desktop Environment: KDE Plasma 5

**Comment by charlag** [comment] 2019-02-18 07:06
Hey!
If images show up as files, it means that they're not remote, they're embedded.
We plan to support this with eventually.
duplicate of #609 

(if I'm wrong, feel free to reopen)

**Closed by charlag** 2019-02-18 07:06 UTC
Labels: bug, desktop
