### ISSUE TITLE
Preview of signature is editable

### ISSUE THREAD

**Issue by yopfox** [tutao/tutanota#4522] opened 2022-08-22 06:09 UTC
**Bug in web app**

**Describe the bug**
When viewing the preview of the default signature, the user is able to edit the preview by selecting some of the content and inputting a character. The inputted character won't be written, but the selected text will still disappear in the preview field.

**To Reproduce**
1. Go to User Settings -> Email
2. Select to edit the mail signature
3. Choose "Default" from the dropdown menu
4. Select any text in the preview field of the signature
5. While the text is selected, press any button to input some new text
6. Watch the selected text get deleted

**Expected behavior**
The text within the preview field should not be editable. Even though the edit is not saved, the preview field should still be fully read-only.

**Comment by charlag** [comment] 2022-08-22 07:11
Duplicate of https://github.com/tutao/tutanota/issues/2690

**Closed by charlag** 2022-08-22 07:11 UTC
Labels: bug, ui
