### ISSUE TITLE
export emails . send Confidental/encrypted to non-Tutanota mailbox

### ISSUE THREAD

**Issue by irvnriir** [tutao/tutanota#1739] opened 2020-01-13 20:57 UTC
1.0. exporting multiple messages create {Save As}/confirmation window for each . (issue)

2.1. please add an ability to add comments to {password-ed}/encrypted messages (alike in ProtonMail) .

2.2. according to [[*](https://www.reddit.com/r/tutanota/comments/dvmp5v/storage_of_confidential_email_messages/)], the sent emails are stored at price of the sender's storage space, and are not deleted when done such in the sender's mailbox . thats obviously absurd and i hope it'll be fixed soon enough .

### p.s.
i like Tutanota and wish you the best .

looking forward the offline ([email service]) usage https://github.com/tutao/tutanota/issues/590#issuecomment-490294609 and import features .

i saw few answers here, saying that its not for feature requests, but (even though i have issues listed) i just do not see other way of posting this .

(didn't {saw way to avoid / knew about} the "bug" label)

**Comment by charlag** [comment] 2020-01-14 10:42
Hi
First is a duplicate of #375 (Firefox doesn't allow downloading multiple files at once so I'm not sure we can do something about it).
The second is a feature request and we don't accept them here. You can post them on Reddit for example.
The third is duplicate of  #649

**Closed by charlag** 2020-01-14 10:42 UTC
Labels: bug

**Comment by irvnriir** [comment] 2020-01-16 10:14
@charlag, ty
