### ISSUE TITLE
Conversation view

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#6] opened 2014-12-09 02:13 UTC
As a user, I want to be able to see at a glance what other emails (older and and newer) a conversation contains so I don't have to dig through my inbox or deeply nested comments/quotes

## AC
- [x] #4979
- [ ] https://github.com/tutao/tutanota/issues/5051

## Original comment
Gmail has [conversation view](http://support.google.com/mail/answer/5900).

I have been looking for a [privacy-conscious email service](http://prxbx.com/email) that offers this
as well. I have been using [OpenMailbox](http://openmailbox.org) and [RiseUp](http://riseup.net), however they both
use RoundCube software.

RoundCube has had a ticket open on this [for 9 years](http://trac.roundcube.net/ticket/1369135) so who knows when they
will implement this, if ever. Please add conversation view so I can dump Gmail
for good.

**Comment by svnpenn** [comment] 2015-01-18 22:09
@mpfau it has been over a month, any updates?

**Comment by svnpenn** [comment] 2015-01-18 22:09
It has been over a month, any updates?

**Comment by mpfau** [comment] 2015-01-19 09:07
Sure. It has been upvoted and is one of the most wanted features. We are going to implement it soon.

**Comment by svnpenn** [comment] 2015-03-20 09:31
@armhub is this fixed?

**Comment by armhub** [comment] 2015-03-20 10:20
The conversation view is not implemented yet, but I closed this issue as we track it here: http://tutanota.uservoice.com/forums/237921-general/suggestions/6820765-conversation-view

**Comment by cup** [comment] 2018-09-08 00:49
@mpfau @armhub any update? its been almost 4 years now and im still using Gmail because this feature is missing from tutanota

**Comment by mpfau** [comment] 2018-09-10 15:41
@cup I will add it to our roadmap...

**Comment by vladimiry** [comment] 2018-09-11 18:59
I was exploring the possibility to enable conversation view mode as a part of this issue https://github.com/vladimiry/email-securely-app/issues/32#issuecomment-420379320 and so far it looks feasible. Tutanota maintains the `conversation entry` and `email message` entities, which are linked with each other using one-one reference. The conversation entry entity is needed to construct the tree-like conversation view mode based on its `previous/parent` property. But the thing is that backend removes the conversation entry in along with removing the corresponding email message, which makes the conversation consistency broken. Building the desktop app I can get around that with a simple trick of never removing the conversation entries, just ignoring removing from the local database when Tutanota does that. @charlag would appreciate any other ideas for handling the possible conversation consistency breaking issue.

**Comment by vladimiry** [comment] 2018-09-12 09:13
I was not fully correct writing that backend just removes the conversation entries. Now I see that backend sets the `entry.conversationType` value to 3 if there are remaining messages in the conversation, and removes all the linked conversation entries only when the conversation gets empty. Such scenario allows preserving the conversation tree consistency. I guess value 3 means `removed`? It's not yet listed here 
https://github.com/tutao/tutanota/blob/b689218e6bae45bb38cfef7929494c708aa0f252/src/api/common/TutanotaConstants.js#L148

**Comment by charlag** [comment] 2018-09-12 11:06
@vladimiry yup, that's just what I learned from the team
It is
`NEW REPLY FORWARD UNKNOWN // a message for which no mail exists in Tutanota (unknown external mail or deleted mail)`

we will update the definition

**Comment by vladimiry** [comment] 2018-09-25 06:15
If someone wants to try it in action, the first beta of a desktop app with conversation view mode of the local database explorer has been just [published](https://github.com/vladimiry/email-securely-app/releases/tag/v2.0.0-beta.1).

**Comment by gabrielmip** [comment] 2018-11-17 20:41
@vladimiry How independent is your work from the main Tutanota repo? Are you planning on submitting a PR here with the conversation view? Thanks!

**Comment by vladimiry** [comment] 2018-11-18 10:14
@gabrielmip the code of the desktop app I've been building is not designed to be submitted to the Tutanota repo. Besides, regarding the desktop app, there is an essential piece of work that is happening on the backend, which in the case of Tutanota is not open-sourced (not a part of this repo). The backend task is preparing the data for displaying in the conversation mode and I guess Tutanota team will need to adjust the server-side code first, ie the API. If you are interested in trying the desktop app, I'd recommend taking the latest beta from [this](https://github.com/vladimiry/email-securely-app/releases) page, it works quite stable despite of the beta status.

**Comment by charlag** [comment] 2018-11-19 06:43
@vladimiry would you mind sharing which part we would need to adjust? Conversations are recorded correctly afaik.

**Comment by charlag** [comment] 2018-11-19 09:02
@vladimiry thanks for sharing!
I think it's already does all the mapping. Mail has a reference to conversation entry (which is in a list). Conversation entry has a reference to the mail and to the previous conversation entry and there are some other parts I don't understand yet.

**Comment by vladimiry** [comment] 2018-11-19 09:33
> I think it's already does all the mapping.

It does the mapping, but the data convenient for displaying as the continuous feed is a different thing.

**Comment by vseshu** [comment] 2019-01-22 20:51
I downloaded the AppImage for the linux Desktop client and I'm not seeing any option to activate conversation view?  And my emails aren't showing up in conversation view? help?

**Comment by cup** [comment] 2019-01-22 21:22
https://github.com/tutao/tutanota/issues/1003

**Comment by charlag** [comment] 2019-01-23 06:59
@vseshu as you can see, the issue is open and on the roadmap. It means that it's only planned.

**Comment by vladimiry** [comment] 2019-01-23 07:15
@vseshu, conversation view mode at the moment is only supported by the unofficial desktop app link to which was provided above in the thread.

**Comment by vladimiry** [comment] 2019-01-25 04:35
Currently, the only way to verify installation packages consistency is comparing checksums as described in release notes of [this](https://github.com/vladimiry/email-securely-app/releases/tag/v2.0.0-beta.9) release. The most recent release at the moment is [v2.2.0](https://github.com/vladimiry/email-securely-app/releases/tag/v2.2.0). If you have more questions related to that app it would be better to raise them in the respective repository as it's irrelevant to discuss such stuff here.

**Comment by Gaspacchio** [comment] 2019-08-09 10:13
I've been looking forwarde seeing the conversation view implemented. It's now 5 years thaht this issue exists, do you plan to add it soon ?
To me, it's one of the most critical drawbacks.

**Comment by unrockbar** [comment] 2019-11-26 10:47
Does not look like this feature will be released any time soon 🤔

**Comment by Gaspacchio** [comment] 2019-11-26 10:50
It seems, indeed. Time to look the code and figure out how to implement it. I think I'm going to give it a shot, submit a PR and hope the team accepts it!

**Comment by ptrwllrd** [comment] 2019-11-26 10:51
This is what they said three days ago:

`Separate window and conversation view are planned for the coming months.`

https://www.reddit.com/r/tutanota/comments/e0459t/just_got_myself_a_protonmail_account_for/f8byydz/

Fingers crossed it's 1-2 months, not 9-11 ;)

**Comment by mpfau** [comment] 2019-11-26 12:50
@Gaspacchio just let us know if you have any questions!

**Comment by Gaspacchio** [comment] 2019-12-17 16:53
> It seems, indeed. Time to look the code and figure out how to implement it. I think I'm going to give it a shot, submit a PR and hope the team accepts it!
> https://github.com/tutao/tutanota/issues/6#issuecomment-558574053

OK, so I got excited. Implementing conversation view is kind of a huge task I'm still figuring out what is responsible for creating the mail view and it will probably take some time. I'll submit a WIP PR to keep you posted about my progress as soon as possible.

**Comment by vladimiry** [comment] 2019-12-17 16:58
@Gaspacchio if you are interested, conversation view is implemented [here](https://github.com/vladimiry/ElectronMail/) in local database/[store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) view mode for more than a year. But Tutanota-related stuff is going to be dropped soon. Ask questions in respective repoitory if needed.

**Comment by charlag** [comment] 2019-12-18 15:18
@vladimiry I think it could be extremely helpful if you linked to the place it is implemented in your app.

**Comment by vladimiry** [comment] 2019-12-18 17:00
To present the mails as a conversations list there is a need to first group the mails by conversations, then sort mails in each conversation by `mail.date` and then the last mail of each conversation will be put in a list for displaying (so `conversation.date` = `<newest mail in the conversation>.date`). Then all the items in the conversations list need to be sorted by that `conversation.date` property. So I handled the described stuff in the case of the desktop app as I have all the data loaded in memory but the web/in-browser version can't act the same way as the data is being loaded by portions (pagination/infinite scrolling). This is why I wrote before in this thread:

> The backend task is preparing the data for displaying in the conversation mode and I guess Tutanota team will need to adjust the server-side code first, ie the API.

<details><summary>Attaching animated explanation with one conversation consisted of 5 mails</summary>

The app initially supported [tree-like conversations items displaying](https://github.com/vladimiry/ElectronMail/issues/32#issuecomment-420379320) for Tutanota but then such rendering got dropped, so just plain list:

![demo3](https://user-images.githubusercontent.com/1560781/71104727-4fdb3600-21cd-11ea-892a-df0de0b43188.gif)

</details>

> @vladimiry I think it could be extremely helpful if you linked to the place it is implemented in your app.

Pointing to the code but it's not like a single code snippet and it's desktop-app specific:
- The app loads all the entities (mails/conversations/folders/contacts, bootstrap fetch first and then reactive syncing, details described [here](https://github.com/vladimiry/ElectronMail/issues/97)) and saves them in the local database and keeps it in memory. Data fetching code is here https://github.com/vladimiry/ElectronMail/blob/463ef7bb7b18aff58f8747ae35437dcbbe324347/src/electron-preload/webview/tutanota/api/build-db-patch.ts.
- Then there is logic that handles the described above stuff so it can be treaded as a backend API, located in https://github.com/vladimiry/ElectronMail/blob/463ef7bb7b18aff58f8747ae35437dcbbe324347/src/electron-main/api/endpoints-builders/database/folders-view.ts (forming virtual conversations cycle: https://github.com/vladimiry/ElectronMail/blob/463ef7bb7b18aff58f8747ae35437dcbbe324347/src/electron-main/api/endpoints-builders/database/folders-view.ts#L167-L192).
- And finally, there is a UI part https://github.com/vladimiry/ElectronMail/tree/463ef7bb7b18aff58f8747ae35437dcbbe324347/src/web/browser-window/app/_db-view

PS If someone wants to try the app in action, the `local store` feature doesn't work anymore in [released](https://github.com/vladimiry/ElectronMail/releases) version (you will get `body must be a string` validation error, which is expected to happen as data model got changed at the server/Tutanota side) and won't be as the functionality is [deprecated and planned for dropping](https://github.com/vladimiry/ElectronMail/issues/180). But the link to the working installation package can be found in [this](https://github.com/vladimiry/ElectronMail/issues/180#issuecomment-551305190) message or can be compiled from the source code.

**Comment by HarlemSquirrel** [comment] 2020-05-19 02:59
Hi all, is there any update on this? I've moved from Gmail and this would really be a nice feature to have.

**Comment by charlag** [comment] 2020-05-19 07:23
I have a working prototype but it's not decided whether it will be the final version or not.

**Comment by bedhub** [comment] 2024-01-15 13:19
We have conversation in the mail viewer for some time now. We still need conversations support in the mail list itself. We will track this particular case now here and do it later https://github.com/tutao/tutanota/issues/5051.

**Closed by bedhub** 2024-01-15 13:19 UTC
Labels: new feature, topic:conversation view
